{
  "name": "Profitability",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "SampleRows",
        "kind": "m",
        "expression": "Json.Document(Binary.Decompress(Binary.FromText(\"7L1Nk2zJcSz2V2hYs81Ofme+pShpI5PegjLTQgsaHjAEYY9vhsIMZKLJ9N/VVX356ma45+morKzqYF4u0Zi+uObIiRPu4eHxf/6/v/vnP//80z/8+Y+/+0/ub3/3y1/++NNf+v/wx9//9tPv/tPv/OHTm3NvR/rd3/7uv/3y82//dPvh+0/+8Ndff/vlv337Xe//9nd/+elPf/7l5/d/5v/46dff3v+BX3/603/76eff3n/wd7/8/Otf3//Ry2/90+9//vmnf37/4d//9stffnr/yb/85Zc//vUPv337ye//9NPf/Jdf/p/LP/n+t/jTL3/51/f/4j//4z/++Q8//c3f//Vf/uWf//zTr+//5f/119///Nuff/vX69/6j3/+9Q+//PXn3/7hXy5/zHH5m/z217/8/NMfr//hT3/55ddf/+HX3//zT7/+wx/e/z6/vv9t83F892vffvr+oz/88qf//g85f/mHfv7pt3/4y0//908///Wn/rff/9r/+Of//rsuHsf/97ffIetNIfu//fLbT//ll1/+69/8y+//8F/12PoJbIMK2zjANhBsvRfYBlPY/q+//Pzn9x/2qP7vP/3hn37+5Z9/+dO/Pv5Y37FSIJqP0XP9+P0e03oITOP3mHqG6dHeXJGYHk1i6lr5DtS//+Wv7//w96j+D3/99f1/89dfO1T/88+Xv0gH6//y07/+l19+/5c/qnCFh+oUwLpAgb38uMc2j16rcwWhTUFAm6xBu1c1yN/DGxDe+Ha8V4Pcw3v5IcIbTuGl9YDA+3f/9Ps/i3LwP7+D9Od3pH7qAE0S0JC+R9RRRGuir9a3kgSsHFMAtEezWENzqimYearJK56qHz3Vj98WT7WKp1q/BzfSShDf/AGVIAK4xX0H7v/0+5d2BRGKbfoc3ULRdUeVANcBwPm9H5MAh+B7gJstgNe8Xc23jD/e5LXPN+ZKKm3t0b38RW7wJloc3r9kBxQH/JLleNZ50Q8ZwntXiwCvVskTNERh9Ga//b6gCkF+wZyzhav6Azb1VAPvZ0OUbdflSz/oCw7SGNQsYfW2YL2HKEBroOlnL3h9/lzrMYL13/6AHtfL/10C2I6AZQpsffMRgK0S2NbuJmCPNFxTX65cOU04vHywMY6QTaWyQiD7AxdtAfs//vTrf53CVfNande81jLktf/2B4iWIMNrTbZAfeyrpamwg8/Wh26l/HJ9lGPxYA8osR35KrThesfWQcMF2LrSzhqup6gGQYKrqAauJYbtO/vqoW159Gxr8gm+Xc2nHthiDNipVnaq3roj0nqbsiy3o8dbayRfsSiebjWGsLbYQmugwTTy1qAcsiS0NKy3IbB6C0qi60hYZfXWHURCuDZiPbDue332797/B//y+3+e4WGPVQWVlsjLwuXH2rpQUgJ0y/vv92OFjoK1EcMNnzPccC7PPFlLnBHCXdX0C8OyS75nTg5tnDF0NxMQfD8VOwaUTALMKFmrn5SGZ2gIhhsG3w/F6FTscOztgnJbTqdiSly1X7OpiRhnZLK5bcOJWCUfsia/Yz7aQvSxlzr/DVN/wD5+XaDaJKodG3N0HPbeHvgmUWXtwd0S7SPiwdQnq6heqhv2XIW8VGC4vmNhjkxtPr5bgCnTvf2SD5ca1ZmHmpwG1W/tKlNjHJNloZH1xRysd9WAmQebNSUgjJwxmVSAIMfhvpqD9SELh1MMbQcejgCKzNTM1neMy5G5V7w4YpxwxETiiHHxs77qpV4ujV7AzVyhgdY16ga8I0qXE5ajwx7E82Oa+SmNfkTDXEdXxbbHtXcg0iHNxcwF6izBteQV/YC2cZ35cFUVqKmMQK0MVF8AVG8N1HsK7AywRTVLiHUEbGGjhGvR7oEN1oDdZQQeerJFpjRXsoWmTmI8ymGNNDDv49IILgMfV02yJUhDRbawfsu7JLFN9rC9691O4Rs8bWUvP1Y7Z5tHSdZd/oQe32wP36n2a2qywE20WaI8HuP6gCDnIDHuuRgZ11yVw+tw5hPl0Ie7C+/K2uAVoI48ng4e77g45FAQ11okrtUWro99z5RsgQ1qwPR98kmLxPXtnFS6Qs/K6CDsqFAWqPHAndLcJywq4BBMwXIHXdjF5LmC5sbDGKB7+ehjT8X49Msz96yHz5j/vrnVCd6bql3RW0N1jZNDI35zIwchZbwxOIgFKUkHUgzW8J2sCjPNV6P1NsomIaSRnkAsB+kQLULsV8PI0PYdzPzmcYEpS4Rru1+ufd7awvTWQpBOpPHSgsaJFJMxgO9pFGY+ZlE1vw1DbTGy+a2DsVjMxnCdqrxTcpjGKRNGg1zmVY7QLXSEzPMtXP92ALgO6m6nh08rYWs+a/P+RLDKDD9sraJVJh3CKhM7Yub52mhm/kR4vC6Fu79rDzDeGZPMYKLrE3zKhkPdWCMRa1KUX7OOlXm64Ui2x5mEG1c822nXp8qVOLB9uniP75NKuMHJcpsOW8hu5p1LHT3zdAJ5uDeH3jkygSyfqIwv8dVqHvArLEnJ20N2Taugeby8VyhyL3fcLRxkLzeKvdzUsTRPB2dHgG7h8kOA+FjxNdvKtpx6hsYHEOUtIAcuEt1Sz8B9+kdNI46PPmoh3fNROxLjELDqmHpuxtdE2pvH2Q7o4+l+aPeem6VsC9tt9nNTz824UP6t7+qrLTrsWp75oD3iCIUWTFETBm6lj3gepWHJB1YQIMynGsR2XQTVXfbFFUOd1AziOb33HDTfr8Hic2iwUD5efi6eNAZvYKvJPScj6vjH8rNiZFbiCgnswU28+X2byzdJyxpyKrBwk1vpF26yMwat9tFCfdU0XWkwNkchIQxNdpGZ7MBjl70xXHew2eaOf93MzB2oiYGasMouifV6qNlS1YFBt+UqPNmTjuugxlDEt2Ngge+KBdbKAr8NK3bFNkM32UL3MV+CxknDjQmwMzrVceVsC83NBje5T1Akg5urmiinjkxN9HFRPzupdk2ZwBIFuboVZCFXe9huNmbIzR7E03RMNSMb0DHn7qBj7jgIH/NRBnyVjo8Fvvv43tx6qL2YOvMf4SgyHKV0lCyQQc41GRyjlkky+BeEWNvG1lvDds2KgwZivuIg8B3XBhabBDt7pWdoo9UyB0Z8xDenLx80zM8Z1EOGb78vTWBy+an0zGw0Gztw2xxmY86d5v89f6tsfnPEeUgHP1kr82x8U+T4pvSsjI9vUFNITFPI7pXIGs6cKD05I3L4BzmLACoOyidi6eZVReupdKWnZVRWvNRXzepuvJ/2Lt9u0PQGXEWA1bzhgkOqWAd8lmWgWgN2WgjXTG9GQniDKI+xEB4y2Wx4c3K1oTRryM5XWBW/5SX28mO1CTQ1JodLx1ftaNhtr0x8ukhTgJ8uvySFatVOgwJmvtMgRYSRBlbInYsoj19VZw3f+a5Lgeig6VI3XJV5kQLYOmpHwSIRbj+SVRvUA4xO6+ITX72JAx8zTa9AXXQy5GdooyuKjJ8arOG71xindlQs8pWG9P4d/LwqhPYF2tcUwgOaG6uc5ZzY6UrGAFDnskgArckcvJvE/tRsDtlVq+eqJ0x3z1OUUs1w+/zIRKjJAuOOn0WujHtGfMke78udSqbvD9ZqDNpFIzMNW6O9Liw3jEdmEZcb3qER+DZj+K4a92o4m2bF37uRwEB4MCQotJ6s8atu4c1j9QVJrFvw/+rna2Xi23qyxndzMtvNgU1Tf7w6p2aGADdVpF0eHnNqdB8S2t3mjeG6KphC83J5MkUDJWeYTOGIzCAFstYTNjrbuRA2SGgnhK2ee0WVEE9Lj6pqwN9tukN5TCxTxXmp37RoDdhVSoOqL6NSg5NNw1BryNgzNHmnNFkDeFFeswJentfsZabKOK85YKaKcyJTpfWUjebaXZbRvSy+qJ0vSaeYThVWDX0H20948G0cLVwcqwyg7LZiC9eHomo02A6yagqYw07iapg3rEprWOtZGp38viNLDmNgfEJ55ZO1v8TbeoLGV0oaVFt6CdYvebb7+MKufdoN3FsIiExPwDO7OKXs+tyvvmpuJR7MHc4YwvNjYNWqGR8DEwvTeA4cKrEwJelgcoc3huw+TudrTMd32A7PZwlDI03FXuYkf2zeMz/ucVlun54YG4+K66fuMjASAHckLdGphPPMkQuyYzkNvnwNuIoH/CLL6HtbYQzZhxQxTY4oVxYi5DafiGKOGEN8kQvp7sjGsJ2XbObdYjXqJZtYSHhzg0PcR0fMEk1fOwoLsUKfc5pY8X2WojB9AMoFtaAQC9HEigS4WgN4/nKhyhrCTxdiJOPJ9cJIIhmDTGR0R7OG7PTxUpX+xRUFD8X25IBpIsU2Q629Hdi9AjuanB2YIQqTs5gWdWDPWUW9ZzgJq6jD8eTFTYqdbpMo9/SMb+7oDp7HFdF2jx0z1DxgLjd6+KidWJoc+ahBtrtz3ha0aya/mlGPyqM7Gvuy6uCBoLmeoPEZhCMJw8RefvgF5PexhQhFPeD7EEFSs/HBB4fEzMtcIOd6Xsb3oiKICuy+aXv5Jt8ng0m+8q82MnFY4a3Kh5psAfqQK/cBU26+x5PrWDBQAGujc9kWuNN0bH6Arp+e01uGsGrmXM/F+BJfZDdJMNOuHp80Xi/JrFGA+4JbOs5Ve8BOS7YPKLZ6tdYxh3OAUxnONXvI7rCz425nR67A8vtEuMRHZfCZa+fbOz2cd9YQ3mER3XlvDdZ9HPnOd9zrltIqQy5h1YycMgz3Y7s6QtiWauCjNXA3cy86n6whvNlKifMdLct0F/WyU4Kx2DAmq1951dDorVPnO4qW+UpfYee1YOaQVpkTFnoZuU6j9jLO6TS+Y2eZz3ESOD5YyHCIC9Ta6SmOQvIaDHHW4NhxsUzGNtfqGvDffQwJTPenJ2zaz95Cr6+okllCYieIaLJSSEs+WtOmcA2/VQWLj/3glemHHmLrXHDmYH2QJygK6YgngLl2rgAEbw7T3Y4au9AzMDL9ujZYcjbOGix3vlX6jDHNlP/Tc/kbt0Tc0LB8UWSw2B5AwUI0hu68o0NjQOLNQIS+6sTREdjRXZjZhp540fWbS2XAFguz2yeI17PC21V+JJ7e7pKUE4fx7VXltg/ZGMSr9hk0IPOFBncAux1uNDhyDTJIdhuKMYzXHdC6S/zSK1+sGyM9bs/A+A7ZQTz3LMHqCxKwZ7zLg68aarYnX7VIRFvnZGqgC80cvGpqBtBqVnEy/7A5DGiNQ2M45WfII24hgVdsh2GXaPXCcYM7Xl0TDMdQuOisIbtmAjk9gFSPH4mS6ORCtIveGrxbyDWx42e3uxnyUgYkJBARLN5/T35Xn0eMxmDdaSMvJmPg7pUf6mJHzQpdKb2ET2BqyhNXSrdyg8aOmBUyFrsa7h3Ge2CH26VQPILwstwqhbLLxUcX1gi7sRqEd6obm0prpc4E2TmM4igKE8hgrhs7ilZoFqPzxMeI66WT56Qfq8Iz8/LBWFcCO86nqawlw97hlo9gB9s9urLUUbRCF/UudQGRhbqwJJ5mmeSoqQrcTwMZl0PFMWLGZchVIuxtIbzLJQ2Xgi1gd0p0d6lnazxC1AOhYGO0OCEtrDzFqQoFGxRcj2xiXHSpcQH1hZSsQbtolKb5sA1GaYeMdB9fQg4Y6R5Tlhhnaxg/RNY0yA7Imp6pffsD5JQS32/P1PiEPTJsYWGnfN0k2G4qtkvVGMCbzChTM4brDhunNwv+FRcey3oQUEkXNhEnvHzuq5ztaIY7w6EvhTaAopB7bsY3IzPJZcUYd1fdEmz3OhbnsjeH8C6z3xzMQbtPrLDLPT2jK5IXQUyRZXf9s75u48GWyzEnY7g+KCooCsJAVAge0tbG/VdjZ7sDhN7mjpXdTqGKxd4D73bDFM2HuyWbB+wK1i1MuaNklY4nL6ZnLLa4s3csAHaXuUPumFilU7MLYwCHDcmmCPkM2GfICKaRbdaQVReDqcVSFcP1Q1gDY7gOu66b8+MKKx+U4ZEM5lOYufy0uypenDV4txqhF28N3v3GkaXjZZWu+F6CLWEBghhB0mn24pMX/ObGk3T8AAdlx7msFacP78VDYhytYbwJPSsdPat8rBPeHKZ/4Hpqntjue2aFsLMjVbI5lHdLDivFHMTb3NAoPWmj6cJHIl0EhoFcAzFeja3dfOHSk7bR8qRUx+irDffrDEuX0MK8gvPtY6VTcGJkkdjyzd60sCuyXC1vsMqTyJ24OCGWL15Bs3X3pTpj2G5SDWrP1vhtw0gi8omEE1/uUwAVZ/4iJwYJnuhjia32BYixqMEauKti2DSKDj+rI9vccRCbKuiudiyt0WmEUm24fhnvZGnLEJ6pEDyqsQmAh0mNxZEhpZP4dmSt8Z2pg5n20Rlymu/+YpujocSQmo1BvErLmT6x44tWyknXFlRw4SNIhIsxhDc5Glc7ktZ4CmaCfTRG0tIpk1g+/pmLxuUnzT4im5UnzVIgEhnkO9eOozUehRnZSTMyWFvC0R5bBdaAO1oF9netArPJpUfD461RsALwqs5MNWyjrRkI6OPW7EAB3WUpoDdnDeP56XAvNPDd38F4+BoE1APLUQVIJZ4dVWv8HJ+DgQRP1P9sff3JvYJVL2kLBjG+p/ZODdQK35vCYOc47BhyJLMfl2H403q+xjXzAvd72bHOrz/GZS/ioiVb8D6WpatpG3iULtEfObCB4Jqh0W09ReNLJ4nF6UOjm++Hdec5TyvGkN1IfmzVGLbT3n1NIRhY9wWqJ7b9SFcnE9bYnpzxAVqEGCHW16ayQHGctoVo/M8DWwjan09sIcz+DJ+ua69hCdZ9zkX5o2difHjm3pyiq031lYXgvCPgNEy3MzlFwfzhjQG5yaKZP3rexa/FxTePSyWoFbi0QkqcPq6hKKqD4xrotRvf1yiN8C0PV7r90fEtdyuy4lKRQ2SBEVx19BWXOffpsfyRenz5pa3GThWAMcEd39eEpy+km8608kfugeXDhfoxx/0kDTP7RUrMRmmj/igGAd7k7dYeWi59B3bKbM0FnmW2hCnJSxuCOTzBUzJuokaXJMqtR5mLtZnkuZLt9OjP2rEf8FqBd4c5ePdYgPDO9chSldZ5YhzHBfVllXeNOV/5hOkLlg/45P3iEmWRGHuDGD92oVPxiRs0vmjIPWl8AxmUXb98AuBgEOB5J7kC3IGRXI7Ihlw4U28ChGh7Jygb120DJCzQ7mEmjmnbKADvBFvjIqMnCdokY2HFadS7GoaZjd/LTUmFKj5a+f3268IIhr1CNobrbj5n74oxhHfrFwRlG0q7yIbJHZ7PvmcvmZ6bGkG4ZhDfNbkLqqVfatV3Thqdh9kLOSuMzt4fBlF+KHhUte3L5XSUe0+yQxyRexOovV4wNz6naMwfhmtop0PKxfcLpmxhgzEFGslPxhRURq8IrDcG7FRpmDM+q0vwWJdkJbgAxj1ju+k74i54gDUI5BXtWCFK7ld/e+rm6DRIGxoyET34tH2p+XUpyNUeh8JXjL5JR5UQ9xTO0bGFcxA6xjb+ZjaBt/dAe9+TOcenFxVSXyMZDF3/B7962VpTIPi2dZPpY8Nt65Qwe8wHET3mfTEH7arHO518E+Q65Tj4RrNO6X3P5BwNbtLGsiy7kvaQh19ZGBTi5NC/X6jBHMVJ3yyi+1h90Gi/GhVtHMVARLQAFDkcFqHdbt/ah57EOTq5eOca5IQEWnZmUs2XFWG76Xnvn74e5JH5XFolmfncTeQ3LSIbUz4T/o61j/jbr38mRQTB5vjNDsdudpBVtRWK8LQWMS9FqHUIetXLQwa3D9EaqttNMkKyBvEel5F8ELyNiL9XciH1HUYunC/3Czw/QiysD8UeymvEynmtUi1Usm1LUoQFg+O5WYGxZGyEF1nWN9SDQ7MH8y57rT72ZO42mJNfOSgT5Cv3BTvDdr0m0ZlDdkNzdez5m+d7LZjtRPmbc1+Ist1OOPYUzpNRRmSjDPqSq7+fJK8D2Wh8oY/RHsQPRY48kDiS7wkccYxzBNSDY8/mPJ1oXAI4NQCn0xPuT+2G55L2+LEPSPIfXhLWlYlsDmK1z3rqE1fTIAmuyI9cGqY5FM+u2RV5zc7HYg7cVd2EomPjzYS2k2ikRCTshHs25/lYwzHCjAeB3AzNeGbHNg0yhMINYa6OTO1BD47NIMwbWf/SYRDfB+qwRnTndbgm8P+NyzAbfXoHRSIJUse3ifCqKC3D/rPgvR9qrJy8RWgfCi5RVV2+KfuhPujCS2omkzjvwTCVgkWEtzNXJsHl6Ej5wuVAkmBc7v5WDdXK+fI7X33VpbeyK+QXbVnCmqzBukuoURLEje9stQ/v7ydGk7BmUvRY2Z0/CeQidGQndZd1ZK5gSya4Gx/FZaZRQkLBmj3ZTS5Z+SQ4Gx0NOdwj4l+005rwohPE86Oh4KXqcMIlGlMdAqgOqSdrN+efGCLjngAZIp+fTni2eUfzcAfuHd/u2CRKkRSFN2zGcs/TAhlcXI99BFiBIysYJcw0Y887CqSaH/NuTIqSQ109oybZpCSZnUGQ53fh5p+w88AnTpbhHOETDhcwcs/YAk/mch9dwmdbnOczixenRxmRJHNP2AIXfQ/W8uLzXWJOffDrNp8sF6tccTn5upWMSy7ukk0n4I3W4N2u/iZrCD92o0K5PMRwPbD5HR+pYMdGXYD2N/fELXCtN7EbuXjY6nxBYHGmp+2DYT4Xa8Bu6OvL1RrIu7UPgr0RvffjGDH2Z6Dr1KmQjSdONKctaFHtQKsJSXI6JEcuh0GU9zoX5IvgcUT7vaaDk0gISAcvUxuHizsJRYV41aZsESyOqL/XfGW8Oooaz/ll4teMM+1s0ZdgDdndykK0BvAWwZ5FsDY+r2gs2BO+aBOkbWXcuurNDvLWr1cBBRke9rwtMcrWgLIVQdl4gJQnsTCYj+jmPmX7J8OUYhHkzbbfSk/fbotEIuAI1V82e1ukre9j+C3NILyPrWapijHfzboMLHuEx+tZOeFdkdzkWZHa07bIF4ca4Ms+cuX+qwH78onac7XIp0KJXXICWWeODz8vt0QBM9/ult+30W53IpM3tEpWbw/ix6iF5qs2ohb+LmpBe2AMKag9d4tkcnFtIUjQJ+ZYnzfBP9hVkRrNIbvR4XJfe/IWiap+lcokeaNS2bHguzZ9TFfTLQyO6eLZ15N7uoH1u4GUhJ66RSr0XsxmikTPq4T5wv22KWI80Buu8oxWc0iFPduAz7aYA3e63nYFgR9/HZRbASuHFOCUUFZzUG42WKuCm/FxxLcP1if91yQ3W73EpkD2RfFQ7bAI7m7L2k2wtNGdFuLshS4spjUUYlrl1Xh7RypvaPA1G6u8xZOv2Rsac5ogaFRBv/ieMDsOfU/Hkh53s8CMFswhvMiiowF4YNFpUoY8segcGm9DE1yNR2+9Nw4Ki851e+Bh/7+6453SbpyqeQjDZteRL5wjn7hkDdY1mai819Vlos71uq3nZLfld3ndEReA4DNW8hnbffUoTSsrUFVBOU27aApAfLO8ZNF6apa4Uq7M3zvC3ZLC1ry39WQt0eCnyw4FlgIga/n0oNAzkg2hHMxPeMB8Mx7wVOK+qU26b1pP0hLXGSvbTgFzyOmj/eHOi12dwJagfaAcKHAdlAN0h5w4b6ihv0jeEA5nC9hdVtXC0ROyxL3mla1gI7BpQcP12CLV/B6Vy3KQfpIhe1ScpLvLJpYAt+diiQqORyGCI44cXJc5NO3D28trE46ehyWuieU3HwFhSBD42lMgM8Ij1xO0cgLrwxwA3DOyxJ2k+aPp+gTgZMPErwH2lSP1cAiuxm2lhfEILBNrcjD28j2GQzA17nvMrH3AMnGcJ7n8OMdWwlHNwbpZ9W3mAH5wB0VDK2h/lmE7bbiDUlHB9VkouOF2PfcKzi11RIg3mBtLxJtgYL1nersnyMZ3nFfosO310kAaXM/VMpfFtJfDJmKzHny0U1zY8xVspGxu+CnzgVG2A0QG583huxmrcD1vyzx03rN0BhDPw5LTCXc9YJiurwN2NFunwGZ8utEasNvdtwouWcN4fvfEz++eeAexb+PdkxwK9gy1QM/QE7VMU1sua5V4eBTEsvxZTOzqCNPzqsAnlOF5E8rgij0wd0rXDK5nZ5lLu44N03GC9pl0s9o7OtUcDEzPAtkTx/O3P0DICQkbhJ6X5aGTVLODNiM7rlJ25+Zp9LiSl1ee3YhGXBpd5L7iynO43QX7wHgUbSEJGhPP06mD4dW3MKdbBW2joFqWCl7wtFFIgBz9sJnaVyxLTZlII59Z4sJJ8MOorINoN1UaGIIXNI0b8dyHnPBJBG9ZUyKeczSFtw7KoylzvYMP5rCd999pmtyBAY8sWI9NeKGSBesk96uDj+awfXC7WtM6cO8NGkfH5ptCQrFKA3QFOxsFc2vQ/US7+bHOigafzSGrrgnQhmlqgiuDzVSIO3fDhtcT3uuA9/piDtr9LrYG3/O1W3zeRLpQXmLZnaIUwIs1T/ng0pg07MaRdt4qGnbTUSXCzRrC07GwGg6hupIyjoRN7EoKmvbD7fjBB6o8Sx7vOVMynD5bmXr+ZbV5zRFL78l1n4OUXp+g9oaepZWRnEvuW6KRv75UzoWvmmodjX/VEnRiJ181vsMjcO3pWaGO0suCRIBXi1FYr3+1cwMIziKSA/I7JBExNVIUPHRjIViEd7eM3RB6slZ4qAV2ZvTSRFgk4kxbm+a90RjHcmKNbkS/8R4EnJAMYvuYk0Ep7n7eNZy4GGjXAJvAIfR0rRAJ/cN4Lpy79IJSOxYViL1yYEPoiVvhGnpgTxhMTmu2AB8TeBXvdyDwRlhKORF4A1tKcfiEBWEbnQckUQFAJ2aOrO1cHZo1aKe48FQcocZWOrzEyrYrI8B7C838gJdovB+LKVgXyGLKkuHamvHl9PRSPbtks3fwm0dnDt/pDBGNwDuIEBGgjuND/u0PkBvX8EGL3hywk5xiRtEJqqc78ugF8nQ9lgZB3HgEg2M3b6HrnRi7L4zJU6kNA8tIbHcE5TWWbvEGAbAhRmPQ7rUsEXu+dssxluHmGPCIyU1ftms5F1JKC0OQyULjr5pXRAuFmI0BvMmd8RCLMWCXnVucDsW6Xo9S1YYUAOIaJMA9U6t8ZaJALjTdsEwvv7c4s+szCL1wmFs8Dr1goW4QrBtiMwfug/s+yorLS66eC3/494SvAWx6t+imD3hppvlFSYcVd1TS0/0DoIVphCpTw4BKeNTHxnSC7q/i4DI5Y8iumbdrujE+bxcAD6ft3379szSc5I3huxlVSz1VqzwUJ7ArX7jC2vkZnr7VDpDOX7n1qOyOLQ1U2U2IbDSH7HO8u/fMLuHTNp5dkg9bxPKQzIG8hrFNE7ZrZKWOsMWC7/i9ZxYIC8I2OnkQMLwFO7P8fWf2qhmb3TjukARp4ztAnpxeJQ6Hw6+gbfO7gJrWbLAMWJOsC344WfOJWHmDjJEPqZqDdjvnSBKsjYyGP46M4/olpgh87SlAw0tst1gRSyjvoz1kZxHf6ZGFiiEPRhYh3TGyuDgkSSd8wFcuCw5HB/HOQSlm1v+XOxxMH1oMOdiCdocTzSEL5kYHxA5jo5kZvVULHa+tepsMwrtL25uzQXD/nR77ClnQs9HOGjmAgO5d91m+yGJ5bIr2qsA8uVLJKmzDAlsN4rpNwlDuWdnt5FfXz0aI2738EErAl4YGGL2PFG5Lf2YQfuwAwnx/EDCccNwfsJEPBu0WZw7dx6Lz1l6dGsbnsY21CJmlpSdjjW9aenIBEHWxL2luZzZ+BieC8fGenAiu5PFeX7TAt2dkje5aXtYl0MkAE4l4/z2fjf38JRpDdqc9lNKTssaT9AqkkVEDjrtfSlj+SZsf8jzhpk/pWVnjQ7T25oGV4SrKXNF97PVOJekNttQEticbap4m6aG+WIo9dB87QaOAd3CCRv1yv/2+KAwZBIXSc7VG5mjxEh+PCiOLj79/jrZ9UHRp1gDeKCrrZoP+AHcUAKlxLyw7PbPKQqZBmnvIAowohy4yT0aUVY4oqzMI87RQptFzBkpZgfnZiVjGVn7Q2F+9QWwfI8TzfBgueIzpsA/EwoAFQtA1GmB60cthbQKlyHicig0/3K5ajdawfawr0+g4g7YsVnmB9YRTlIwnWN3ltqCAV1A2Purx5LAPczjV+/Hd/zRgzfYgXtU9aB4zd5hWdfMQPfnAeQmyoG/8QFUjQegsp+HlZWJmzsaPKBFRh0uRbBIMOz+1WoN1+sv2wIcNG7ITQ1NgVSGgbbd2lO36fxPdtTzwYiiWBdfuliJXNrsqoYw3u7g1cdLsJqJDZpAhb8MeM8huUQya63Ed3fuS28HM49gFZX1VKzavkAXMNh63Yo3EnbsAeefNW4N3j4DNFnpc6fbfESHCKZFR8Nx5iaWldl5XwGzCk1IbWH4T2PBaNIjtFH+YCjZWXQweNbbsY4bhjy31CPPlNJypMeUmLrkrvs0suGVr0K7Zu9ZcRRksXl9+vML02Io1aHeJ4W61R5bPKQOEXNBl1eO8TXh+ELdGpOFtgr5HKKQaYKBba/Zw3UsIizciZgfijew38RD8bHgMUGHbn8kk3NfAEA9vDdpJBXcqY6jQPtcdUsMddmTZoYYbgpcgB2sgr8naVUFMHefOyfSxYd5uzhg/Fo4gIRZ8jc6BlfdCw/fHEJ6+6zd1vJKfmZCQDm9MJDajxMMz8RAcjc8oPayisAlPOD9L9dzqYDekJR7ZGsY7rKnGQxA1nmP8DiIetwXRscT7YV0dptnX2sFFUPXt6ynyGw9B0fjQzJHtCIzXPbWYP32fWiPjDl7qNwFR91pjZFoYvNWeojk+13l/qyg2YsbCMXH+b6WqoKgBA1VBLymwaIUA1ud4A9IMrtPxbRrta5DflmCRZ+5ff9fTMMfnOBXgpAdlwmdW8meItsYnZdH1bMzxJZ7IJmUwdXBxVdjKqp5ruuXSNlyNlIUElNcFiyAvbA4G0Kqbg3HcdmULPa5AT+t6NuZGwYPY06Ig5id62gfmklMkd3AzzXmovCdH0xxZoXSwABxdMoftYyYQTQ3mLhDwOw99IKmSGYTc/o2up2KO6LjXykCWTbAytImc7adJ5Ss95eONNOIpzwFA7omZo2LYxXmHxAydd3nFRs9eocXR9SzN8cS2wBICcBoR8wKA91lgj65ZA3fy9U595xKdrVcn5XI3osOpEe2mCYz9YQ3jDebA0Qv2RnVG5QkUtyQLej5VTLVrwnsyPMV8kipWySnmLC8xR++tIfsMu83g8WrtNsNTB+26bilU8pQlxsEaxsvqrmbeQ0FOEuNx3a2IsS+AsWBtRDK/1l2i75C4+PAJMX7yRo9lnJNFnB9q0jTTiUGXdpm2L5EnvWBv/PhfZAk4yN7qaUjLM6fsUxrlKCArgLYzdpwXIp4V+NYVayBvcqIu+moN2XnJTDMDGoS+ghp5opglpkZWUCN9z9lu9KLrHSq5koRzi/D9KPil7hujl5hjOIyhu8Ud5hh6uub5sC2zU7YYfOPCAhL8WKrF/EeMVFq9WTdDNQg9W/N0/ENyF1i87hcuR0zpZNSLB0dsh1a8EjH/NVQnAe6pmqcDCpJfTN2OeWLq/uiEYsaRN8hsEsiOA5sases2UBpCz9D8aEBx4DEO0iOsSX/dwi0WekrmyVDiw9qAAY/E2rAiPnO6+ZrvvdSNF73+6XEvIvSMzPNwpsCWKJHolinDyAOTYOP9QbGI7Q5CeeiJmB9djZEuR9YghNPpwzPpgtG13xgEGePil4PQoEg8pC6Vs0r7I65KxcMcvPMNwrxJN4CMcNIjRDZWP4A4RMHIRgKNg7qAzddEXVjlDZlBeTDlSV495KkVxcWjSoS9NYR3SXKMMViD9rGqq4B2UHULhIWcVN2DhIVU+KbFnpbdFDFpaUIJDCxNJZyyspfsmsy7SfGTdiKMO9YwFPykJXPozjsXNIsnA+eCc7B6dmJd8GT5zAG02Ry028U/x9gztcCV3PDmULRBpvb62mvebB6rOXy32J6KPVMLfE8CUy0YrmmJ1PhQyzDP0/TtAlMbHSoMqSdpgVv42covMTOFY8FsZz/DWHLWMF62uj594d4F9Yn7ksm5NCdZRfLWQN5k0JN6uhZ4olAmh2px+ptOh7+vsYcpgB3Yw5CunZj4I6FrDm4sxxStobvJbD0la8DuMexJgqcNd6bQ/Yw7UyvSbbZyMKViDN1d5IVUjQE7nbGv6mwHIfsu3pOyTzNeg8OSINgZX5JKbNCD2Rbt+zXKl/vuVOAOaq1z0B+c1NuD6bke0p9jPqyBu11gW3bWIH5MFFO84YEo1mBN9UQTy2xN1cMnLQtiRj0Ml3WpDOgiMfNLDtbuYA3JwRys6w7VDvK0dYdqOawAqcRTELGRW4FIt+BWyPd7nDeWGHOyhuyDISEaLwhVZpq8LTcOCUl4Wc4HcVguZsHFaAgesYdRe/Oiq2fzYaOqrUieNoqb1OPA0cviPz5bD7pXLvbAfSxhbP4qorseOlTGPR/XE4qS6b7/UODbM7KbW0zg6w8Fvvcv66yb906lCDne2sq05zJqEjKGPTeZ9Zx7XhbJNPJ6OMajJA5Gm5mR+q77UOWwhut+wSul52SRTHyveo1XHEWcaBqel8ykyguhSiPs/o/NIAeOJV2WY8nijUG8cPIwIBCqycMcfyg9H4uj+aMPgCbwsZdbyeeOTXLx1oOv5iSMlPlqEsxySjSG7Q4bUSUZA3XNbomKRdDlErCQD9dL3ntXonxJC3np2VnkG5KBLO+gaWlNmv504rPX9AUjnx2MHMJwah5ZB4YrkqWnZpEPcxzLbUTq4JZoX5t0ttUcsLuRstLMQTw/431gxFv0E97gA5vwytvJsQpeRuc4l21/CLNiio2z1dEOXuxLvDTVWQN2o42dKmgYH+REFsEGakJcse7/GHHQnE7mJQEzck+Iw0GGjxhQXoMxbB8rCGvj14ZFgcavYbUVpIyPddqbR2xBPgjuywjEXH6g0pgwJyVUwczogqTzJHSYnOF6bYdgeYmkZmuwPmRkVuhdAx/zmkdarKH52M10leLFKS6e1ji5mx7YaQ3c8K89E7ut6cjj3mhfhuPe+fvp2N/9NJ/LqiW5U+5alRvBtXFANqkCDYtAM4jrPAFTADsgYHr2xfREh6GhrWdfiU/FPFvghYLQJmKxn6gdTEsHWuGA7YqAhbk5cwDvEnjbvDlo14wYeF+gGzHM9QWtp1yJTxUjK7CYC/hZoPiLDF+Kl/qaq1AtGgR3zdxGM2GgYxsvMxLGY5uGGQk+yYyElgxivMp9MG0+ABF8bD6IqIK/wyNR7slYItPHa6YwOawD63lrrps95F5WKTMD+/K34cz34NZjvDdCY0TxXnor1gB+bB9ahTBfiL78uMd3vBNdEtbhAhFWrVoDdz97UhNMjS/wFkgdZ0xtIvNj8ek41bqT+irJyd45S7JyQSZZXf89MYXuY+qNZuow8CeAMH4i3kSijF+XVQW4zhi42/lD0yEYG03JdgcwtvgB+vp93k22ddIRjAG7W+ubjmgM4fl1SE2qKF+HrHCxfrwQmR2JFZUBQOkQvI2nkONAgmo4L75HMBWsNJibOV8ktuPZWfEesXXFA7iCrtGbh86T+ASc9nQb0tPTnjUHzTSkQmexGb5eZrEBN246ijWAdwpmTEe1Bu8Ot0rSITga94BUtoSOt0pS+kQse/Ie3wzQRXWmYMQnCuFqYGJKTlA1uoh6MdogmwCjTfJfKfpOeRg0g7WpUUVyziCwO1htkuvZ2S3DRoSvedidJvpY/I92AQEO1gDeI+0yuZ6cZT4JDmwrihxEXnFDch+rc3LJGrjzXZhqKMyRzajnjjsxqufCZYLksjVon9AhDHowTYcwPiRJXm5EeHt6lslQ+OOWEe7y4QZEPWYa3YURghrZZpAgWO4JEAzsYxZgVplcNYjuvCqmSb4cyGIJRpUnupg7iC4moW0GoX1ow0RREQYLJhLZ8XYJszzis73dl/7Alk6BLwk2EGxFzvfev12yqsudUXV5Fu41N12XhnsNUZGe0iIBdtYAfujlzq9GYbLoyeP15IsGwePJe2vYPmbSU0gJ3KO3RErwgo/xie97+4UGUmy/6uk6xDM2zYxvQyQvWNlwaRqjauCx+nN/7jO726nlf36kRBKIEcKOLUpCwkryyRrA8+2XU5SCQfuFW+mT5SBbg3OVA0TxYrkBRGriI/tHIu81yOXT5AUf45HNmXy9iP51nq3ydMO+hi4MHPu+waxsHAyU2HHZNwhsTr6aw3aziY5v5hB+wvdsUHlV37O5sns7GvmBKz+X7j9i2z/ZSV1z82XN2GHl8d6hmsCO9+Yg9YTgrEG82ZctCF5GRuofNibMB8Jc91g+EWwWHysxnHeXgqBofGH9IHkVxHZXjjPGuxjVKSGBjx4chjOON6oz6RfQWhN6bnYLx5W4YkUAXL17vcBo/H5GCj01K3Syc8khh300FGryV0ayzQW+05ILuyZjN3nFXRNfssQ4W8P4MflmXr3RSzdstZosmoRiDdptZr6hJ2qFznbeKy/OdsgXLZ4vmrx2AqF8v4rne/J6AWEsvT1PK0Qjv+7xHFW+XdzjccfpOe/VKgNwCNVQcjD0je2OqW9zpDC8oXf0dvDBDLj7pLOl6Myhu5mIE3uiVvjIJ8NZI2bBmyRq217vTbEna4XuSF02KNFYDs83TJzYeKDyzoA6yM4WoI5zsxNtxtCxEKM5WB/zjWo+atw3Cre4xs7RSo5x1SaOcaUoeBoXdQO7IgkjYP/ycxpTq74DaH2T16LG2OaEx6JyKxLbbAzbZankGpSpv9HLrNFhuFjCG6g1yMJQjAG8SbJYioKj8QTi9BYwKQRvy8av7MOmln/p023al1scftQOJxEWJI3uoF1W+1DXRcF8otNd5A2ZWgEe0QlwkZ6chqAmUjn2ueVkWgH5sUZ35URt2OqyiVqSWUIpCaY23EJTXaY/hfYZ1rGZnT7dKs/cDDj1tOx2E6KDM7EYACi4+ftsplfs78z0t4PUIEzTPwkNqmwUcQDlTT0rq3zJJEEVYNi60u5+qkvPzWoEscG5WVcgvmJ8bzYEEl8B6RWpZ2aVa7kODKTMjrvk2W5mcEzJGL7TB6NUQu7gYlRoYCQfX40qzEj+hhOelI1BO18TNFINLwnqcpCYPE6kmtQzskr9+Rd5UREx6D5TF59rIv2kteU9QhsI5bLwTnYJ1R66m0i3qdmDdoeA/XRb8v8Alg8c3EcM8WeX4+qahKu9QnNTdvYgXrgWxSFWrUUNg8sziVVAV2MWrIwvRCSSv0SYQ7p/3ezBajslzgRPgY1VTh5OdvlKxtGDc1nOHrIgZiNDOZnrQM3NZQUv+/d/KiblaA3UTTqELLgYD2NDwsAsYRMe8gdrgd3zEClnY8Bul0qecjEG8bQtQeW+5VOyBNriiTWB6TMObc5ZMDI+YXBgWKI3ZuvU3Y29Q8lzMwjwVpn6t9WHD4T5JMez2HcckqXDlFXfTPB76Sna7eqcGJcRJgHjsjJhYVq4HKWpwIPtqHrH3m9JzOxcoS0r3hqy23jDSrAG7VbpbKVnao3MJa+nqA/cpyYj9K92L81HZ0f4qJ0YmNhHzeOSSUnGsJ1f3/EKZAfrOw5z78b7O3TEgwupJRtDdo991NIztEbGkdeod+m4Y1Hv6X7ZZusA11KNYbvMh6sRx+iXDK7DDN2MGY/DNHkbpjRjAK/pE1RMjcPrpM952CvkjEbncEin880Q9oEwH08WyFdgKxCuTCxN7ivhVGcO2nkriIrxci9IQV13aAeJgZhE3QG5K9Wbw/Yx7UZDHbh2g9+1E+kmstPqmIZZBUHjg98Ih0zo0d/707MfMTbCt0zT5g7y76K/I374486U3FKHhxutIbvZHmoVBI3v9GVGI2BMGe63j++cXVGzNWhXDdQUIPN5mnqaRriaR4AFV6M3+y4JFmAoxwSLbjnq2a7cGbFxIOVG+JydSLmNfM6ugc8C12oM1ykaMUWGEy25RbI0P3q4UXXDszZjAG9Tc2/a+AeydMB+SdLGIRo5ZPLZmPL16HK3sw5djiygKhF1BhFdUxCm68H1YpauHrSI9SBFibGgZ6PhOgnBw+F6d5BLjfHuYUxNUDSe36hbQe0OmbwmLsi6hbR1PO3qP+EJAEXCS6qEX6Ev7AVvsgbvdnfVW+4hHm6notIAHvM1N363sO630sPKL0glcq4eYf3qE79WQ59bNYjxFmuUrRlE9t//ckS+fcA+cOXziPeGF7f8sOGdMpMur7eajoEXXPCLjX38xC7mg2gW8uEMgruGsWlKg0o0H/UKidmapECWD98jTKcSF/0GU4lBvzndRntpZJCdOxH5CLYAnp6xa6Zpgxm7i2AaGw/Zoyd1F1Jz8yFoGh9JvHNe5BE4Tgufxe2vTiWe8TqOsizQwTCOsnAHC9sPkHCTj2QR3t1MOPkQVI3K55c9awxpWrNn/YBTZCpZu6bB/a4iC28aBmtfegciRUpoizlop6uDKgJvUB4cJu6P60NjXYNrcjiRD8HTeJqjY2wCwS0TMs72doZ8CMLG7x9l0jjgzN0f9z/fp91G07xlHoV1PTStCsNqtQLE6agCYneYg3je7aR4tgOzk6TEY6dTYWvt0Jo5wdrogIKs/0Wy/tc59F6xhTJzT1l3Zn1qaJmdNwbmHtkL2QVjuM43BxpMR80BHlQ/Iw9sOcJHEBVcz81uZVaQB7yNiOShnV/9fTa4Kg/pANxvCqIOXHq9D2Tc7Hpe5uiu1EVOUByZa6cZg88UbIyO1rPLxtDdoh3oiZijqzxHffPYZVXgCv4zS8hz7xbMNLOcLAQw3ox62UsoMephUaLcMzJHpPLrwhTSXRJMXqfiBpc7oDUH7AeGMQ+i2GT71SzCOp+0oAgcHdhz3SpIfc+6HFfE0SLGkoNcWHOtb5MrG9k7e9hupst4bw/i6WOIigI7uoW4phb0LMzxMUNm53YwIzccC2jYA0dRH0hVOHCVb5yqwLJAXAAW5qM1bDe4nn41OX6PKh8rFBiM0XuSOb2SI0wl6A9erA933PGNkXkRANlsDdlp1eABRUavxjg2KA/Iv7zgX3ztIcJ1ZLZ42s3Bpu2gazQDje7FRQNYehjLBgG5l3OSe/lqDeE1DcHg5eoagvFh5H/7A0SnlfDlCvLF5zON5QiSYKC2Qkhc5bedjhGEc4djx63TOBDCYQ7j+SMFmg/a4ErBNShUIDtMCfIfoMuwCgmtMwftTqskOQgmRmNGL0GucHgamVi3avbs/tbwZeQcekZ2E2uEXxEfLUrgXzsXM9WEhWgM1jVeDg3GrzhrlkMyhu/8R+yBb1jRf8KCD+wTJjdycuhZmefLZB7ylliWc/qyBAWjga059NzM860cz2y2OF6YW0lfvs+rgHbQJEhWNiy7335fplklgLdahHezm+k59DTN0xnZUViuAgo3zr1SEjN85izHwxqszzl7OJiYDe5BQKJgGhXgjCbxKM/N5uisgbxmA0plChscTYebGyftLzm5cdHYBcg9UfN0ZKZMfXeX6N3XL0lO5TYOUvXxKv04Vr8kfMVFnk7PMVgE+LG8ZwW+g7xnTH8/yXsObOHBQaMWBX/jd/syybnCYVr5zAbyzEphdRE1JnsAbyf2xmwP5D16NcHjeAyeh1u/1CaW7093nZfNoHNQOZ4HI6CQwPF8MgY6EgP3QHCrNXAfuvarwXdw7DcDvCe3fh17uwE3qWOzBu8uGY5XBvI9tKM1SZn5zNYk22dt2Y8YhpeT4G80b/Bym1aRTFy+f7uvv4JmKjk3J8HZRvtRJPIZqsJEiNjzxAfFw+Xag1Z4aKQ2JJAmU0/ZbmN4KTxgK4bCw3EY2u9VMWM+FLr8WDkXagGv1MaUJcrRHsoLT31yx67+1CeHFnCVoCZ7oO5SdXuCFvi0Lbz5BtBCOmaqXyf5mg3HzKkYQ3ivdqwaQ3c+zUaB6CDMRlaFIQOujAAHJMCpZ2iBb1AGSFthqHZhK7MEbR5VzUrfANaa1ny+ck/KAh/5xDevcOu6ep5dszz2w3DEaM49Fwt8M+ogNmj04Lju3/4XX0U0mo6bs7cG8HaBbFnQMr40VVg8Ofa2YWpZfWkqkMojwnMAfLrjBlqMOKcMUc4pc7SI7mOJNiuzRoeZNixrNMEYOCeL8O5WhAVF42tqjez/kln7xDG0pxVhBb68CMNNqbEp8kCKdqFtAuFiDeHpYdoDszQ8tH4ySgss9CqQFq1ag3ZVdVCdAOapglJzHBaIWFFz9EVqjlmwNT70wUOfNP3qyyKaLGdql8MYwg/Ng1V6+WAg/G39RDkRPthJA49Vojhj+G6i7hbB3/iwMpDjaKjj+PsX3Lc/o5pLsAbwHttrJVrDdbP1tSKYG5+2Z3bVHm0ML/6gTc0iVL68kxVhXVpmybZg3SEApxRbmG43oSw9R7utAck0Edy4xPlEXmG92SUdrzRryO6R01J7Phb51LeyiRpJeP3K0EG71v3qzGE8/TVTHYrhnzPfop6XpUhYw5sH10LteVmk8/VLkAje6AKb7ulU7cWfNCOsrPasLI52LB0+XRhLlNMIgRcHkCmeMTfdhCYRHtpuvAOE3eEkwtEawg/t/nXvlntEBqt/AlaOKQAq0ezJWOTblBWCM2mpTadH+37QE9W5ZmsQb9KJFWu4PrYErHiwg0pQQL89WQJmd00qyLdVELPReJ2kiUCV7fJ0v2C6bnUtojaDGE+fqVZFlA4CdsGsf3Kqmq1YZ+jD2mEQ2wcTCTUtLg8bCh7sTWO5sZGLky7AzckmSBoZr8fLKmWAe9W4ShnCEpL20Gjygcmkfirp6bcNXdBNsDQ6lXTsGDgJ3u+mEOz9Prczs1p+WzCI8UMLU8oDPaxAwL2TOEzXvNzoIW0vKA1NELXRuio5aI8XJ1+cvzC16DeIj8ebtOP0+OxYREvBz5ugbXwwkdjnLcHbLZ+5H5+xyj7zeAcZQ03G7Y4jhmrCtN3aZNhuywbR3Wp3qvXc7ZYdIIfseFN5xZbPpsdoW7WG6kOzdZXmyKVz/J6dNLzMtoC3kFqzBu4uTt1rrt730PJ5zztZUyxZ5+/n7LNG3fmcJhVJG7xZmPacZDUdpMxWabUphzMG7GPm0QfShBzepz0zjzKvmIchezm8MXwfzHlUBC4MerCLarBgHlGOnpQlMp6MF9O+vEEZ6R2J+9f+HukMDIe2lSOaw/Wx5CvFUx0kX2Hm6+RTTeYg3cspWo6ehyU+6nUQeJVIpFg+XsoSbN+fK0exhuyqoHjN49UcOximxLODlPIcUjmqNXwfEhYVoA6ERbWqWGjLBQmO5RA0jE99M7uciJc+584cLDaNaijDwDXagOaOjaM1M9kWDGLFHQYB3uyMRHHOIMjzja4mR3fQ6WLSzckpukROoQQ52ClOsDI6+72EvMIxYBLyumqws8VyVHHBILSr5pLTlzqi+lBHJScO0pEkytEgylvQYCc4GzUtHIlxNjLZOW3MnuEeNd87ZHPwbuF1LE7wNX512cPwgV2mO02yWJ7SZDhrsDjB0vjRWt2JiO4e0vNhNZyNV5ygaPRW7YGfL/ZYXToN2X/qEsTUcIffj0lefspGnvJ43TDDeIUe4tvNTzMQ7/Qd884cvHvwB99Ts1s8qUxtw3AFTG07F8aeGRhkN1Cs+J6hZTKSvNoU5IUTZlPo7rAz6rDadgd6zXyiY70j0DE7wsrk+cTioz1k97l8VHxPzTJdTL3c9cO9PhinfWlgkFnR0WdrCO/kaSy+52iZzHw+XKN4RQbJb5pSbVZBbPSEePHVIsS7nPAqvlmEd7IMT3GMQtlbAfY2QjpHZG8hS/Z2uyLzgTPPNvfkxgHRd+OqE7bz3oZ5awN6Hk92I1jChT/ANRKcRXQfckLPG6EdrAafGKE9KcJZrgaXIDgcP6xaPnL4Pz2JdNpHLJ6tTXUOqvCFk31VlkPaoPsNgrbxsGLHFAdcRsun12Re4t3XIPuSXLwSojlkH9sD1sza+Rqwy9KkO0Y3HLXAqtR7OSxJwJvMwbsmA1oVVcxDoNFheqKcFeKELPCIBXXj85/GjOZA3cr3kwrlGZ8HneZTVv7BI45VrvudlIiScd/PXf41EPAK6sYHQY4dncJHHL/Xe18RQzinRnLJF6NEThaBI/NCkoahWkN3L7NpELSNTisuDS9GukHDG6c2rZ/I2pQ77XQFUEvaakTt4YgC5VuC5hXlWy6/PCeBbS/a/Us7e8VP6SNmHm+mFVhqOiPZLDO3nrwxU2JP1wrfoYpvHq2QGFQ6MWvbNYG/xJ6nlaHcq7l/cpz2DK++f6JY/uFJpdUJmDnEAK+ENliDdjeDQ+xZW+FSZGEp/GRQ/Nm07Qc7jVRiT9oKl8gw+oaFwH7h+7U6CYo9WytEIYvX25Xo34Xblde/yeN0bc1moGqSOTh3n2Q/NtwOrLp+rJgDeY9+rGdrhQs65c1hcDzm607kui0ODdBQtFfFupXYrGE7P/TRPFeVdn4y8aE3vHAn8JbF8gHr0B2N1AwnPl3a47SRd4PrJyU5c7A+h0EMGl0dgxhfUEyNPN4mQfbmQH6o3j6Q0ZLviWhx7BEHUhsEVRuJj9jqMvExvfp7Zt0pnQRP41F57/BCF0bg9avOMGur70xofOLgYoZxGArnKbCUxwR+nJQsgrswt2VM0VRTtRPHUyRjNXeZ0guEe6Z2O+4jEJZeBopwPdbIDI+F5mk48ODeDJhxTiZrjjBhTHBJPUmr1DN9GU3AATUcTfgJjrb6WoepkP6Sqjl0d9MhU8/YKg95qm++QoHAIxN1SodcGkk2H9TwYVRQrmP7wDz/oDXc9n8sobuVZTr3JK6OPL2HB4jB0+vdmg/c9C6bSn8cLLM5zOEeL7Q1dmXCNUTX20N3mV96evR+Ob6unb07stQW5FJbDvZg3ixrL/dErtKR0GUXXpFINBFvvOwZGz0MWHLP5SoZV6TL9iC5VgXbg85/lvj0kqXteSVCLUMor92WnC2iuxNTzsUiwntsFmfB43hsTmR7V2CBqvF+HveYBDHDMQYcGRWIE46c2Cw+4IetWQN3PjtH05INwnOcL/LdjgN0imc3wIq8AVZuJkgr2C7yOcy3ZZcfKzuzdrWoyuynLDEWBI4OiC4iD1j/yTpbOx8aP8PnYHnhtXhz2O5jdiiCtNH7XxeDDhQHNOhkd8YoVtdd+KJpwrtHstmlldLqZv5jmAxZGQLYaAzY3UTfIrgaX6g4CBdGgF132/IVl4U/6RoGZz30d1M4sgCrxDRbw3Qry2np6dnt/K04RkFO1qEj3fvTL9lrdXSNCkl19CsIOiU9OhQZqpMQV3sQb2XVKT1Ta3wTyIPnn1mhwhdKkDNPmJvNIP9paDZLDgOgwiEToG7+BiMIz1NhTUs2oMK+3UGFUyJUGIhwdcaA3Ww6UXui1uig+L17kC5J1vI61+4G+GlfNzvBkbWna43M2NJlFk/CkHEWf5yLOct9DlMll8ch+wRp/sNE5Fgj0clShPLQM7bG962OtwAmX3y+5XsP6uwC/JryML8NBIxtLJJVZGzpkIytJmMAPxiPoRla8niM4GE8MTbxNSbzBvy6ZWPoPjSeUGA7GE/oZxNsccVhHHIVrI3usGn9TxP3EvaXcmq1hvB0WJmm4x2klTWwPo0Dy1wl1qc38J7WZg3Y+VmwKgyZD4MjltvxNPhjBCenarLa3oSFD2T5UC28eXD14qTdl/v7sAeQNd6GNWcN2ek1QRX9Hdj8G0zZx7uCiYVuvuEeUPPWoL2rA5sy+o/S35p8uXn0DXOXdHQYpWV4t4KakTHldUtF9l9sS6WdYvuS7tZWgGGLxsBd1IJpSi9POwbz7rAFiygsvCMjX6/gZnwDs8G4kobluPJV7NewdNOyNYSXnU7QKJAUYycxHmbsZYS4AcLFGsIPOXc1ly65BScCkzgx7zp2iryAC6cJjjZacyWHVXAJ88sX4DUv9mUenNaMQfuYdUy13DrYz4bl9xP7WCBDCQdJ89dfv6Ebb/9ReKJJnAs0vRO62BPzMTT6jWbuM55XEoQhi6gergeYj9UKiAw0at5NRZuujMzR6AyDzByHOXDj3Bx6qBHyXerhe3T59uU7Z8OtKrT0H+e975OPfZi95VyPYA/kPZL96xHtQbvGVKb9ztHPnNZXFjBl72LVERinHmO6eXmx7UEOJxm8mwjI6KDlZkjd++WwAqYS0NwDyvcsC5zIZp+0JZecH0qa11Bg1W3Rccp8YadFMQSuHqUHlg8kHMmDxFb3/LKothZMr7k/sOWeoM09udp6sJCncEhxtx61h5aKu85B3HFkcbG+mlFwpgUctXyjiWioR7MG73R+loY3qHZ7TsKz6G4PdgdOkLNRsJ78ctFgvSXC7vwYTUMcBnM0svc3HqSFSgwhSfpBqhO0jC6gHN8C+j+7E9gmpj2b3kKoztsDdosV6+oEDePrJ44oCVhjuzb2pV+wqdPCnCjAdsSYKHjcjnCHkwD3ZOxWfeV2BA6AyXbEVFbhM4nClxJd15MwR3PeLl4bbG3Ra5M/y154tnVBgeuLEo6rywaBnV9TVSA72FKVsu042Y0h6yCQpbqejTmizVzd5ORgHbGHlTXlYKuzX9VVgxDPdwsqxw1vF9ArdtIvROIVC9IqVl0zCO4mnzPfMzPH09zyR7BYX3UhamxSU3yUQMxk3gzsYlnvFvOBtLpNPl3fszM3cutLWZxuWrfPOrGXLlvb0cW9NwjyfOegWjjh1QFPuJ90Dwdxk1aYq/uerDki5aYLDZauhcRocF1y7naf1Ojqozl0d1u0rj6Zw/iu79vUwZSL8Zlh26Rpt430cpcTenZzE5bd6gVtG51RIjc9YIa27ODtvLqrsupydbdA93CyJRFI++COAP1DMYjuTvuU1VeDCD92dUKjQw76BzTmjQFmaQER5pVekDc++mnspDBokfkzfBfLZVPZY4OZmsOLP+O5WmDD4DcHzVk47IG7Kita84x5WHSSqY/juOgDUx9dzhJlZw/ljeKMaxD8jRv685vDOGPUIObuCy+962FI+g2CvdFR2/EtQvOT3jedjtqebCqdsp/ziwgF1tqHBxEirrWHXCXGPYe7KWoyuBSeLwkuTf5ukLcmyKEnb55Phdybwyk8zIrToknmY/YGje981P1qDQ4OmZsH5hZ65ua5rB6Y+xEsu+37jQldaMDqtne+63XwbE+6Xk+ebcZnW6xhu2FbVq1hPM0rVJ6yQUMWYRllzCsi8++ifTf0nM3z+LFMBPVnNmS7uXTiYRHlbTaqorMI72OTTUXPO5hsqueagYCbQXiIPWXzfHMivQWFpl7PvZE/7DnyGoM5kB8bXMzPLVpRjy1q8tD81uZF8xujOWz3SRGoUbA2PnIrJKSQ7ArHY1HtXVYhFGWYVwhogccVomIL7ItsgWO2iPMmh+xqFCSO7wId4Duj+5bp/jMJ+4bw1ljNQbvL7mVs5qDdwZ6eBFvjQ6DI8kXgvFo7FXlfsiysPSjMyNoBHcP41WbWMeD1r5oEW+PbVg1EdLayMmfxXb7HZkboTd4gtsv0SM20jes5YEMd6pGe2FCrtKGmYBDm+aMemtrLb3rI2ju85/Ht96WBD2uvIGs0Ocs5dmQNl7KPU7L27IUr1dXQ0ZgCHCTjz1pxLDYL7TmpZ2o3Q4kQ0eUxD3pK+FhDhKeE3qnsN51WNlxfYVoZ6Rx6khZocNYltgXnw9CQtWqNC5tRy1IxCPN0nZgvExGmmSdVopFp5nXEKbDt6Vqgo7bLxjYencACXE9TMZ7rMpupEjybTFLiUTJZIzXi8kUUADdrAG+Wy3uV075HmIdn+Y9i0PcQ4NLpDga+9LqH1dic7IyhO533pGkbBnlPAtKTsCfHtJwAN2lq9sZgfTAydt53GuBy84nvlF1ubhDwknu+FvgIyLMja+jby186xJyyoKou4Q4pMVke9FgWoj2Ip+qu3XNrNSd7GG+hOmTB2/hwzTPbPwI7E2m6MrVMM7Lk4x/17If6ckgYXC7mcH3IMD3vl/awrn3il07s9ngAZ04WVI3vswUW042Cznn25tNtkSpxgfcLFaEduyILgbYhss0csvMJL5o2lwe8yA5hnO5SmJUMykERxIzf/Gkk1ZiElaWJcMgHXuxcKMagGNxxF9AnMlXL0H4VZw/afTz+RZAzvrZWICCSmW9S+lpd16ouVoJBjB/bztZUiMGxQPimnbxhR75pcMu9lmgQ38fyBTTUl8cLqMH99vtyQQVfr6Bm/OJP+OhrPzmKUML9je4T1y81uiPdvpRDnxH5LeQLh+PLks0h/JAtZ96Vg9ENJ6acSobDHrPmSzGH7i6dWc/SbqtAMrIM3GRkWNlWUIn9zNGlWcNY+3invAzXi3Of1ts2lMX+7Q8QJTcBYas9YYt00H4kpt9gnpa7/0TCUr1R81wHgmNNMGgfgltY5rx30DHUnrFFvtPqIY6TH0pwnzRkL3Ga2vqk1Z60RTpR06ZM+6+7MWx40l57zhbJQOLjiLPmzmWcaBs2vvZRe74WiXZ+7cjIgWzUIOtnJtNnWkWmBu98oqadpzmWWIacuCaDGK/ibcpqrHBLj1NzKrql4yHd0jUbRHm+TqiS4QZ1osCJlZM6EciJFbiwUnviFukOENkLjGwvMNez3vfHNZzWag7k+fAGRfUdZDfI6jtcu/z2+58usNVmDtfNHOlNMDi+y1bevEL1daGsYHAPTeAVwA4m8LLujsfv7PE6nGY2QeC4oK41N9x/VHRRdzZ1TFCl944MZUw3QyN689bg3ebhCtbGkyIbO7JCZsX/YfEHaadFawCvCdSaztO6hvfr8rRiwSfsiwQ4WQN4i3as9UTttgcvYcWkHHJM0C0ouQ+a0DWDIG4qwwXMExN6YAuYB6gNradqiQecFnarESfwp83u6imF+VPZrVqDdptmoadoaRS96fGeM4o3S0rtQ5lDmpIwCB3CVP9x7lBl79Z7+W6vmy620N3p4kc7nDV4d+gT2tFTs0Qma9eAnAOpGQTkOLdEVFjFIFT1gZcHcKGPSEQlO2tRdgvt6Fla4rM1thBI+O+a2dpm48t2RHMQz6eNKFAdxAjgAsVJjADdTYFbgu1I5qCdL70abAe1N2OA1rj80gAtiNxsh6BpfJ7m4atGsV0WP7RZZnc7ikWUH2zPNIn+vD2LVebynrRnJWMwr3NZJPO2Q7A2vmalk3jr/fGFK0vEfCA6HnI9qRCR7WKD0tAOQdr4NlBkbl5o0PL99xKepT8q5ZzP7f7DysA+bkDa3GEM3R12hZtzxlDdIlekOcHV+BjNsQEwWvT8/X3Y9skXzQVzCM8vC2tMkINt4YgCznhh+MMwKVtdqd84QdD4nCeyuz9QE0p8LbSGbwU217OzW2CWzC9FuRwGPfFu+Wb1mTVNV8vjd+HWxDB+N5FTEz7IhtZlW7juVml7SpZH6yiyReDrKPfrjvM9guk1n+aqNVxXybmaWyn8YwY+3aGam4ib/4AvWc/IMp9E6Hx4c8ctl7YJfcl197QJeGOC4wqgCkRvx1c/EOXrPZ4kRTN9ZoVZYXphVdN0DRZW8ZraycIqY2LYHHhnDdg1vkaNm5z6Gj3sQ4w+Y7HhPoRPUQLcU7JMY9ycZ/HFCHA9FkUx7BRS2nywCPGqxYjpvQhf5Ese7UWkq2VP+m6ChLnnZ5lo5B/UN0iYCfX9LIh7cRWe8j2rzlGN48cSO0dFtDCf7OG6z2Zw89kevLsk4TQvSBof6mi9uSu8IWuWVjUqw2Br1SXZQQwXV6tmo7L5ag3j7TJFmm/WMN7FG3K7PPOBLN9Ja+yUJSDbBV+8PIzbaFZWC84cwo9dw9bUXr5PmaXaML6H7QNRcppUcoI3h+0Tputc0lFN1+fknCAYG52iXW76gAaJEU7he1inHfy7HMBuIVqDdqdF1RaSNXi3aRQETxsdA5T7aOwY4JwDb6VB19Y5wBZ6nnbL5u6+YxUSoxOLx5rYjVh68loVFcKNTAU6hJOb14G0CO4I0CP0/KwMB2qILQ7U/Is9IVPMd2BudAeEcY/djYlpuy5gwW320H1sUVVRdgd7qlK+GS+pUukRrjO3W3amHXAX7Z1oREg6m3BO6ubD8UTOGt089vyskGnwx4cNognJDcCZ7YgfYTgRe6JW+Bwzg3ksfkRu9t3D6UW1pxSJqRMpAxJ8YRpaFuwO/MTFLL9wMVgDd9mVcc2OBOXBoECO7U4HKpAuSwUy9ryt0B0qZfvr6oTUsNDioAnNG1gc2h2Z3K4SyvYGHURM5pB9aLymWqnk87WCDdp4vhZZgwbnUlrM5uB9TMxRwDsQcwS2Yymnkelaa4CsIG18KS3DYSpWdrtI4wcY8byLTFMUBi6yBF+0E7M5+6TBB01QNj7uScQxwvre1x9QmmJtg6SLq1qA/cJgYsnOz7gCYk4UrI3u91wsOVgUwJITzm9XPpVXzJ2boA0DGMvGi2kBx8LOybHwLbDJDMSLzoPycYTuPOjcPCI5c1hOdrhT+xKOEmGgaGVUchMytCoJWhIEjQjnHxCXzyF2/rBkY9CMJjQB52MKzHKx5N3rlgRLGwrosMNOGrEcV9C0BzReDahc401Ofs9ONN7U2A4VtGIpmsN2r3T+lnqWdjtGI5pdkiGCGsOX+kSmghj4YooL6s2Uj8mGUHJkgHxLPVmrXPAtrPGFzZR23P+he4BQzKz7DHoGXF49uSp+kOVVn2B7NRVryD4mMsybeN2BMThjlYHG4OCkIvWMrY5WqkgKGUabu1U7VXukBqSerNXRDpAm/MaHuzuzlTVBIzIMioJvcNZnXBUuG8KkKghgbyvBRoDdbuyTe+JWR6s/8iYVXf1pp8bdlxM3TY3gE0yZnDckbhmD85rMzcveHMSbnPNpuWdslQu89c0BJ0ZXzozssFo5N2SDzNEatPPKuaYQcOFcr5oX0ipgp5AFSaMnfBz7oDERJ8x0YZv3uVkQNG44z+xwO858lrzbaQ+kqhfjHkjf7jCYJpaT94bx27lYg/ahkY+iKgwmPuppT2M2soAhArlaQ3ZKHDN72KtlwdCGqWO4noby41deB52K4B75nALMLcdUuBANskiYb7boD5h5All485hAhgny8cuOfBnO2S3OGsJ7GBqKt4brbjS49FztdmpRxBdLFy+9UDcVI7D/JmuJBjHeyMdbkkF872mCp0KiVTGbJ/nmLGYTU1xKT9wan/98kxc+O5MycXt1WQU2WxyKNYDXbKpML6pAbzaO0YrYm4UKvVnP4hodsbl3kpElwGQB8/6zao/R46mh+3VAxjsHSS3qMT5bx8ZsHllyacbwnQ7PUplzuPaABwFPArSYc8ShsHPzihgB9ikXbrkrUnXhlsML0EpYe67WyPTyI8VUMXJv/u56u3Lcrgo6H8zbPRaD8cy96pqF6q1BO78wrMF2tDCMgaYnC8Ms0BSlsip4Gh1XXo6DYrwxZu+mGalsqTFag+7I0ODusDnlQGxOFVxONRpEd9HGsKbPfcmluipoGk0svJhNoTrg9yys2ReeXgXUEDTVIcuTpGN2yLJhYRAEbbTz4zAHEnd+8mfrVIuHa9CCaerCoAVzEaruuAeLrLnFI6FVkDM6AXKegEsGw3OFYV8bWa0GwX1MFls3WRtKYmyylsF2XptBbHfb/bkJjR8g092fo0KKHjPjuLrINrLZ9k9zBjHecEbcBHWjm0BHZJ5elCHj+erw4ibCtgu9BXPALtpnvat/UPcO335fOqQR12gO14dGPiozA5/5YLz8ydiHiY84lWgdV7t6W+cXA1O5W3x84lBYmzNCY0aUo598XfSTtaFKkLM5kKdrrqonGxRdhwfGx4W3sUBT18Bx2koPLpmrxUuiKaaMYKJp+boI/5n1QHWK9PDjxlKkMyREttpDPFpewxUKVM3y6eTyKeFklg9QtGYN2mXHERRX1zixqG7F/OdDbreF7fyUQvFkB0MK9YAiMx3Sg1b2jqvrceVrgYEEQqJZbyJOb/+1wPdf9j3ENJTsYB0DMUx369gvGQNZT+V9BzhYBHgvTef9l6NFlPdarnhHWXA4visYYBrP6nE4zUZ/ked0qV429pwyvYy84WwN3Z0OUrzjK/jbaCeTxEvjBOP+ZKKFM03VcvZgptnu8JWFTKrvm5OzoXdoBW/jsXAO9tqo7vCV8ejQT8yft0tS2xkGP7WK2k46KoDc7IG8S8D/ZQGrR5dvDka2mgnqb/vM8v/SzUE7+s47ys4eyvMK5QNjIeeAbJyMho6DsA0f8RvnvD18d+MaTjA6vkJY2QohDpCPL7sEb7tORGsYqyWJudMJfA6HCZ3ej919JKEzy4DOdzCSNWhXuXiOz3VgbuJZowK7nr/dGgoxPybBnGTvKr2+PzMcU/SObrGH7j7j+Xd8qz18N4k8fQe3p26OrmS6A+RJegzT1l0gzYiTJ2ZAzP/wLpAnMf81SpB9z+Ac3247wL/DQHZxzQteo6Bp5B6qoMEphaGGFhti7BNi3PM3R/exLhqEYuOiy6b/wU/YvCPrrSH7UFycAthBWhxRzTiyha4TkzGy7wmbo8Ohy0UFsfZKhd+8AtotsnTegY3WgN0ng+Qd3Z6oOTIP+vieKS5oO5+/sGswmpTxDrGgbHQkdGl68XAYNr1zYenzeqTdFcJ3YAVbo7OKo8G2UPyI/Rfz+Im7YbvuYb1DK4galXjJGUHWKFzlpceh3Wyv+B1jwde4RpYJxpjT6er5qO0Zz3dKbMg6JSeMgg0TEXJ8ACEnHOawXTMqVo2D+Kz48mPtsDjgkdyYsnzBoSdqN24sz4Ao8gcmgjMWr7LMS2U4ZjuRyjyZssEd13dsvTFsd+HAIRgDdjrSez7RO8KDHQd6l8bGwsT6FHqi5unqyiXPEMVdIGpdNza9FrQmr3c6rvdqjtbF9caC4qMvgHCyhvA+1pzQszRPhN14zdIBmQHLwpKdtseWgjTjYL4U5LJP2o9ZOGqBdszF9x9KdIsxdNdsaQ/mv7ot7ckJcOipmef7Kp45eKEI1PN4/9VgTiW7XANy2DesQXBOGw7RGosreyMybmjm0N1h7/2De3wPLF+eqBALSRMx1tx432N/LTpzwO6igkVvDtpp3VYjHAyEWw977ifaLduTyNhuRcHC+B5KhAOtXBS/Pz96ZUvwQIYABvCeGXTZpkQ4cOIQozlw13gUVFHHdKYDixJjk0LGRYkL3ZUYJ3MYrxqcKY+wKdw246SRik6QeIATJApSRlMiL7NfzbXLuOpGwiYNWbGI7TbfN8HS+BG2QNDFPcsYT1uHHyg+6x3XZg3Xx3QalbWRCzUBTKQnU4dGok1dkOGmH6YRW/iuEXFV5YGquGBvHKu4gVhIHXzUkiBsPBvSwekUFiMQlzhuNhxNJm8N5FVmaE3BoA9ZPuOhE5occPX4hUvBGsKPXajRvN7RhRoPUuTZhRqq7MBZineEBY3jWZGZaZFoYlgTtDd/611jDhncei+w+jc+9R4D2f27TM4A3GQO3F1i4N7BzebAnZ5RaOrCYEShHk/82x8gP2ukJvSs7eZzku4FuK6Eg7TrfPqLpJ0pL79mr3LsyiM2hkg+a9UcwPNbwZr52mAr2Ll2x1rwx7q7rLqAbU/eAvcvZLhXQ8tC+cIEF7NnA92RewIX+KS9vTkIcEFTdL2/LdvTaZ57yhb4VNixOH+SivPyO1b2AwxzT9cCmbR9HA2ESBH0m9dz2eEZl3BnSFpUvd0wrLmRvV0HSf7v2PZELZBJxfXOMB5kREtD8jM678I4nP6Ldp//JjR4uhxagBUg7ZlZ4NerAtmaMpFRaNidm5M1ZLfJZMnZGrS7La5nQc5G56vkTJiP1PJLX+8nlfauHsEHmKiNe4QYWbImvt5qDttdjPtZ0DKe59bAVp4IZYhuSfO17GrKtJfhItNqzQyO7PsF2PcrhzmYt1EWijOH7XR1UDRjg+qgLg30MLYnYdxF8DIu5DbmcgJc82er68+NepwRdlX33EMajSoJyAnF8hLsYTyfHaI67s6zQzAV6yQ7xJNULIehWKVnajcXulyZcgAutg3+/iDCHyDfoiRzEO9iQC89ZYtcMHcs4QJ1xzLl0XugNkyFLwxmwEiIT2bAiRBi55ERl56vRa6VR1gFZh7e8yi3J+yvo4NBI42NHAwVHAyT0lipxjDdhgGXZgzZfZZ/a0/NIs3Fu9RZTDTHOpu//4TNTs22OyxRnTWIpwmapsUdMDTvoM6OWVqmXQKStOqtQbuKomnkG87RXADP2IimfdjLRJvrgEnUnqZFvgyI9xfZCrsrSwTIh+JuNPVXJTOcuM6ZzECMjjWag3aLK+7vyCZzyC7aBJye+kCO23jqE1HXfccGMBYkjc/XC5xspo6xmayx1eYFDbYD90KB+cSJgYHdm6k4nqiCpfG5ZWLnZhLi22YEsqVOaE37MGDB31QvHQ0Olez8JFz5qdUivhtFudVmEeAdR2xN8DieCPsN1/5zh0hPSJEvOjszaCs09ugyaimYUQ/nbM1ZA/ieOjHTrDWVBpGH4k5jGsT1oyihFSyO71NhLiGNyJrYvFz6jZsXetWft8QinRxhF00QN54Fm958+Lz8hs+q71O74KnaO1q5TNL9NFR4qi6soUWDOM/fXXwg1cVlUH/HZK6xRAHXUKRsySC+G7Vpredxt014MWyT+LJhWz6+TkWbG7txFViuZQ/PWsaKa9m+wFp2K8YwXjhxG9QI/cTtbGeYnqFhXURP5hKdGJMLP/R+84stqNZNZq2Zw3aX80lX/L/Hlg43L8frIE2A3KFZE6c1/24VwA6erfrJBiatOywI1+OpxoDdLAnjvTibg3iftswdPX1LfLoZIEuAra3kU3B/pCCtd1bYwzo6q0YeLbj2JraBnjcznh4ZR/XEuCZ2t04K6+5IxiDexdXrDkHVePhmgpEblSHdCmin40VUHGKQL0LcJCcZI4750WkvJkgaPVh3uQkIhnR2E3AipuFZx780De8LMkbcUc0BPF8aNJMJXhn0ZaGojFDvDM0cro9dVFM4evlBtSBveHBgAVSJ6O1C+weiPA6ykVwG3E1JK5qv6TQRTVM7SLyI0NSOA0UyoQwFjP3OOWO4PmQYmfeLeMD2xC+SCLYuEHAFH+OTtMBi+4ExuLBoa2K3AHTngkGU90h5cy4axPaxiBFVvibPGMGz1+OYkUKoWWlAIJygZnyWFmCxiokK7ftlCl0+4UIzuoY/DMzozsP1iZM0AUeOTzhcB3QuG4P2IYeIyoHOLSJXcLQ2kerYx411Dj05u8W9CXhlFBmD17Xjk9LwhO5hKjd6AHGDB3yCMLue4j15wNUgwnuIjq4naHk4QYPvGpmgrSFoT9nG5lRNtY09SdRuZ2w/kCUziHSdQUDIG1LfcpxV3Rfjashe6nzP2jKPgUxvHmMgQXacS9J7cNRj2QDpvDeI7jIPjsb0Tz041clXPPTgpEb03QY498Qtk7HEx76KJuF41fdtg5RY53vWlslU4qMGw6SSyI+X578C2DXKuaZH49I5rFuNxfODFOGIRbinbnl4tyoByhg3kvNpD/H0rCeNw2m0StyAXozZW4qEXryR5tf37C1zg39gYUTY/Ka4gL7tJDv4Yg3dVfspmikmrQ8y/3y4oFIw/twdMv7c+WoN4akCPKVP6jKJhuokSxvASDjnBYfj2mR+c7gChCH+8fwq7jOWBU33wLdzEx/g8iw4D3MhlqW1hMZNvd6p4Rt16l0B0R1fiwXrgy8AsDMG8ENOPQ2rGFj1AkhnJ1a9g0hnRPoNPYO7BZ6KBpi0ZtAAx9d6eK1nlbkQrGG7ihprgKbMWMuLEzubHRDhaA3hde7+sSD5NEUy9DytEK03XfsEtDhAn1DCCql3k1RIF7I1ZB/aotIAO1iiEsieLFB5OnonI4rQU7RChXStOpZOraXa7vYxD5kCXu4hk9+wUeeVyWUPVl6rOWD3WQ52oWdlZZQBR87WwWQtnK6mvXh51Up3cIs1NgLwJuFvLjpjwM7v/T2wrlr026rBB7atSp6soGM8/K2yRJEKyJ5KYU89tjj1eFV7f0MtgXlxkO7GYA3fPVILXRRMjK/3+A/J9rNE+bwqMGuHEWVMFpHd5lMmiBkPemsf//p/5uoPKzrcvfamouBmdLhzGbBDmikZsM+MHlb68jSTX+7Lw43KE2veQTYqfcKVyljNYbtXdp6LgqLxwZljgzM0P050uo/I46ZdpbcUITPA7vJFS84ctLtdRnBJ0DQ+kizQNdCMbnfaNrzEU2rNz596mna79SFomscMdKBp10yH1/E0y1QiRXOwPmYV05QE7hRrRWxbj41iNV38i6LuNp8kuD1Pq3RRQnlTrduTePl+mjmHY8rGoN3J4Jh6hlb5kMdDUUjMXpPu/pTNv9t/ByOe1DO0SoVy5wi2bHkqv7zgmp1MpmYO2B23p26LlB8wc7k8s4YBjaNlRnpcHHth606Kyz1Xq3T95PJhw6A8jBs7/bC9Vn1UvWGq3zhXtApkzoFoDQEw9tYwfuwIo9KYy7AN4B8d32GMhSlkaHLMgqoNBfQG8IKAfk04fK21ybKSk6M5aOcvs84fZg1AKcZ3WTOjFP5AQ15O5rDdxeuYBVvj+zw6v7776pAhg1mPudjDd4+pRK72kL2rKuDzVcAb/CiPUP9Fa+RunQtwuM5lwdtGF5M8DifwYtIpbfthI4xvSxBGIF54r4PvRNxxr4MjC7ACpoKnjVbQiG0MC4M7Pdesnfc8RiI0dWHAIjCB7IRFBJZARtqx4s0BvAuLKD1Bu91bnAlwqu60033K4zWun5doD9/5aGjN7GeQDZ0A25N4aHewj5mEtidpjW5NOawKNDeku5/21RcPFC+YtwvaZoGRiUuHLBHO1hCeVxg0Bw8GEsO3F63TGOgVS5K6UHqe1viNGQ9XUNgtCdfKColhk6zdUs0hu0Y3n5bNg8xkGft2I4ayhAqhLKUnao2v+FRIdkvEKlIWkIh9wnZvrhsbyO4xEK49Q2s0Ie9yR0KRBFCPFYa86Rd7fM54Bw92Ddmt3hqU25xMrMEatGusuZaOWrsqCBkf+Aa4+Umvz7WzCvsak6MtuluTNXQ3zHut2RrIm6ypVsHJ6LmpiziOWYMgjtdz4vDSrEFN/eXT3ywrxBhlH7BC5IAVolrDeJuswdqsQTuvNM4LjfUOnTE7ojM6eLM31fYD2NHkF+9+EhP0Z0bHF+e8qpozqip46cUbrlMmtOJVcOI1wdHoZPJyXBXS4lG2mQhyfOJZa02KCA/LlI7d8WHriI7dd2wAY28N4web3/kVn4spQdv85muugvi0tSJ3fFqwhu6G/K0J/savUXm4FMwMu9dT5F91GMVwJU7WIN7L5tSyNXznx2oabAdjNdypOnHuOrZTVXCnqnUU7lrRaZSm7IFZlOZMKOEPcK+jVWsQa+WHueurnL4lmP6EoQKcWNy2I6usrVmD9oHK8MDA/YBtqpOBO8sacgHWqfwNzQ9w+Z5wIFYcckli7prPg9ML43ea/eEsIjxVgA0fan4HrIeZGhzeqwSxQ0KVSKdzopec6zAWL+KP0MPLR/DhzYPribziY809lPmzBx24fF48uHogkOWoAqKAZuzRpEvC2hiy/4h+/B7ZZBHZxwSd+WGmepLZiGWkweaqP7JFdHfLyvKH4Gs8vzSyb1nEYuvPPmarrTm2bZD+EDSN77BWttmOcU7t/DP27D1LY8g2c8g+cBZJ42vgDUKB6fDJWaRAxsPugPmwd4KlkVlbYoHGVBxrSxIZ5qeYmnfLp5j6GWZhe9f4aJ0zh+tuyph3gpiRAdCHeRcvH2BhWBGW9dhypeb1jpYrPaxMnNzyOVjH63FbzbtgDOBdlEfvojFk16g2mo8bFW28nFuORZuGc0uf5NzSO8HW+NDHAZ9gV1HK/atUP4K9wbtsDeNtFlO8K9awXXN7RnVxlT5f2Koan5/xmlPX3vWM7dYJS+ERpz9EeDzu5xX77rl71+xhu91gwvfczfF94YPlbqJm9tpg7ql94ZE13WO0yNieXpUv2Dtz4G60ueJ9z90cH6p9s+p9IkRG/4nc++Plknkf7OG7y8fNR3vYPpZXqKoNfGUFc0zHmYWOxJgmWB/2vudujkyE36F8L7S4WJGg9H4VN7YbJ+B9z9scD5KObx6P2OH7XZORs5026Ys5jOfvsqocvbz4Yl7syWHWgxifKvqefDWH7WOOaY2kww3TLsu1ivHnLRwV9ypcrHKxwntB3viQuIAjhy22LbnwsSjomNtx1EHHHFV4sPK1hsMYmo9ljKh8prorP8OYkUSO/Pggj/z4ICgaHQy/UzScsSFFS59ZRp5fZeeLrL7Csg7X4W6rD94gtI/ZHjWhsIOo/gi14MT36Jh7t+BXLAiGxrdcvx0C/OQr1k71hdXqOWCryikciDehgfl8LN4UT8znbwH2UnyI1sBdoz5Oi49a6ZEdU/Jo7g/JGr7b3K7zQdAzPht2bDYMo58Q7xYel21cGp5cBsHORidDiYKDJ0OPekohnu85V40kuKcsOTA3jD1lqbHmAb28odpDd/rb9sCnDZ0jJ6k5B9uXCAdOhkPPzm5DIJkSi4MJdJblfD/9nRfObecR+dgzNT/K35WBAhTZNeboLfIgfXTmgF3jZpg2M7ggv2hDM0MspOgWgNibg/ghujbP1iLsuZ9kPbE9d4977j72ZM2Tkc/1xCV60EmufDptyp4B79zEUn/J48xsSuM4ieQQe8rm+R6ghzPu1DFd/P1dw/5RIz72tM1z5TwzLRIX3v2SVYrHvnDTYmSQuvn4G+dQNfeQRuRjNgftvGyuaRxUa5cnESPUhE6cDLHnap7q55fSqznpMVEWdv+yVXPwLhoG2zl766PgbDwqspEbCeTAZfjaCCJLtSEd1nDdJd3UJ8HZhucX8XIdtGPLJkC7bLsnwda4xKvLvAjHFzjIbEdD+iToGt+eQAdZIg4y/xXjS8v2x9QTtZu/Qci7cjbM5N245FjzmthuTXnQHW0ekmF2tBmPVfmUrCG82ak1n7I1hPfI7vapZ2uB65AOrjYzoczfPxhebDpXXWblZRcT304qL/OMJLSMpJ6rhaHxHIPRYepe7+9297aMpJ6jBeo6v1ieQMAhCz/pa9FVdWMDdB0GxY7Rbcwv4hqimw9z6O72Tcs9YwtcgfRsbYIMhlfU3umFKtU24GChKqR7FqqOxByRB/Zk2VtDd41Mpni9XCXTSmQsLzaSAtFTtkB0yOv4R5pG2PjHf18fpueX2xy/9VkwtpGbNyh2WeOxROPdSW3IyRy8u9kbsuBrPE4rwZSCCTruPDDnCULvv4esp1ysITzZn80M3Ar1TAcIJRqlb2bVMRWfBX8byr54bZgEdt9v0tl75T0LAkdF34v0gDsrID10Yf7TFp1V/pFp+4jcHB66R4oqMacc1hBeFEqkkXnohw5yy8YfuoAlwjkoEaUncTdLqtx9h6NWpAyXvKBE7FeGS0/lItUoL/50dJrhRuZ5v/b01StNI/E6B3UJ5pBdpfJobDvctQOpvSOdp5LonHSAxF6iOZAfW39XvOHB+rtaYf/2+6L8ZhTRSs/lIpfY0egb2fLV9+A+MJnfw6tTegoXqb/XeeJ5IOcaF111XTM4NnTv2ZdiD+XHsok0XzjdWH6YS8TG8hnHb6Xaw3bDz1tP4+Io3UUz5HRuKl5r20Ws2hO4yEX2xFLpichzevDupUMMS17f6qxhvF+NqN4axnfVhxlu7AfZJBC/54b0+KK1Ew0C7alV0Dhuq06sBAO88W5wH6DHU3kZKkf1SeY/c1Q7orBXwduown5JlAWFHcdE4f43u30mSU3W8F0lnSkQ5tKZVjgrBGESSl8FhSPziys5JsF7i8jx0260qSZy/Ejb5ceCLQ+vtF21TIHzewGROAsSx+3r36pt/3nDFvj85Ohrto07cHkM3x3jTo4tAAuo9vTttjskXu+BDh60ppZT3Uw54XxMNtM0vQPdLFaZWnRiTi0ZY4vcJXhS4tus4btsf1tTHDi9kMlFwwlcxuCiBrlFredviUu/GSDmB8tPB8jPXL34ZEGeFwjlVZDJ4tB61pZowMPlyCAyCjjIVO8PnX7ad23+s6b9pjl284qY15u3hvBO9xRaT9kSz0x3LH4Aiu+qTPpFsb13zS0wtvdkdBHJ2oU/yNON9sDdKnG6JXsAb7PJ3XrWloig/jG2gKaBRUNNDIwXdQ0YSz99bhDi/senmHSBkq2Yw3inxbdWzcG7y1CzCdY2uggv2zJ+Ef6ctq3uG2acJDVpYE1DP2plC0MBF4auurwxYNcM28wcsgmHIG18TpHhSCbL3IppkR65S98QDkHYeAIMDtmoFTUumQPdg+3UppvKKRmHs6BCww7RDBWOYA7b7bxQ4RC0ja5bXJKSMbQTu4awykminWVORcCozHzfNipYP8bMfI0832QR2W1cqOHIFvHdLQ41HIK18X2Wg8GME+PvJcnpfZZ5yUwTqDHQzHyAxIexaHYhxIQRA7TVGrSbxG+Foydst2CNLkkDc5IjqQ3hdEHoKbvcMy3vwPskoR0bn6hFBzNgwu1O+Qe2fL4W3wIuaGLAzgpb2fxREE0GweAoyGULQjK14VWQUD2x7HloxpwzBu0OnrLgvDFUN1uLD64napnvAyU4A0+JmjtXHp/hGrEbghpcNAftdh2u64la5oO1wAKSIXGgvlbcBVBVoVA86DD6O5IOP75+ovYW/KBla9A+eANe4cEZ3YAHPwOHFmAFTHtClvmc5yA3QEhKXJdw+KpJu+XLgsFVg/BuFpIRnOBnfDelkVNBmEk/YUN/1pKr6pOmLQ8nUQOHZgEo3K7eGQF5XrhRHdQehMUdEIR6EhbHgvhcgD2K4AVTG8WZafYo3DERjvyAaP7vIKcoeG8P390MOcEL3kYHbO8gY44DOWD+2Wj4yYmz5woE79T4Id01XZqPBrHd7Bxe8MkgyIu2tTWTeNqqQZkYO0gOLBOX49ASZUHi+EZbZBttaNI5F9Ce8ZDP1R1eGXQeh9nSUMzhudsSUPCCxfHz2u7D4/SJWdq58h8MgzOMnsbdog8lV8ZDFtillSX7Kg994h6Q1vVft29/gEzgw6/b7eCKGXTXPGINzC85IhRCT+PKaFeQBKqTXcFjBcQPCpTz2GJKxtg37UhIRoIonRC8OXh3cJaFnreV0VCIuKZxKOTX3CPd6IxFCNEevrvNjENP3QrNiTsqDDbZpqvzXyYB290lDiFbQ3irT1tP4gpP4EvwaaM1olvVnk+YnR8ba6DlU2P9yLiwXStSGKo9YHdxk4RmD9vN8p/CLY3+A2M+datkfoxlt5yeCFleFqYiIwf+yAKrKmN7ZAxkV8UduKwSnTVs98ikD9FbA/aefndqxhY5WSswLQ5++G4PMi2uOCyOgq/RFUznmBsdxMgSltCJ3ZrdKCgbnwR5oqmTZaDve102CXpRdo6l+20hJoMAT/YOU8O2RN9xkrGG3o2KRcVYQ19krGGIgrXx81eNSWZo2vne9zB9Ana7UlGsIbwLvYjVGrKrUr01BYLHejdoJ4ax3o7wC/J8BYfjuae42sZuwM5YqpePLNZNgx6MeQm3NE4z0D5kdFAl/g8OnB+47jrcxMqOHTgnq4PJmQN4em6hebaDsYV+ZBHprDghgUs9gbvdsBCl12MaMpRed5GJvizY2+rp+JCCOYj3CIFK0Rywu3RkqWdtlQ7gCWujGRmx3S89/ACHVkLqKVvl42IPV6Ej+ao5n1/OKEynDaRiDtx98gZST9gqX8+MbD0TnKgdtvPC5Dy4Gg2HY6vG9dvvfx45kJo5YJ8g4wz2X1UyDgcYwJXA3pJcPoClE8zLdW24n4BSerzf1rvSUKZhZwNHWYQhxYmpLJAhRcQhRXbWkH2I+85T3491CSXzrURz9AdOhbO3hu4WxxpDFqRstONKjtwhd0hLPNK7GRpyNAfxditWWfA0HtIbyIQYczKc/146f2S8tuZujfJuI3XtSTox+sbFgm2ZL4BytojyHiJOFjyNHhY8Crn7fE037LHNa7Td7SpxtYfxPnmyWXA2vpaZQIZk5sh2ztle/YC1gyA+B1I+4ssUCDs2+NTd1tg+YB5uZirO2DjX7hZ0lsaSaNpgTuHyHXGyfL5WUCwrzhq20/5IlftpYJB0CO7YJNnY5VzXCLjeGrirojJURzJpiwb2JzeawYcD7U8ug/2p9HzudstRJjpAESY7r2s2r1aZzDT6pEY5GzrMEtEiCGUu0RzEa4iGcmyhmFqcDC3gDWObVpI5gLVleGpiUQc3rjAZKpXhJ45adJBmlJ7CNb5RnN4CLrVBk1a/4Age1N55pzreEDtxqif2dANaoEqxh+9jw0yVzM6nmQHMeycDTU/se41U32oP4DXBZprvm4olj1oI1qh5HGSUnsc1PjF2cBie9WnhrEv7kVnczaRjBOTHxhmaXF8+z4AA2snBZu2pW6Pb2s69OYydJexilTa50fXnUL1FhFclb2mgprMMSZRHKLNgVAfFtwr+xjeMC7ProES5DOTdBhlVUDg6krvY+hSnr9r3TcSrh55mSXIVHI7mz17EYLwZgmLwmpXNXbYsajYH7W6DoipYHB8UVejOePTLue33uQn2lrXKKqjcaN3tgIPbxBjRndZ9+UueKReq9OQxxkSQ8Ci6V0Hm+MZQhRxP9pJT+0K6PGf/oxDDiehxO+FV1xhuCuXlP187QNoZe01nPHFo90HJZ6ZR42QuyLX5sT3N4da8x6355npkudrj2bcOGrXypXk7c9kwtFWrTtusxdSwSMQG79ebQ3mXZq0Fc9CuMbKr5svcye5SlqP7Ub9Wa8R+7f1PlSjHHuWhmqZJqz6WWCynbe3zrnYHA40TV3sm/UMh7zeZQ3Y3stFyDzHfdSlQIpjkE0+14MWeE3i6mvPQg7fbwHEyfruuEmDfcJDRijFg92t8a48w38rQnYnO6Qzh1/QN88cBIK1v3Dl4EtaXUG5vrceWaJQf2OJtFlzcDF8stxsOhIk3uvYB9OhUlvSl0TMB7jS8b7XdZOp86aACF3CbnHQPbI8T7wvFQ9A3qqO9v2EHw3ryhssnT/gpOrBdbhwPwdq4fBbIPI5sY6wCdxejVDyCQXR3rL7RIM7PuDX0JceO4yH4G9d/mTRpzHRt9lRWPLI1iKczuR44JYLtw0ksV2BFOGAORDyKNWzvMavOUTf+kcOt+vHKlmdJnqg8xKOnb47OLY76FlCcxOHQsaLxXWb1mxZ3itfKOzlWfMO5AsjNGsj3POEZ1aypso3ycF2rsWyjQOjFDUsr0G61iBFdT98cH14oL+C4RWbrzSb00XmDIK9pgFfKaeNzkEROy3D6Irqez7nhIAMCZEgnEe5Xg3cNLoiuJ3BupLI7BBZU9jT1fJdfv1DAO9gpijDGONkpCmxx1pEK0XM4R1T2xO4dJ3bvOJ3mgj+3BkMzMb2QEeQEedylqSbI0WVrGO/TpRVr0G7WpQkWx/OlIks1QXzzcTe+e6+9RCf4Gw89KmQOh9+3Rd3ZtMiu6Ru4/KDW17/9vmh78XR09IK80YM4yriYiZNZL+l579J8oeedlHy9YG08h8fBhizrdNO55eyHCqWN3psDds2b1dTbl9yTj16wtFFGDF7JQojj/WHV86UWSIQqqpq3YC6Clh6GCaqRnSiMBNmept2qr0xURmShS/iKszczAbWDJgFWjsc9Qk0eRvG1eTmK98kcuPPigmoSz9UF77z8iI0VhhwKNmC1QAPme2rmiUD2kTqJDRhMiINb0d6qsZ2qCoF3YDXJouCH0oJPLP0XIvui76mZp6LYZXEFvmhkcWUJNZt/thrWMHi2CO341RYWrOwdwbZaw3aaNih62gFtwKD12aa2WUNzTYayZk6piR0YByiz9HrUGEPPxjwNd9BOIdacCdmm9QrOHLaPpc5qPmI8ddZl6YI8CZ49KvogXaxghAzeHL5POBYyaHFfcvM1hp6Xea7hujcHgRlsejaxqv3giutUtzB4wwF63BMnTiOHhFyAS0IxRHMA76YthGQO4q3GlEHwND6H8CzOAcz+aYV2s80uUAzFGLR7pW7FILganfG4g10XIitAU7tWP4BROggORyc+l20g2Mck20DueHkTYXxQGQ9z8O7WBkfB5PgEqLKzhMA0LsdIXhczYPv8dozeGrAPtWbznZm+LatsakkW2aKgbqMVCnJ+jCQ4fPE4WFNxB/Pg5KDnHY6EL7k5CK6H+9AxRnPgPnT1USNH8pshpNQOBEmmmnkim8Wer90USmkQwXE7GETcJ0GHT/DkGb+oGWNP18Iomej/Z+/rklzpcVxX5IjUv/Q8a5n9b+GW7errSgJK00rZ5uh0xDx9EaceMNkyAQIgocM4Lmxxyrc7p0hd9UhQW2mC8E+PucWM4R/vIfwTiz2QpzVJaiQ03kMi3bv9DIVH966r4N6Ne/4WyHborgBHhQIc/ae1h5FnuMMr1KSikTVmIz9wzRqyy/ii02YN2kXIRNqztNDbBzkFsGGgIPldm3cOrHrz3vfslkZkMo+nQWLy1pBd6bZNTMEavK88tkOvgle9CnXrx//oq0ByamlP1QLtKrtq6Hh+EEaxkI8kho+3uSi+Yt7m4oJUIbt1LiWjCBkdiJApWUN5NQ0yCd5Ge+Gudkhs5MTCnFBe1sqWLZuOSZA1flghgtGUB6kOPWazL+seL9Y6MZSieXo5ovChwlcqGFmv+Q1758kyIv1dtrON2mw4h8oCVMGpvmc3sOCUY7xBUDLemOVY6wVojmXO/Y+FxoQsWFlP0XWYpnxXT8ApxquqeuMjbgPZsc96a2ayo0fZMe/J2WNpORCVCDPe2NXmg+yNATzs41XpuPzTTfDp9m28iQHr2Ke7p2eRirnKq2FuV+Y/OnnNYhDDBCKq+UMlJoa0AX/Ie5YWuSiWwInDjlu5eiyYz46kwAes6UPvjA3Ogb5wEPdh+gK6nHIyh632bRhpDrl5FFVvQ+l7Szf2uxbIOi3vaVnsaTe6k2GWPHoaqKl9TLbNd91jRVM2H3OxhvDw16s6ntL5fF0G827/+23s5rNraN7Ne74WqTn6+tsGbwP+tpVnNbxvf3iNxSxzswfuOXO06gPWVhv37dFuI6JjhqGhbPbwXatjqAjWxkXHTLylN4Hn9BmriW+vhql1nl792OCYySkQd17x1oCdpDl2kFVpjs51gS0EVwZrsAbrSk7zIkgar8RqF4fVTXC4NQ2lJU44oeFB0AwLvRfh95aK7lWg1VikZ6gkg/CuJpMVwdd4/ZiD0zSsaWjO6Sr1wwuoanSGzP3mPgCbiF2RN0bCJpBLlGIN2oX2E6VaA/ecBUc54WpG3K79hjnyXCAfruBpNIXiNtj9sBhgHOp6nOcSsRq1rIKr8f1auX+texUH6jRd2+YshofvrWnmss69Nf/CxUvPZJyMH3Dd07SHw1TGURDcGfV5M6cyWzStemvAzlr9KHDmqx/t4qcRiBNqZDVYQ3g8pbafx7j7ppNSc6VOqoGte5KWeG2eA7mcHzz4sKI7YoTuIOoT7Cj7ub8aSV1LisCA656iJVpHRrpE+FnseigwvMMmYjqxWvfULJFFz83BgFeFiQ9vYM++7KmOWswBu0oyolZz0K5VkFX33CxxY3mCpDVLAx8fOfh80JpPCLqg9eB00PY0LBGB/Hb0WnaZs6PX9bNPrGlzbnPWcD25eBiv2b7+T1u7eMgJHfoZHfpN0DCujAd2xAuyD6Z6sFQwU3XGF60+kwIuHwJ8v8EYwud+xcZ/xNS/YL//Xo61yHCbIGRcucV4CR0R/lthjPgma/iutPNt2Rq640YFzb6s41RIgOyBWYHZlxBYQcponOe6dEBXOXYPjgnib9w62PlhqxZhXmXx0JpFdMc36uML9RD1+/Qc2YngDcwKtzf+L7z8LFJgqWo8gfJ6qnrt4uK0OWPojv+yjf+wwdrh4HctO/K7Bl0AaduztUeycrfSafcBYb/SAR/TtFbdVerx0rZnapmm0TZ/8RXQxTRa/vvZvt86OiQzdPY7Beq2D/Y7gfRtuw2uhadtz9Uyj0oVEl8nLoXXQ5Rvu/Rn6CJ72pI1jFewPqctW4P1XD+IQinn/SBThPK07elZ5oudBC1tbO+QwsvDwdRd5Phhv/jCXb+6kbt+PsFhv7TtKVnmK53ACl6xyWZOYfkqkbO0NXPYzil31QwKtNvVy9LRfrdrw9JRn2TpaHJ7UpbpqmeLbLwldUHPHDZveWxta47JOYsID1saVbJjx9MYGrgW+r7G4olifkHDc3KCofHGq3ZxOCsgQ7tu6GeYcc+NC5ovmM8LyCN6oclUyQ8cxFKTEwyNS+Y/b7Cmqa0dnrh/77pyrIafxnhSlK+w69rFMoL8881LkKM1kMdVR9W3y4UxLAU4kB0dE8YKeR6SNWznsGDVr1wnvR4kzgfu8kKczwVRFoSN3z5JF4crd3uVNwq2pvPiDNI1J+gaj5ck0tHEwHzWBfCRkuLxjmL8WA9CUpF8rbcWIolwNYjwHCeDRoXkVobr/9aVboaccV0ZNrmvTG5P4B4VF7JIF18FLNKdUQ6/jrjrN2PQzslWa9gFz1bD2ZNuurpVPHuSNnn2JHlnDOGTNfGKeaHzBHsoGzt4ggMrIiTrYL+nbYVHexqL9iBt80PZnrcd77Gj7/hgEeVV2jST3xO3wvcUFVouaJ1b2Y4eidnYguigEX87bpwCBSIHbhzHdsO4AvJ73lZ6TXmyApZB690k2WyZo3/JZ4PwLpX2SX5P4wptdLuaG/BxQHPDyO2/f2ID7/dUrhB9/dZ3gcYn5tp7fU47+xk/+Y3rnD3QCjuDCoRv5kB9xfM05jTlko4HL+TB0+CIFxJ7m9LjDKgZeIczrJqxoRNi/R0FdCnWHHTWkSBoG18HuYtDSxl2MEy5wrxQS2kKgrXRkyhbZMYc3GbGQ5/p9MylZcNTEDyN6+eF1eWB4Skf3kN6p5xjtfo1hWgM3mnRFM03zNXeKjDuRlOyB4ibB4QFXev6zxVrtjrl2V3jXcjWYD3pbBi+lNaK9lJaumkHQmD44WcS2mIN2rVa8lLYM7NHaZ4sb8I6EZjEWnmd/s7OYVvTF0Kzhu+pXIpmb9nxlYG024+m5MpufOEtlPS4OXVHl0dTHPPtYTvWNw8lDdWQ0RUbpFm7vqfkVPvh6KxhPKyea3yRHfW8vZBldZXYni5Q5ZTinqdVvpjwbDGB2mMdCFb9A3HsFPekrVIN3XkWGH6bwLvSLfEUoz2AB7/iocInFTXuSTqB5bLRHxn3xK3SkIVzsKWI93bufTZoxhAxyQalwJfboIokxv1Olw2ZcYhAjeOew1Wi9t7MZrLtnJrNtinXWJexp8diDts5FhLNuphaSOSI1nseWCkGdkKmKEgcl9MrkAzqcBgx9k7/es3cak9REDgupqMqSVOufvtklenQSjjyAxPoHmndXKYLbA0U8ABNepRvmwH33CJIo+rwPZB6CURXbLi+TIK2cTUdj7cz4WHsxMRk6UE1LHDtoUCk7UB7iEw4y/joJm8P4CXk9CQYG/X9XyueNvkokMX7CC1evL8wpT1jezT0yrocDFag3/SbuQrjeauU7OF87udtpqes+wPHPGUJM9tpz9gad00H9v7Casg/SxR/1ppuhVekYhDiWdqOpkaDajuwlO+rOxG1hx94AOY9fWtdg7rC5jsYjl+bZTSL+A5+xyNprEIfiwA5lp4UfN3HwVyxQY7l0bt3x5krwQ5S3ImolOFYCP6QhmbHCJH3dK71FGDMbhNsXzdCzA66KX7hPnWMMeU9kWvU6HvNGWti8Z/3UY+FizlRdhu2O/SZMm13YAAHcwDPmdNUeSH69kIQtp8hzBiEvd4FkhhHcxivcZExZcHi6KEK50kfPe434zblV228+EUTBOgUvzgczvrNL4kFCAsBN5sDdzj3qnkMVL9pB5lX+ptGRt5czOG63Mo4C9pGS4t+MPYYECLGh2et05MPDA8B24kIVUhfHdy5SywMUHF/kZtBdGdpD5oRjYsPUGvWFx82rDVzGWrNHpUZd5y7pVCK2tk6ZTf/yvA7cofp9sv//BWuWz/1upFn+CZpSHCdNXCXaogq3hq8431m462+922E8rygDwTaDV19RXA2HrworCsON/PTNLO1Am8lWsR4li6pGdRUS4zeM1GI/BAJyjv+dvtjBGXdwdwdMf64fV1l/O2cswEHxEH5S2BrZNwOlbwHlm+H8t3usAc2w+eb3cvP70Rkx4F12DzQBzaTd6Hg6FvKHlh689050geFWq8rzxbHb11tDjWcdcrjrv8ZtUneHhdw9o0JZ99qEeiJIxovJlGPaBxcQBZgbRZhHX4cNOMCfxz0L0MlhKIhn3jEB+/I8g3bRnoziDWq+Cm6zuC8gN4dxSPcOh8uONZTb2bIpEEDD4pVt8eZtkJdMy14XJuID8+at6aH5c33fVdvEd9VLOs1WER31juh+JT5M6F9Ixp5ixMevqlxjzJNtVxRxrcYUH69Y+eNbSVWkps12QJ4jkVVM//qEgJ9Y5Ru91azLXxXSV5UQd96t27k+Mttv/W7z69hu1kV7I0fDcFYIbU8xFk4LxHBqM0itMOOVJXo0LGkuviKJ5WazoJDhB9hAEsIL7R6a4LC8UPxrLaEiBCfTG3CZl7TWtIr72wvrOYTOxJ/IYXqzRuDdr3ftiYoHF0NXd0P0HtGKFx6/VT8TP3Mlrjeojlk1woNtWQO4PGtvMqow99evAhwcGy3kosAGQ0PbU/ZHodhBbWQLl9KLbY2Rf99ZWYYclDHzkoThMnQxTcGJkw6FCZbsQfwcsbJVu2BvFL/d9uzN0cb+67N9ZjDIgH6w7DQZ9PdU1HuJwMIymmTKOeHkcQKyuP7ofH1kH43xFact3MOEldnDddXfuGerN74Qr7xhXyDylQOLcAKkO4Jm+MB2EYaNfDBzUNW6nVvYOUtGAR31jJoeBfUtKug4nAw2xyAvGdtjhgfInsU2DGWgfjrzHSbBtJOug3P4x0E3LZMSpQDlijnLVnDdimbb94EaetFt/FGKZHLkqWSatW9Xerluw39qpbqeJPK5djQAGRB3HjHZGEXhcBLfXzj8f1nCDU/cJ0zhM4X/R3jUEmJfYIO+7wJvkYXmqR9luq94fAyy4c/YI1mRr9f7deb2BsMaYu8NWsIj0tmCkw7iplaLvv99+LlJbPZQ1q448r7JSvrrp/V/LJ4mVx2gq7RZdD1QgtCDB1RrrpDMecdRpIhoewqJ6hUhtZD15WEb2+BlrPsBHXjavrGhgdkw277ryBJBMnsgj2QF7CrZ7dnbZ4IvffD5pDhRmrsn1Hjt7tINHv4noskthdcJI0pDxcilblkEN855E11DJayNy938X3+FnAX75zcxWeXDaK80tYtuz1581zy9YAwNayXTwuUlotgsqsWoZ2VBRiODEV1YqiSOY1sg9yewXmqAju888YZ3BTXwyJ+6vx4cM1Au4qhJHtnDttZZj7tvQDCL6Ccr+vmi1jOF7Is58t+T+I8jW1ez51jETigPNajfELgGSJuHXkSP+G+OnkVfonIQ77hYA/dtwiUfHmsEig5xAAvQBvtQTvM3zSyeo+/hfRKCmBLbDpDk3r2gsB1V0PQTUKe3/z3shusLT59AFLRQ6DbHI9+utkctCt1b2UvOBsvnI2svAhqdf57/eYPrtUcrssQiWYO2qVknCCIGg++Yh0fu/M4hO9JnWzkye1Y9xDf3HVGNtaa4bE1IwdnD981PKfB20P23BZzfImp3mDe/7lYAuGgEAQ9ozv46yAG11fIIObCkcTwkUdBgWznUdC/CDRFTPwNQfAznsT0F6+4vZ2Od+/viAMN7S5V3hHX9UV65h0hwnkQ1KwXYyMlZgDtcUTl/c0CKubL59vopVJ+MOLezWey/gm08pCtQbvMMZscijVsz6UnxkcwFyE93H9xq2NeXowP57CnZ4+RdzcpsH3aBviGeKQq/FNryrCnZoGsKW/HdEmTNw4JrUz5JVvO5hT3/CzQXs6NGdEJyO4LDHjMJdKpxsBugf7MwF6HhI9DdAYBXijZmuOep4VeVAWfCWLU++YzMXTzitciSzbcGyF+//nzjzjYw3gJZTfuyVqgtZxbvXiMqKAZPb/eRD9zdvCK9U5neCCFWoMrnrinaIHrueXiYNbFzM+Um5izzgMpPlp+HUh+s93bQOT3zCOZiHuiFrgs5i4eZTH8PdsOd2gfzU5YmsmKNYjVb+3Qgr0mPo050BlSd7/+Q3JxWqioM8RqDdvVcmtR0DZ+pE03K7Tt9VFhMp3Ynv+o6eTHwR+0JAgav2flLz5IOFFccMcp1jewM+vrsyTYGT+3FOEMPFv/Ond4r+YzOx4NNeM7HjhP3t/yVHKfvDZ5nzwnbw7cc8qCxm7D34IALQ0HygIjZXjEKqc9KXsoObIuFuHFS3czfslOGRcU2HZ8C6jaHPgW6KnRgIw3RWPgLnaCLadkDOA5jZuq+gvuMJc0on/+PSKN+EEGEN4ztUhjPldtAZbsTFuoL0P8D+hiac/UIo1KXNUGhBivNaaB3dq/8BlXcxifOwqk+Hz5USDyK8e5MDHhEKKW9kQtciN/YUZ+cmr0rwnnv6ufG8B5MwjwnCdYtQLqnGxMMozdfYarqhg9Z2cQ55feiJG7CcFrHon+V/z778UonOGoVc57Ghd5amK7g/ls+VP+PsD/eO98zsEcsgsmLbOgcrwGLsMGPpGbxP5YkPz03TsNyjzs3oAzd8PujvA58i0ncyiv4pbOgsiRncXtqLbDshE8qh2/evvZeH93LhaRHt7Iq1LZXG3HWtkDRx9jyw6PBOVcLcK70KQmGB0/IOYvDlp7ya5ooDJy5oUrBa6dA1cC1/5xq8ps/x6vYuaymcN13P007vuvL9j+syMPLhzVzkVQN77drBAEikyjnIPsJDuJ5m4YtZM4J0/mdv0kOePN3LDJo7m5CALH/f8OTGYs9u79kQ789p4RzQ8arxmRmHY7RhJr2mP+9BKMwbrIrfJcojFgXxElh0p5ebU/kcn6Kzf8ISOZ1rInaQ9viYxUgOBA3E9h1oXRFZlEyRaRXifTVopFfM9VN4xbIO5KmtICsZES7wo3G3PZk7XE18ee1MDh0BuPBZ13buiHbq3wzUWSymR3cdEqKpNpA2Wy7Pla4qvNxK7CY8XAUIvsusUudc/ZEl8KJbYUwmPa9ZnW8JHDmApwO++D/nFg7RiOBFeqswjvcA/ciRo4vB920AIX2NcbCLmo3iK+y/V41z2HSzR/5baLxypk3MBt8fVfuTcuh4Z3Q9rNUCPfckJVskZ7GC8RHqzJHrArnKiogrvxDGEg18rxfE1uR/rDp083qjgyVSW9FCW7xxsTapIVJMlarEG8xKKiVmuwLmg3q4K1dbeYCDJsMY9NO2/vOFXdteK/Zq6AH6r/g5YC8ZCgI7VtxpCdM+8Oj7vqYVd3dLQJzsbXmJFl4zGPtZN01JziQ7kWntNU5Vo4wgAvYCv4Wm+RSfRIWGSWo4f334sRtmAM2jX6TZugZb10pmQP7DVIh+mgd6jnQwqO5wpOBgWnbv39D5vFAsM3WcN3BW7W9tzsEbEQ/S63Lc+Tfpehs4wrX01pxRy4q3gaWjUH7Ryj07DPKcijHv3anOiIZu7g693zskwXltfiY3CgY83pJAf6nDDmcBYT5PJ+FrMh9fVJUt8b5fsLMV9YRtZ0igxiSmp7ocs/Zdvzs9xt2YOJAfXcge6yqZOuRrHpjLpuAzdDf9xN7CS5C2BnKJu3Bu4kaUwj4XSksS1qpbEWMgo4KQPIe6qWeZ0h654nRumU5igMkxLxmlmNvsJgG+m/whltI95L20jZ9swtE5X3thsmHWa4Gx7zPk3TccyuKMqWDKI8XsQ33sOHdf/9Gr66kRo+n6CHr2zZILrnvE+a63bc+5QlwGMiZNkEf+P6ubs4ME6jKbKFGRxjWHJQdW117ljB+HAgOwQyPkQyPQj6xqXzxMQc+FxLflnMWb4OqmyCvJ0ReV362nhmeWxwgrwRQfLGj7FIh5x9346LdN45mo29FXTBBhpEf8XmUYNwm9QgittTuEdwUHRuBScxxs84Hh9f+ognXfH1fspyWtyewRWi79x/3TAriJb/eHiXfPY0ZnkRVNyetBUq6jhMt7J3oQyFst9l9R+nxlperCyKKy7aw3idh2HP1AqVdsj9JRrPHlMdpmpnYVw7+51ndS9EjKwlGeHNFuEd9utpJrKOYa9CB1Tfs1do02wlT0OxCO8yScHi9tSt0JKt7Xfr/sz1FCalrNYjF3v+Voiec+dv+BUjf9vcDAK3XpXZ7e8ZQ3nBLYZ35lAe/rVT3V/pVKI62HL2f+4yjWXirOYFieMSZbx49EHAa+znHBKbtbnQfMJ0caFdW7BNp0OEgzmETxn7NLB2jH0C2ANX3+8fkN5/8v0KIkcvl2+NXC6/FR/u18jf04GtnhcrXnA5rgMH0v2CCZYRkWfdGsniszloV1kP+WIO2mnTr8bgR6dft8EpgO7468hhvCBPARQvqBzdYFypMi6NkSrXfPjb9tGE0PACwwX1AiMWnB58AYj3PO7RoiH28mEDiLGS5Bjhf7eSujxOxN9R5qsM7NZhmk/53rbTsOAe9hyuEsH9rvposm71OBv/2Y3ysOajVXwSU4XxNy/smVztNZSQ08XEwXM4C78/iKGxWPMgRgHzzkEQIwR0R7ktgDsqBGvYnjr6qPhkO0cfBbQHFx+ZHHzbLUlo9wSu8tIMR37gsFzylsExdA5Ag/MHGl9K2JO4ys192OrLL48dHn6c7EOzXqFewp7EVa7uBPh8KdPwU3zsq7SjllDMYTvu99X8pHUMvz+0QO/4Ld6T37Ti8TdtT94qt1AGZt8BdOOhhfId0ULTK87QjEF7SvDdP7kdI3VH8XUedhYcW8BVYvo4SHrHlEo613IteAxYudaMEWy5YvoSnTWM16EQ0VvD9tx7qzX5EnwDHLs6eHM9OXfVoKqoRMHQuJnasbAx0ogpK2L1pzu0+1E1mPmuly+w1gxH6FmM1nCdtWHTfMB8xZakwaG/ZNvQ4HC9QypBTtZAXuOgY4l7dvboMxP5eBnAovn44g/Fhbc4+YYuDHbuWwXIDR6c1G2MRQRkEbHYQ3gtXTfueVqjNRrXY1e4AcIlWxswkJycHAxv4OOepzVen9EYtGAecX6W1XcSr1CwNs4r4GL8IGN73ACxhO65TLHKF9k5ahPk71v/psK92UXoujj0JmcR4XFtV0PZOKXAJEBf242FDA8Nh4e0Z2yNL30aXIOm6LbjfOYbIkJD+/bO2qeBdN7f/NRMpHNPpPO0p2yNBwEqCwLAVmJGevAVcIcq+VSc7WAmY5wNT1WUFG3hukYqM+05WqM7NOfZnhLHMDejcmCFmwklZWuwnnpjFb9gnSc2QlDwYLnuGHUouIhIxRq6c4ZbzZZSY+3vVxwynynBV3AzsqFM10UPORhGNpTfzLKZ3kukZhDmNS4+l0fzqSFsT2pkGmWXa2Sxyrr0g3msZOxL/3klZWF6yYKm0YyKc3cx95m8Ww99DLPXaqZHsiwIGl+pObZSA1zD9tXaPbM9UDnYw3i4Y1YhifUqZudIYllQM95BX+AloK3TW31dy50uiI3rYWoxTHdgtORkD9txu5gC145bTOB60A3JepADyVjmbA/ZZUyOeUfRbs4I+sBKDZc9sM4PqIzTy0bGjSEokR8YQyLRyJ3DJU+u9gAeomhDu2D9MqJ/YYUtIwri3OzhPDiNjTwYSROjupuZ2C6YaOYBFz6P/sI7xnwX/IMoBi5x2z7nasVqWYni9hDzndrPwIt8GD7jMqWzd5W9RPHWkF2uI70EaxAPG8k0pXsdJ1kDKb3vJHOV8OALunBK3CPbWwaTHDYug8duNU6vwlDND9yJc/3PWjNOSShElgZCZEkWEV6xtqFki0gP20Y0L0XHNuLQ2ND3jQRmbLg4VCKKoHR0AX89fAVZd7Z1e/3s8+pbt1Kt4bvMcddSmjVste/CsQ7RUXsdl3kwKjwo+D76Wu5w8uS1Z8UBAOccSrxOoqoKpsY3lxVKW2iq3R2m2t8inA3RCH4eE96B7nnMRJ4BH+AZqN4ctmvsLGswB+x6fpEqyBrPX1c4ZsUckJNKs4YLYzWLIJWA0++KrUzA8YV8vMkcrqv1bdZsDuJ1ehmqIGbEzHC/BoTEF68BDajnH9oEvXTrDjdBo6NuNQfutKjw8OsQ5MXn/vvg8eKzq3DxuTZzKC/x0/YIrt5x5R6HenHYTwi4jh0EOjPyIpXQSLvcY3pf9ypNpikQxQb3ls0ZRHcV41PzBsFdqGK+7Snb42yjzAF6eHKxYt6/rIitbH5qe6LmuJ8hwW0E1qs5ciB3ZvOF5rJHZ2FZoCTroPrCMWwJtMkctOfUMY2Ko2kN6EpjmZQGEA9O2zM019uxOyhrwR17fb2sZWZHlgLSjqCrVnMT+1wdcYe0PTdzdCnp3GXDi4xTronOfma17ebsOYCLCP2nNkd2hSajgaHt6ZmjPbvXXzHA1+B63axBr+3pmSP7nttNXHlvmN7EDXXSMLYYyvXhLbWE8gm2Np4I9OmFSGCMuFkLUS7W6uYswjvnsodSjlSokQdiJLzHkKuq2560Ob4HSmwPBONZ8t+EeOyXT9c81HeKbMTpFKXTqW7BIMrr3U+pm+Bx/Aqbh8JjZnNI29Hs9vbeWA2N6wzFpKe7PxiHShr2EhTs1U3wuJ7gKxdCTPCth9D+uxdG6yY4HT9kFe6j8LMQfJpRzjsrVqEqfeIuanBG9pIVlVT0RtAp61asgTwcJFYNbJ0kMTnj2roZTedYbIVIaXXb87vHZeIdf94IuqRf+pkK/HZ8NY9DB18XX8GX7o6DI/jumZ0netq9v1u0wdH+7rGz8DPPqJiq2qsPTd0QuHNqZDVA0yHNy9Vx/yR8w9WxT3J1XN2e1nkiXEZmPaNntHObA/IKJWbVeYPInooNanYZfDXv8JxrPznoiXiJ2mV1exrneWAFGw3pDPz64HBiSwS/bCcGB9wSHfyuBbY8Dqi7VxetYbuKibq6ZA3adbby1e0pm+d3A39GBpAc2D2VgVKScy/uiJ8kqkzqoXv0IzKTumO/Z8Uctku4/6sTJI3HgQKrlAYKHD6bqjAvlLlmDdtZ9QKaIBvV05sAmQMM4EpkH1rCHdleZsWhAQo96d8u3zREG7wzh+sSFp3qBR/j64hwX1c+UxrrcYriE63SGg33Q/eaqw/msF1ubekFJ+M7H8+8OrBOG3P0/gOt0tUneygPC7qKj7ej56rF3ERjVkRS8IKacUN6unjxuxbJ1t1POVg1R8rVYPyBi2DVF2v4nuwhGi/A8Lc5X9eAkVMB1Sa3IlUbX62hu0oMqPo9RQtkRxlvNhEMt8KL65/J5LNPXQ4R4E5+jeyA+xm2THNA+Ow+4DSE7jKaWNiTtUBXlFuCFBB7FsI32wst+8jCnrgFnq3I7JpoBnIRDkMA/2DFXg3BHLxzaMUwqwhSIutTt+jIPs0BxNEcxOdiLMreQvYBb9DDeZBjYSetSIdDDXvWFshSLd5yLJh2xRzL2K79bfeyubarvpc9KO+GbBHROZRN8/5yzpbgt61rv8n423Z1NkiYi0WYFzqHW8OeuYXu4UvMraANZ2f3H7WhT/qIhz1koEz2P+KIyuQPNABxswbxIi0ONQr2xteX7uIVseKRU41L74ajMwfuCq05NQq+RjaY8XaPosFzgPcomvuwojOyZ+s1xgpsy8E5FVaOEYjiEAVb45s2VBxYeO22PPnoaVzj9rEYrYG7xOonCnbGd2rh4hQmHBeGHoSF27lrFFSNRqiuxjwsyQBjXnsWzP6E61FDIDoSLx7MPlB5A1MXHKoLcU/SHkOZCKLIFBUNogzINwvPt9UassOajQLUjmYjN2r9lie2lmjkvW3WUF2skPd2cfsvwr1omgbhVCfMCeceBM2vGX8QoMK//yR40uCfcB2RnDFoh0ew8TSlx1+x/hRGf8US+Wb3tCzSPNp1TACVhrwKu46yYY/ecGBKc92nl5iK7YXIVGNNZRdi4k/BHLpr+ZtSNAfwEn7ztCdnkefRItxxZtdDw4CzadVKyJqyOWDXastKxRzAp+LVmo1OJ18d4DTVQb56I316kcAruBnvhoysVB5l3OP+pveX6Vl6cJs5XF96cEfS68FzN1OWRt3+Zxu2ik5dFytYdbPgZnytk1nHMZptJp0cH1YVNFJYR1ZAEnGgLLAhLCOHyIKc0dWO84yckUOAr6/MJkeoFF9uJ0KFOuNBioq5mHwh6Hpr6L4lrNp5flVh1e4l7IJGPLeBES8Hawivl6DKgqjxJZruMoK7ht7+WxSLL0WyiPFqKm8WDI7sLW/ZCeJrgtcih5cHtROCA0Cq8d4Ezi1qkj91vrtSuxZP4xuRENliDNlh441GiezlfRqYdfvumxTJN3vx5GkQtI0XamZS04Ljb3xWmvcJi4jKTtrxiPzaapQ+kY02thBDQ272MF4tM1E2exif48maIa1DlGOVrpEDfadktI24K9WWCO/J3GOnKYYIcrNmxgmraWzD7EWK4o0BvEzfSNnzuMRzl5nlLkmgamj+fV/0Uhmuoiqw+IC7ycuK5bBxg3LYEg3CvMRlq9t7bg7aU649xWfbMe15LI/um/YSY8gBrWVlT94S3RdvCYpcWDTbxQmP7xxvP08D6rz9HFFAE5AsxpBcx+xU9mQt8RVmYhEUYjh//W7g27LXiqeW8wg1iyAl0RElnLJnaolH08rFb/DtFhR8P1uuiZ0MmhbjTi54w/OB3TEsMXBdQE9O3cyhOxzz0ShkvZzP7wZOl/WhOSoyIVRBz/jBtV9705MYVS5HT8Mb2IP9yoDqjcE7Lu5qFLKOuBtg9OqLu2Ejo1fFyasGY8iek2004HLVRq4j+t4GT2Rzl1E3r4KQ8WhluHi8KQFJqlnthEuYcmqyB+xK/Xk128N3ltyoqhOhemOSJ+u6imOseLLOFzhZVwVV43vhCDWF1Fs2p6N/2PqkGcg61ic8inJgfWKKDZEcazUH7ax9u2oxQRfu8AH3V+4bfsAu4wcs+BpfDCv7cOKxee/TRxc1brNOKw6UX/SuLpaMukN0oDs0Qdx4namH+6Fs/+7aM/XxHWPakFOS+/5B1umf+KmIrs+I7p65PQypsu4NT/ygtuvqDFVniWKRtqdsmWvmkbj38Aku6WVYZ/saNANaz9eAgsORr4GVi3jyG9eCMYDnNOi9NDtgg97B7JAJIy7IiFs0huuCh4TbnsFlsqVIF+fIfOawzSm/vqZ4m+dUFQGg0xkcC+3bTgPug52DfXDL5jBepkq67alb5k2QmU2+ODSMXbudGVzZ+yJf6jBtIPcOLi5btQipWi8bSr3X1PGaQoFe6ober5cscV7AMbdZhHexyMrtd/Ivyr0dm7xgx3Zs+fUV2ySj6VCr3qYx6cWex8mxnGuCwaFtzhjAi5Q7tc0bA3aFMr22CY5G463OkzI9EmGL26RX99yuQvPN8lWFwLe/p2hkw9YaohstortQyLVtgqfx+5ae3b8GhFt7+VWY3nZu6L3N1pCdRIA1Yg4lwBBK6RNgrxvGBEnjS6DKmkyh6by8Xk72NoiHEXZBjXAsiLAvgHC1hvB6F5Xa1qyBvIyltznB13jZcWL1LmDpTd9NplgNZjfn7GG8UofOzzBnD+Bh9qby5/AJOEGv1gGDY3qDw4R2c4LB8b5uB7oZU9EHXt93KTqqnDaXdK7/WanqtIA+kmsmSGK853GPMLGMXmoKMoydrxo+/AP7oP7hn4b7IJ/kPqi5ZBHlWcvNYb9OVNt1KjnRmDacKbJFnOelifl6SJcmHtsNNbdncqWXv5TlkWx5kbejR3j2qm2ks6Fj0YkQCuq7dEojoSCPRb3NVWvIriLwuGYN2WkO1GFmAZn3PrfwxONQ4TfN7/lboR6HLUDalR6reeZU/0yvrALcTq8sJrMPekccIW9k3+adQYCHm+g1r0OniF7uLrr7+P/8ATn14nLIe4PYLlbr0vyevxUe2nasYBb4W3jdzTd7ElN5+Pgo1oAe9xdENRN0PaHHXlC33jVReSybXRPdHRNVaw9vdJU4hS2K20q87OkcHHx9MgjveIZQgyfPEFbJ0kYBFeSMx10TFJWxeowhPJev7W2+mIN4SMoZ6zZUn8ruzg/0VHbBl1cwNx7SLJeA/ALrHOKklOZSo28zCPBqfr6wGQR5lXKHFgR7653I9bC8wKfYlgYxHIJ1VS1BRI8j8OYBY28N43PVL4ovuFP9UrC1qN/8EllrUUaBMgRr8C5wdLQFQdt4chuPPLOGBxcOa18+7txRkAzu3LlWF00hGSGZQ3c5c1/I5jA+9e4qVmydZ3fSNytYG2/wDuD/Z2LkQA/UiXd2qCGjYyGpWG7a/QmLhQxhjQxh1RqykwScDnFQCjgHNVDZkUU79GK0sCdoj37DHbDIHRLjDqkczQazmxuMbyYeR8jNIPvSWniE8HqVgcF13byeZoKwy/DPkew7uHwx7MEfwupc/JxLmOuVa/05OWwG5XFZYVxV0EsKrNfFYe3In8utd2B5wbS7eBy8sFagzbnY+J6GjI7RSdeQMTiGxWgP3YWe3mQP3eEOZM3I0KlAlgufg2UEayMK2Ijx5zrjHVreL4CHcllrjkuHNVqzK3pHkO00d0v9q7tgz/R6VSS4Fmu4Tjyb3Wka0Z7NHn1j94SskqX6LXrp0XdD+vReP/XzNq+5ZvqiypecEnqSODs8TEylURCz3gaYNGjhoQT3+sXAhf26j7NUZqA9Veqk0Wo6rU64bjgodtoIvpXAK7gZTWVf0z6Qysa0z8ARsJPoDqkKndJCAe1BYaGnqsKGP2VJUDKyyrndc8ZdL9Y1pNeFsMkXlKx9ucEYuHNO0xi6lf3nYooRiFdzjiVBz2iQ9QdgvCJK+lyOl73vjrGOryA89LgcpFgDu5+SkPimbA3Z8WK98V696PW1enUrrFavwBYiCYLG27nRoEAnsm2K0LhKN/efRnkz2M75WTNzuflPm7wZiP+v3l780x1/w/LR2y+TvygsQPJ3oNPpZM3Fk6xJR6vp/IjN0mrynpA1vsYpcHOR+UPbX/Xrf/73v/152RsEd7UAWg4GQR5+YjXDQeeNRW/NgR5GDwcTh3Pec7LGM5QVTlWxcqzrkPwlKdd2P0tO1kCexXw1KGsu33aJL3M5O/yK9/Ss0ZDqtapfUzIUXx/C3ndzwk4tSy7WMF7xpdgTttbLq5I4D7wUwdBZDwXG3Pcs8O27ntnvHcatc7OG7ynT8/iZYVwGH2RNKguzb4juo6rpji5frnm2XEOV7OO7duPbn+KsgTsnFTyzzrSPMqkzzQF+44ogdL005YamR3Li/Rtdm0/USC5CKNXIQQmiCALHE2gOQGUNIs6HEVBnptBUKWu+t8TVxEESjXlFMm4mSrSI7nrjbxEcjpfEBrA+shRKfD0uNXn5rviGP3UL7E9m3Qiy5xr0VJcuOy0XTV/Q7TZy+xY3QEWwNr6eqODVowPvNul1WLFOpOyY2z2bNRyYcPF7rshjktFJVup2baMDRBPQUgn4un0H2znZvof28hMxNQKouWvXyQAmeB8OQoDsgYDn4ZFMswPtKX+0ZjhTrTAP+m9Y0ofcrqrOHrbD+UrVr1onYOnvH6kyZPk7Ej939lcv8O0eaAVZnRxo3Y4zam/J+owYyThXC/IsQtc5kh0eRbjey5TgBoPgrqSV1WgQYPWvGqCr+VVLjg9jBbLtIXRjloFk2zHaXpNAl8Z+3AboXv8joDtg2Jv9u6YpDuG/aw7M0gc/bZ7s20ipUM0CXh4B0m00p8Tbx7PBXlOF1dnIJwltPx/sE/GUXEUJCW2xBu0y85hkaF9HdrEtfJU8ja8o8NIaExtcTIc/aR/dUdiSGh6+SDs4DxMLFR3uEIvYXiAWzZFn4kJ4RZO8zQC8005PDPc+QsFIv/dxQ6uDy2B1aJK+8WVbg/r+SNy+Nc3Qy8bHX8X70Jl+1ZNvYt8vu5ndJHX7PrAzfdSdIULroz5owQjspN2GnskmqVsvyIaiOrubHWcIO3N+58Z/5tS/cez6TyEfsSRwBjBep8elSf7G2x9/B99nqZXwzFX91o94rL6Qnx6W/aX9k4G6buMmyZwNnGdFBDRAU+MknPfohwScKlrcJLfje85w8RGAxjrT7fUfvZkl6IqX4mNtZU1yuu8DuxRr9n8WxWYQPpfPUq2KeEDLN7nH6Ge0csJFRpaLDP9n63bH53GxfKf6RNZWhAVQV274UfuZ6dYy/2dr8YsuT2eFi8P4K3y8A4bqc7aoJ93nHN3OdTAXIZ51cB6MnVBxRVIN/2dvYQXfFTiy/6P9/uJKmwx/6IWDWjhCL3aXwd7e1w1frWaD0XsTfp2qunehqpR2/0cxs4PunLCQBmmeFUqe7JC5UFkrqsBbBZCzPZAX8aT6P3LDL7j87CX6JtmuyIVPTw327Tv+Dxf+hZiv4yIEWthgNhbsntmqowp281odXCP3a3VKJmtk7+Qe2f+hEYbgXYy6PbjEL8Z0U3R9gmE6Yw6/OXGheVdUOLC6Kyp9h1Rh3II9EE4yNwvonvP3KeDl/j7yC8ftZ8xkIjs1/J9Z4RdauiJy291q9sweFYd0yZW/XMna+PJig5M1FF6fPvzbNnaWglO35ORvW5+9xdSYKCl7d/yf37JffLmsHtlZZ/htGzhqN7HncIcsD1d0eg4FrBxSgBOglFSNq4+MRZDYyhyT+hoeav/nVb1j67n0WNnlKiQRI+VwJx6BoZmLx1bk/rKfWSnkgSXszBV7wK5kcfB/XlQ7CJ8SF8bLpvE09oG+QGu3AsFXsDPPdd3IWs2QnblDeN9voVa5yvjGEueDAwt1JfNBxvHg8bHaAXeJw3b+D5R2oF2GNnjByjyPBClbpsOk+pHFNBsvuJnvKrsAMv6ytQ/HruDl1binOy/vTalVP713g44cHADcaA/cUwvh8X1whK6X/jq4OXYXqEjf3hUne/ierCcapmu3RhZdWXrySNd+2J4EV9K1XjkcqjZk5v10D8nQyucHBP7tSmwP0lclI7rOZYRXkjYeqyj3XqJn5VofZxSm2+F+UJKE7fvoDg4OQ6acQv28bgNDb48ZZ4eG3hA8wCx52/dhPtdWNLN9r9tVxNr3rl0mAtwgeVtvK0E8/yibFz8D3dU6Dn9QlhTOAMprHAT4wVYyuN7ix2v2alv9r+L7H2AlazMA7DIfrSRtvIDPwzKY3nOtc0SdiVmrlw6vzNmqBcnTLEA6K/WjyldRD2R1chzrxX6uq2CUzBrgLCkb2V7eTxFj+ym5y/Y6zP9AKf0PypK5fR/lcy5/BbgdVafBsu3A5J9ZFZSXVVA/+Aru9piDxQ6e3BADfPPh3au3W0VM9UD9QNusQbuQ5hA3a+COl3pr+rX4fhjPlB+UegeypIiyX+sHWcHRAlmzpZvMgPZzkBnyy1Lk224KcmB1NwX7x65oLMVDqcAPrN4arCu9BoKiBZpHuR5qUxxPiAMj71TH4/jPWMErrn3HYyCazQ908DsWozlwV/p0kzl0Vzq79AOw4GmB7y0z21tmCbA/3ltOHhWemKFfupKLFxwH9YVYzOG5Qt3FD7CSivEdcGLdWVDYMrJgn/QSDPmcNO6b/rlsNtmigyFKQkYWaOkKsLzAllgjzkA72cTqQs2P2OeseUmyMbLXuXtD4EAjsS9srxsY1h5vk6RkBuCdozWOS41anfH3n4sFMLqik+RnBjA+acLR/LhxE871P6tNOM0THnH9CxJhSdL4uTDsE2HHlvyQw3TeZmLErceNIjcdXOcTqZE8FxFwlnzNBM6nnmNVhUDnPXbYMnLwJm/UME2mtSR5G88BOpYDJMfvDm9ivtctPfIo809Z+yEXYjmNyNySZG7fh3hY5NX05HRE3gLf74HIy0qI2NcrSRxfq0V2uhGzFIeT8GRkRyicLsUauimKRLtNSflQkhTu67Au04qTJHn7OrQrekyzIHKPNZvQIEghJFLkLc5Qd+bIkdqUKw25ahXJgAOaczCgZWcP5NVqeX9Q9vZQHvdDqiZgboj06YXLjTEimQsRuFwWXC7ybWa7Q7l/jaHnf6Q49p+47PqDc7SH8/hmc3yxid/wwWKzkm/YJfIRCwoXu5lXWMmTzOs0pnwy1Kb4fnmoDXfH3VBbRYC9vP/8g6/gb5Fsiu78DV9g4G+7q8Rn4FV/viPO3qwahwc3b1mQtshr9QL05TBhx42s3ubpZ0PvbuO+SPnqhtQz65AgcUQpOFeDOK/i+M/NILjr1JMVSeD4jrNBWIUNDG3AL732Jq5I6sa3RI5p6yhJhvDyPLZuFKhIvvZ9aCeNCp0hTDUqxK7FPzPljFW7FMnVaH7t6jxVOMx2LXvqMWyiBUrBIToOKDRL9229pRFLye1CsQRXErReHSQx7eCJj7ErSxNtJdYuYv4ALEmaCYDnaJKanRCVJG8KmE6SjIXMDQVQllSNV3HWi8NuLXA/1DZlKDvVraWZyzrlWgXeiX6/Vo6s+Qmulv8ALLjbwzG1CxE7qESP95ymmfXFkIVS5fPt3nQlPl+P7r5SrSG8lo+6COKWiBR5O+2K3Q1Eihw5TfxvqA9VMLhEVcmrEQ2PJ6ARLU0q8F7ttajOIsrn+nTGNxdybdFt02EXdDP5hr1FdMcPrCiQ7dxXkYyjOxD//nu51sSBuAo6l3j+IkENFHWxf9ATNVQg2bHuOAzD9+07gYXhL458toLMJa5NxouvAC1wjXq8MZ4Mrv3DbDWZA3cd2bdmc+CudMi1SvbWU9VJpw7MvmM/Z9Mt1SeE9d9nQ2uppkIleyEkgzOB8hpHR6tkbyawPde0pZTPuH4G7Lh7tyISq86twFpA3CRx6y0wyNU7YlffPt3iax5fSdm+j++4n2/czgdFRQduvkyKihI2FTVJ176P7CxhZ/cGc88O13UEyBxgABeQlWSNd0e6ixNheSZKDiSOT04NY11FfP0W8FZQP1PIQpskIdQkYfs+vNOaDjXTA7/2LDv4+k2HFTv4fIEOviaZG22UvB7D1NwGGWmUfFc38jzFrPsEM8WM1EM1SeAMYDysPai2yB3tITRYv/W1h+LJ+u0SUO5tksD10kNEkMQtcvP/fYgFvoK6PXJEu+VQBp96JKUws0pnh79fxdDQ+3wnjQ2CrWVq+7/eyI3wGmDldD3uSX97DZ8ty87tx9AcuLMuXWleXtq10+Sj2/tBKw7Z2uYAZEHWMq01+5nMPNx2xclsFsjr9SO7zRvE+dQvmwLdzg+b/ldNt7JwWzAI7hqVUbdA5Q5bHg4KzE4COYD4TJD853olb1m/Hb58I8QOOmJB8hi+C9/L/MHTIrxvUc040irVrOuFagTmqzdCoixoW+Zbiwi2VEbbfHhZlzyzDjJ80uZ2hGaHKxV8f0bgDdUGGIGnlFGv0vrvNkndeNqiERsqLtpKm4HtagUat5vuxjA+ccBcgWungzZAp+9BDe1GjJEVPFDOSeL2fWxXCgI4Jwkbz7MUWMSzNFbZPi1E2sdXcjau9P78kOGdBWxR/t6uYkiUVFWljmmSP8+wOWDXc/87J2jbI88tnNOk8AWc02mokmTSBzxy7jXRmjOYH3zPnx4bzg8+4fyQDYK8WEGqc4K7FZoXunIMiB0jx5hWrrOEm8+5ahHbc3XVmjGYt1Wrdd/ffy+HCNQdnCBxhedXIlN3cF2cZqQsVpN2/GYO4nPFW4oXmPduBWlX7/ZuZYdudQ9udecFhSu93i1C4bB36+MHmyxvhLw3B+1SN1qcF/StEF39XlaCAAM9di28jvA7U8aKN4I/vi6AUNl7f+834ATQqFP6aBDoc351rULJKQZolF3DeiCeqKvlCSCWXI5sL25Smmw0oon5+vHjxaYXcF5yOAPgnotvqzhcp3m2yeehH+G+N2NIIQLfB0nfDOC73K2W21GKHco8eeGJF42cN0/+aAp+s4N9RO/hVQ9Ottr3yx4ittr/gAMoSzpHL+JczdWg9xBzdZhTXbLEIvlxdtsQsqvJlUHyOQsgnzosorlj2rksct8DTdhnBEnl+CIOr0Gy+wC7l/eMhrbKvRYXJJEzAe+cSEDnzdVFAvpplv/8AdEBw8CV5I3X9WVWiohxi/K6g2f27Ds++kJrfX/y9eTgeWow+QZB2x6FXLuZrFxcgZkMmfEUcMeLaDWqJH8S0Fxy0EUbWesWocQhm8N2lXMLLhRz2M6iEiqPFOUSwNj6XMIT71nFYUwwttpbvUkbBFu9uRJGftiml+1oft142Q4qD/2ynZLwOy7k/W0WEV5t//Y4h2UJ5UXCLVEwtsqXm+7Oz54UajzR1idfmh8qqeYThIMJ4uBwaSYTRMEBInpzyC5WjepiMAfxub3Q+FpIvxOiF2KxiMBFwdwqbe/8eXYlLWbJi1gmzGhLuX+j5G48lvU78T4zqX60Y9LyDREXJW/7Oq6LXWBwUbI3vm+LpMqI+KHy3zsXbz9/Y9orGSVh65WbkWpUDHF/XnIwb3OIkq/1SrhQjCQp+W3geMi76qFmqpL9RDdRJXMAVvw4Z2EH5eFGGI3VoVMJ4/AbPuiEcewbxv4ilyRhM4DuSTeJhhGr7xj33STsjnFAfCVto/Vm10cY5wfyCA+pDTMrjTTodj7gCqz44PtN7DYLSW0mydl4OEt39tHV8gTfd78P4+iqoaW19R6b+VySjM0EtGuNEEnQtkeV8siZ88/PaHbParqUzUF7yuOgmBw6HgcPD++BzYE+vIF8uYK2NSqjX8UywS5YIMC5dATvR2ff8fFBPfnqqlFdquYgHhbTNVdZOmp6gZTmgZrOyDHJaCZB3RotOLuWcBWAFo9xh9flyLe591T1ydS+l7yAuW/fy5Xo6VWC/OhC/QWZZoauYU34flHyHbmtOW1lMeRE1aSGumWTTPZ18BlnZw7hJdy92ZvDdRm3ThaMrfH8VQBawZ7eHav4UnzFkoUvR3PgrjIyZEnV+J6isFwQusziMzr8j7pzsmRtJlBebeeWJXkjq6Hb1XP8fSNnStvXyNuQvs7j3FdBV3zKPQUi5wAghy0AyJK+fR/k8UOwmse4cwn2mgeW6mTXapZDwR+6WvCHThI4Hg1yF4/RIODG5fNeHbs3jN2jFOoXWn6RxbGOVIA2/O3YGd3HryJJFknXvo7satcXiiRuvZ2FlMyY6FuOz8G+4+MdaujrtEMFeHYPamCaJx2/178gAZbs7fsArzYCF8nhvg/xKauksnSAfcGwcjtwSlaycrtdcZLw7nncn6s4MkIomgdohNC1773CltNCJQuU+e7Cw09dZP0Ox3W/bynZGZEnuYKm1c8yGSICOkpKsYfsrCd4uCYqqluiKslipQ1/56o9lJcyrJcmAOYbOMdi8lgot73+K3cS4BHXelOFLXLXtd5Y2CIQrfKRgLUD7rT7sJp+EloHXp1ccHbvw6aGs0RsALOzB/NK5snqBb68dDJBSRSr0mgD24zp+NpReWoQ2PJgS2XBFlAny6E4+eErhRotonOlMMkxuHulsOpqzmoUKPN1Rr2vjZ9pwFv9OplTCex8jLgWM+jniPuK43musEo6ZwDh4bKdE+ejE3Dlg76dLROyHAhZrpLG8QxRYh5geIFde1a4/g8GBKqkcyYQHl8UqRIufFHkfNEviopnimVBxbJKJtfbFMmTAUx0//bBwiFDO6/0LGD361Z6RrT7hQx2vyoZnQmgT/qmhsvtW9GW26fksdw+eFlu//Cv/8LLk0SNnSFCP3sayCL/G6SuSVJnAee1lkhN8joLEC+R2WqS1dHdkbJl4/Y/pE9/vIbX902Qucc1TlFHGzYAFzThsWbPc2zO8oGRJnicI4L7/eIx6hFYA+HqDEFiwb1cy/ZgXmdEK/bAHb/Pq6mx71QVFEmTD87z+sCiskiUm+BxrhfZku1czNo+q1Z5jmSp+YlTXTjtypW//1yoEagKt2YQ5JMdnxpRjQ8Q14FWO0PkhCfKMpwo8w+3iSGAFzzz5DdB4xztm7smYTD+jQnP75yKtN1X6zdvEuLhKtWgeSk6XaqxQeSo36faWOTogu1zfhN0zvE4F7bPsQWoP16A/rNXcvwmeZ0BlFdQI/wmOR3Zzd3LExs8EHgK4wvnpodytB3GjC0cB6TZkRYOHNf8Jtlcb3lErMJkeTTnluEpF5VmguAuKryPc2CkYttlX2C77DfJ6CwAvFxUzm+S29EWuqvbEs+6oNtyICr3xtWG4sXgmw3tXiOxXT7wZ79JatdroiMX97BNZref+4gVZaik0vNpLcOwVrf+cSL2cxfItPbQg+0gPEegGLdUQalMV6JoFbfMaZNbZu8krzMA8rjGphGGVdPagcDGPl+HpmHvJJ3juSNdX3D+25c27Hg/YUPRzMHchlKTfBwOXCgstHHtrAVwBZPzZHd07/LCPAGCe9g39d7Q0ZDfkjtQ7peadBYUh0wuBGByLlpDec6spviYP3Gk3rtkDd9zxgiNBsF9ES5LabjP5sJWURt2sYI47ASd83x/9PMCKw6QOP/MQvWWSIHlIyTeFZMAj3emqZYbvDTNJ3D29HvTYkRFOERQhF01ie+cZkUNkaO/c/JHridXJiZKQHLOO0HkPD9ThAfqmXvKT/L4LHHtxT9+zwxBe4okaxZGHZKsZ8i/f0CmYQi+ziC+i9jTvBf8zfO03O/hhieHdGo64m9v1tCsVnN4L1nc9yGeU02n7cUnYwQ41LrddIE41Jx0qHkvORzfxjUW6II3IocjjvHZS2buxG8bRxTgBCwlX/s6lsvdJ/JekravY7xWybX3krTxhGdgyyGwmUxpTVvFU+m95Gt8vVnZehPDs/67F6etltJ5Lwkb324G1mkLH/D1YNd/28T/P7ZBMja+DirMYoJ9wTtwP+Nntx7W8kFyNgMIr+ThCZK2GcBX6z6D3zeNhTJxtdc1aDAI3XqIwAoMLo6gKxkbWWrepzOskMGo4ax4/VIVHD5IxmYC43OyznhoAFJFfWGnklhRbTJW5INkcSbwHd/NjzdExBeaxOtGmsR9gipxHwSBe4wUA1Xitzv3X76TbGnjFoo5cBfKB4RqDt01vFBBULZAF5lXYDHqjecFDm/Sv2PmHcG2czyS8DWObWRLNofHtW45ZWPYzsq0aD5hqqLLh7ebaCGcwuOrGwVnCzRleK3iwftlAHGd1FSwnm09CuoWaADuB2YH1I00Hh1vM2dPZab38FGwtkA0dX1BjK2Oa438wJeZDfhxt+TakX08kuMY7cG8yjY+CtIWyNbi1gVB3NSwKh74lVv6iIOPkrPR21qOnUYmg6973az+Pj+14hPmdmo5Bfe4WyGyTiQQS+b2fYjXocVREje6EnIeXodIqqTcLmzxGaOZbYYh2ZsFdIcT3aooCyfGFfYV/VR3SYRbuIpTQ5L8jSwsbiEAKTqwEEANR+/CJ2KEmpHhcw7JJJnb18FdsRwmSeJGFfXrfW9ofMCaRH84nE3PAMD7oNq5uY6ppAK0oSueBUc2xoit4G4PuUd4SrAlkXlKPr+RN94glaI9fOeYUHcvMXdLcg+q+IQ5vvDpwoeb7AE7/ipopobOq5AcCA3dR+FaqkwUdeTDSTC2yKNB4eIxtw0mqJGDvVPR1ZxD7r252HJ/8OZW4tJJaNJJxR66wyYS1afLmRpeweh7SBLrRHQemXASZC3y1Eq5eIVDx89w+J4aeFU/Z52J19VXmjM2z/Resm5LgrBFnqtoF4+5YhQi45Rz3uN8TeNv6Jh8PXy/B4TNse+XKDl5s4fu+J5CU/fLhYYAbPhgVRHZpm1DNpydPXAXa6X1WdC1SCMWzjO6hsXrUwzUq22Ms2Rt34d4+IqWZjjrndHy+APXv6NFixCx295nSdl4gsXDnpjWm4V8NEG849bpUO1Ax0KN66ADCzV7H9gPnGRuBvAdHh80ck5nfPDtBb03sV+4Cxl/s2RuBtBdZUucJW/rBbA2vP4GmsO0BuVxa6/q4+XeXt9euP52PciAP2tAi7NkbibgXW52kOzNBMrD44OqZL0zPjgHt9KPznBuJAHrI1a+FMngeIIw360j+yc4wxOcBy4hr3wi0hfJ4WgE62f4lRFudtjpdqjv4wGW45AFF9PV1WaDgnqRtI0XSvq7BLl/F5BTfNziMEKIO93U4pM9KKZmBpJAFLMi+NpjKS/PHmMoHpcVaZsgSp77XjU/Zvx7VdOJ338v/SNY81KiOXCXqRwoyRy2i5zQ80UQtUSWQHeihk0k8N5+o71sqPeUD2JEguwNCUpPeikG0V1mx1aqQXTXKu8tgqYlfnqsMojx5W11hsa7RlylCnqWaA5oYzkgNO39JWejRunlSuGqM4bwMvNY9caQXYdGVMnReDNcJjZ0otqE10fdqVXTqvQ7r5pOcHvwoGrabcTxBNBKhsbTVY5JjhhOaf7ou539U2a9xLtKhvZ9bOe0Rmp0Xd4aKfWbLsSBTAzkMF6VTI1mq66PLl4cBIgnxbPX6cupkqkZQFdL1OBx0JgZPB90C1gZXOu3lbFZl3y5kqeRTUS6JifQC4nJiVJGwD1Bg8dGXI6uhyqtA3RZtX9GilYlRTOB7irL9iZpmgl0V9sGN0nVeIItsY50PJkZXo+wzRJyDBsimyRtvBGu3rWxp1LOpIXlrC9Z1YBKP+UAukP3Y/ZEd6igOzRJ4UwAvQ5FboLHPazqskFHUWAWDw+KzRZ2bBPkJkhc5oEgDzMw273f/vW3gsRWa+lbNofwMu6GJhhc5quKdPHI4HCG2KYcWnnp0T2ezrgdR6c9cGQBVUC02kN0ucm32cN4/OdM88zyXzP9T1kh7wH2udw2GTtg+Y4iksZI7NJy2xT742JHKsImaFvmy4oGGLMcW5gSY5t2oVjxKfNKrSKvl/cPFEe8Xh6yvF4eNm8O5XXKc8IWzKE7XDatQbbTNS11s65B+j9/QCCbCLKSp/EM0M9PG7r24KctTensXQVZSdS+j+wiem/YJEP7PrQLdXCGTZI0HvuJ7HgYTmXFf/rHbKRZoMOAI+yCDkgwO6viC9CJsEnKRtcVxClN+4iuq6XPX4Mf4WrKHXyPrNEdfAYNPWySrdmAd3iVOb4ndnjVqr/JzIQLF0TXScpmA93xxifFh9spfBLY9sueEtvBOzT6Bye5Gj8ZlkheDX/YdtiOtz2tt/wJTpI1AzAvdVswOEnYDCC83JmK4CR5422nnmzkMd4a/87B//x9q+Akffs6toMP8dAXnKjboTqpmrkOzNf2SAxYNABZELlHHF46UhUedXd/BD9XHmk5uhJcMQjtcHeOAtlOdY5Atl+bQzufPHp8g6sGkZ3046YR1OmPW6na37ayefxtix5QFiyu8NxgYH3pUHw6KWOx2F4z+M0exuP5K83vWieAhcXI/QCWr6QYOaNI6QWXK3xprKx2icc1Ge8ohzO+E/LeIL5rWaGCDwYxXuU+cfCCvhXeMKtEN7QJHONceaSGv3UKDlGp7IsQjvy6oZc6eMHgCj+Cl9kaA+HdpsTiVynNCF4yNwPgnigu0/AL/jLUJL/cg96yTPab3oF7OnhJ3nhSs7HsNnZPpylRi1XWQ17SNx4i/Plysdcbv9z2t/WULTCmz73Ge9ODl8TNBr6reB8el+B/4eUn8DZQH9iFq4HO3uUz3CFI4tbLuRFWjG7f3c0V9Qc80W+maj3t2KJchKTxgTWKauvBEYQldTOB8JzvWAU3/5BdALNJPytUyAxcEGlJ4HhTp/J80Kxk7BDSIyNFUt3T7U0ULNvtocM3BEnjTGA8a1s0vCzyctvZXRYlp9p2BsnnTOD80lwxRJkznSsy3BrrNXGlSuSIDGpEEIzu0X0mPNZ4Fho5h3/m6/nw7W2lw1LhPekHBSp6T+IG3pNQDMK8RJgoCGJXeW6zsb0cIc3xiDS/c6QY663n/QTX/4zaD7ev3j516WvPgLKgd5VIwreuDRLsxgu7x4mtjxIQTV6Lz23wFPfHNh/wLc4B3uLHhVIzIK9kcI/OHLyzFkeqt4Lb0+QGv7s7yrjAb7C/j4LjVR7t/OF4WDaHGY3DAohP5OHs3dYMMVhDeNJht06KXn/YjSMLoAKg0RqgJ8mFRhnWVff1yQVp7ruu3iS0grtVui66NnThIRZ8cfPrL+7KR6JDlNSte8hN0bE+4rb+F37PJG/7PsaLlZ+FKAkc3xwV5oeAc9wzGqtXqd0JUZI2fmassdssQI13xb9vb+MybbJ+3LixgusyBpMkORpPEJWLQ7UXHoNbhPl8Ncw66ZYk2ZkBdFfjZ0nyMwMYL+OuTpKr8f7OyFwm2FFQDRTJzV0cd11SdHEM10NCkoTNAL4rdUAkSdkM4DuHT2geYs4nkizl6u8qKpZypQ1KuZLgbI+ecHmnBRurwYpWp7go1/GoJsHWGl23XQOy4AAmt3Xz4Rf83m3xiBetqRohUu/7JSNEIhA3cxCPb4o1ollnVYzpi4NtsSfpC4fhi0chtRlsz80PM/eX3emB7S+vHdcSXEHeGl2wEbGMVSiHNIEXr1f+kAWFazw9pAtvzvlxW6S5LwdzyK5Rb5QFaWt8C+TvL+yTN3dgwbZa+XfIgqU1vpRo93H2if54mAX4yI1HlcbAW4xilSvLgwBhybi0vLZ6y61lzsbgndbFpQGaNhAk6SfrdxBs6CdzGfxkWXI0WjZ5zbOASoabYbcr2vmf/x02RK4kNWRJ1EwgPCcDoFnEU18vHDLupgBiQ1+vT+DrzZKrmUB5sT6CR9XOL8j80JtnNhIYIHJ8gvGbSx/Q5zvsUnebNDv0beqO1O8EsDsUyeD48qIxBgc/fWmSTX05gbJIDmcB5eWsO0XyOQsojxsgNEJaxwHh8HJs3wVBaR3JyxbJ6vgqI0Mui6nsM6bk1XxRRbK8bwO8RI1fkeTu26iesu5oZ4fO8EA+2f74gJMacZiUPa+7/SsCr4ObvOxWt6vfzHhbfhqqRZTH1UrNzNCRK9Fl0lcsr/W0+BV7tJmUJvDlmcIKChBtuw/uqxPaSOSN7zkjeNh7m86a2E1TWBg9UrC/OPOFERopaXbzMLr57vtOqj1nZ5kR0it9G1tiujupSqzOGrprNUBUbw3ftzTV8gWHqql2cL9RgwD2TCLr5s7+6CmXIer2Qs6tdFccdAomG7kaTQK8YG6+JoE0PWHo8Ko0vSfw+kH0xf2UNZuD94TXWvHhdrzWWOnX91pfN3T4SCDJqJLK8TVoZdc3YQhu25Tw5rlFsyJu3Nkzu9vqeMZPm2RuBkBdxL9TJWnjOcJwp8DPau3LQGv12xp2Oh4TVcPO4If6ME3/oskPvrmLx6ZfkBjK6yXV/8Adhib52fchXib62iQ3+z62S8jnTVIz3uGZ71m2ZzW/U9q2xrMVGmB5tEIC278KwMSaQMSaJinZ94FdJ/faJAv7Prir1Sc3ycT44TwH5Vrxfkpv/+C+7v2fJSeMRYw7Ac2mr4i7yroKxbxJUvZ9mMdn3DCeDUoA7UE2iGMrkRXM7HHxeOiNmFFEsqAe1po5lBeLD8bHMvgXYr681B0qDAM1h1PfCKcQbTpvhE/yjRjjwnFz9hA9N5xpftQ601loUmo8GNDu5d/CqQe1A3ETbM3xTVpmmzR4Ffwzg++/+i4EgyDP2Qir/CN0JQze3n4gIKO313vp7Y1bNIjyuSs4qgGCn8HBCbh/CacQz0iBkHHcBJdzfHfp2O4SHmPvP82T4QduuK0zyJVEt60z39Rs8em2kiSygsI5mtPU+hm24+XEJ9qhNN/txy6Xxq3Yg1erSY4dfeRudA+LYNe6mU1mxckg8MRNkjd+Oa8CreCGvY9r6SOvQuem5n11rozEehLAyuB0iptkbQbgXUFOjw/6awfYBXNt0UkG1+2Yxd0wlvLNMvQODb9jTzHdZ0Ia1vUmiPttChnUlGnY6CSPMwGz9qUYyssnzpIrGHJCN1wRC9kXNzDkRCcJnAl0x/1OGvm343e6lrrJJ6JfLslUCEgZRyeZG08Zb+Alo1HuAWly3eu70UnSxhdw7m4vfRJYyf7Jl/uOMwuWi7eik8yN38jz5LINFm85P0WgXK+0JDrB4DxZXtxOEW5oKnmXw2xSw5niqeANZ0WOat2Cs7KRUS3iqCaonOdiO9r4KMjbjIjmEjVc0TVzwC7jMImPp+AXXC77RtIDg8W+IUx5gefQi2F2oeYWZPp1cL0tekHhfC+zQn7jSGZlZPhdO0wRvbeI8DKp4uiDRXyXEyG84HGeZoJ+aDLp8QSa7MMn5wfLDtXoBYfzRKu8ddeTWnX4iRs7YbwwQ/aCwvleeoUcGoPpbBZDPvXrpiFunZ83F0E+6/++VccGiEIglvTNAsTnEm2K77eTaFPviH7/vSTH6C/xkrhZgHcN6uYldeMHxzKTz/CiRZ3wk7ZKUCgGSdy4MukvHg2pKJ1t7sPYGvc8BEnaqDCprEdN2xG4/+b1zBgkafs6wkuVgccgSdvX8R1eZ2p+0VTPbn+VmaheRn7RgiBpj2dY5FiQTGCOxU3JsawRg48hmUP2nP1UEwDg7lO4Z86xBVgB0mwO0jdouxxalbY7iqsgZIFsJO5bYeziRFzjwD5t/ZaBGKpBkId9pxqZUXUG+sBzys5AN/LQClIW+Mrnd8X+TM6Nz0q0/tnMYIybRaCn+RuGH4oAynn3qfBEOa+gnEfB1gK9gHVt04JaWXYc71mt7GwJZ4hLdOTz33uCyuOZ3rPjgx58OtFbBPjceKZ5Kfh4JoffbjKoEQWy4X4tCqoWeMDCM4MDngn5628Y9u/NeY3tnK6IUfK272O8TC1njJK68TRAYf4y2Fx+9frKyCvB/WVSeui6y0iSJeI0HCWVo/eariYoDFwQE9RxlvsjLqjxJDfejz8wQkVyQP7mwpYAS05nAODVNN8oKZ0BjFejzVGyO75yKxeHtBnDFvF1t+T7+pHHxwmXJOXofsu1IuWIG1COJLmdAZhnBeCG829A7PrxNyXKktgZQPmVLecQaY5cB0LrZOgmh2JgZ28cvhZJEju+RdZ5o0ZynNMeZKM3IGOS5O77CK9j3UmS1fH8UL64AAMFtnI591Vap/lgO6xOzej+8weEvyQjp0uS0xmAdg0/ahJU7iETi+y8QykCsvPJHQ7B2r3GqR+18d80/Q8a22049tkWe+AuxZOT4HCRp7EaSMG0DSYcjmT/0lYuNXu4zlnWKz9g+v3Kz/fg68UkS5EY580exoPj7rHbhKOcKDf2RZI217X9BvIDFwBlQdoiWXveTb9icmCm35SeqMFvSASMHB7seVMzyO0H9lTH9PZbk4SEWNC2yBNZkW2WkVT4geD8206GdOBVnQw5qFIuLM1CgA32gF1mNsvRHrizylJVoaHOlKa+Tloyruujg219FtQt8l1ngSu7bB3n4mHV5Ce+YWuiWZYE7vv4rvH4Su72fVzX2dFnydt4CpZ5gYmdMs3ICy3oRMuSxX0f5QWXb0XyOJrYvNrRgGGgHW1KlfIqxzNjkeStm9j08AFjDfissPwr4wPWaSj3mezT3WB+iN0MUWZ9Jaxzp0j2ZgLj1cwmRVI5EygPh7VUA0UnrRUSDBQHia2NLTIcWWQUyefIavN+XkRxqzCnl5/hxWuNiqRx34d3sd18kUTu+wgPt4NrSmk79eC+wSDRrwhPkQwSF4+9Z0WyOX7xzcMmjmYGvjYJPxknePiQW4Kdk1I7hxjgBWgll/s6tOtYSopkcF/HdpVbF1WwtoeFUsi/Hu+IgPzbntXI/as1tFUQuMR3nJn9pqFvZ/s7935kg2GfvlVvD+F1yiZrsIfuatS4CuKW6Ib+2gsB1Jj0QowdZJh6bHP8Hm994RxvdqTUHtdvVfC2xNecjtxjIBrws9T3+y+ZGtoQ1WwR2iUuOtViEdr1Ii1VcLfEW35/Xtoq315igphzrWXo922opotiLBHu7eAYz/B49K0KBpf4Di5cPIaGIGUYXy+dPPFCHB9r4VpDp/oMGdyg2NAkbfs+nMtVfzdJ2r6P8TqKTpN8rXd+jOzk0VZSj21nX5QiX5EdUIrs6g45q1y/TfI2AyiPz7waNb0z9CY4HX0w916XbdheIqGVdM0AtOduRyueB347Wn603cvR5G24ihMSWUnVevliDbJ5yru72IqtScb2fYTHtTJNxoJLZT6BybcvldVIWrlSxHdBUrbvYztsb1AV93XsDb+xCaW9gZ7GCg4ZcZNMjW+H0UBClcir+f20HXViIW0HYmUhbb/zrCbsp64N6qmbJGm9eLGsr2fgPru58PZxwY5Edvt/nzVghzeYGtNTZ4NZ4E042GCyexZ4cyFtgqY98oQywILhYtBu4henhRG+xtMr8letF11pBOEEXC1t3hrC53aXmr0w313e5Ujl6jKyYSyDNJY2QdIyX679PgVPGmnb64anhY0jaYvWsF0lOJg2QdMy2Vfeyjs9dpGQM9Hbpw1PQzXVnVKHuyKpLHUIZB/sNlgIpy2bA3i9PvC0Cb6WaYvyzwuBa3d8IerXh16VI51PvdG/oJHdG63FR1wkG05bNYjuIlce09YMgrvM75sTnC13y6nxCDd5fl83nZ6ce8dWax0zOnjRD45hsQua6HdKTvI2A/gu49hLTnI23v6dWFMcnrlIr7fqzJ7Oxocz/WRG742h2TQ5ydi+D+4SMpmTbI1WUTs28RKb/+7a9ieGMWDCqvgPbzj07YWTISmRkyFwMCQ5ydjIauLe9I3aOTZ9+8N7C29tMxsR0fnKPTT59Had/tHhgqI6wFiSNgMYqz/gkUc3q+ax2E1eZjaPeazXSk4Std7mhyRVQEMvf9+Gj0QoxpZrnQKz344SZYPZRiHGOpLkJFv7PsTj367Gh9P5eN2GOm/3A07sWIgLqPM6Sde+j+4cj6lmA089pmDZ67pMY0PLnk/Ssnc7ULSDmOcE3cUJiGmGYtZJrFn7oOE2s6guM6uJWZ9gkvCSu5nA+ZT0oAC3Iz0gOT5QHxIhxy4gO/aCvz3adURl8oa1W1iZPKso4+Q17vHNUEBtsi9ANHZAL+A87AWNK2Q5pP+KP5+4GomudDQItQCR2Fae3OROPpoEd1Z2RRuA5flX8avXTa84ki4OMl188/bsoObdvg0q+iJrUH6W4X5/+ZYC2k75Fkpp/fItX4mUllFJ89kguisJwV4Qu0JDbm77+T9QfTYA+HsViGb9O74aA/icY1JFnLll0kEMoO+ZLGQULg2HCMHqCl9jNHbbgtTXD70Pyw4RYTMJ7rSOVM0vHQ27JWmD6HekbmiDcBlsEMGZRHo4xT1evBVB++kHuUsj2o/H+GsKks7xjVFgdA5l4bpNSnLPY8w8BqtmzBxegBZglQzOBqxrCO5BMjiecEuXgEkW3HK6dDQ4vL1Rx9SvmuRr3wd2uUqHFCRt+z7Ia6lnQdI2vumszJ4KCmWYss4YL+Ubj7TguHAQaQnsrjyZFiRh61WgOlwig3YWji9yf8S8Y+tcXgqSs30f31kXxzRfMj85Vp18gXsnx64mNBwgmkT5ceXRDMqLtHamKNkazxPW+0/Zk7d3oA/1bfUvGpgpIYZH4sDjB08E9CSnKPna9wFewuEXJWH7Pq6rpAGioGuPZl/RkYwDL5on6/Fz+5Hmf82b26n+b5DH6lf/10zyWB6701NM9gBe6HJFioKxVZ7V9EzMQfdv+bQEOVS9p3Ksh27GOFHHOpEcYjGJ7SqtLylWk/hODHJzgVcX5B5Ud6OgaZUGYK+t/zAs4IOb/mI6Gt6eUxn50luA9OHgOaDHMhPyh0fL/y+y3eSg2AhTccwf93l/pLxM5fbV1eh0+8sSadHxQbbopOTsgbtYWXpKgp9Vuq68Pg0QHiRJoW3OMDYeFFIA28kJyVVldw6rbAwLZAxLgqJVvlOrF6dwnn4zJTR0MZ5ztSxHhq587nzAiSEHGBiSZGsGUB7+ddOQic7PG6mJ6/++RU++YbK5TJKp0RzhVu5L4Cc3iyfl4qfdNNewYk6KAehuCsARmMkjLAmbAZjP3TQfDwFgM9RBCGAja6CKa6AkSVuvSlK+EaxKssYZc8Tw6W3N6NC5vC1w7V/d/s8fEL9xRIZMkq59H9nVsoRJkjey/bmdVPAJIMaTCl+7NGj1oEJ6lPD94tuLYMlSPpqvKM9ug3ykoUSz/VGdXjmwN7DTK+TzzZLE2YB3TlxegTOPy8ufuG5YnvkcUIbIksXZAPmcPV3zFHN3utTUu9b0RtoPG9ocsmByj6Mh4ldONuzQXzlDdQ92LjumHM1hvE57ZxY8rnFVXdfe6eLr1bOL9uzkbA7XVZw5uZiDdpq1TDP6UvUX0ip9a1nFtIovkFbJgr81Xo1aWXccqGfRTVF/lyk+zIK5NRoX3DC5zXx7u9rZL19msjL2ProczAC8wrXMVARna2QpdD+9glccYRbbNQ4MH3FcYlwo3hyuwzqkSinrCJHOgch7IEZuTOX1xO1fJE2jq6Br6yHGs3GXGdPhe/DRYigrWlmRJI33SjrQIhPRGdqcZfFaXfVFMjUuqDvYx0d2qDh+2rs3EljpvRIJ8D16JJj5NGxoPi2SstkA+JTcq0kF8dkBH+IDxdeTd5icYSmSudlAeFbXgEbXUSUrukUDJFnhyfArqRvfCzkoSKUw5y88xoYzAEVSNwvgzjqeqdnO8+uZXt7V7d7PTHhWt8qruulh/DeE8qTTLBqMO6dZkoxwd11+VRfhrpLP0bDQdT2kGduyIZg1L8ZnjJRVcjsDGC913a3u2d0tzkx2nBu0/kZSvrXr1fmwHjzyEfOuB8nuet9wIewu4mhcozWEz40TM22q3YGC2VQTtpvVZA3bpSKFNQt46bboKkzAXVh8fWM4Uta02+P1yqprMQfyeDmqhsap9PZ+MWpgersjl3drFcDyZtTCmlFBFx4MvS2cI6pNwMvXRJmtifBo9EB/xhvViOHiQycNPH09IqKB5wcc+RE/DDt2UD5xhmw8F1tgejjIxQYyPrgNYy7NCXS7R94qoIu7jRDnPBELOiKaF0CTJdLNbu1wRwd26ylZ2bVWSE3SOJ51wTo55uvxh/hO7jKyXo3aJH2juvtVgVAcCkhDL8SJzdGQh13l5DnwojEnT8P5rEnyxnXKwioQYT6Lr5O32YUw4+RNzdwaK9QIZPZtkrnxIiO0rjMPjyvbtx5c0yHZJpjb4ySvNErh9DDpaXiffGbpgkirBoFeTWpvgs85okPc+qMwEUf6oz4tUw59vx0LSoAo8oEFxZMwcgsS3fxQJo2gu1rUJW/OGMJrhJHzJqib4zJaYDIaORnrX5cgJsYxNCePO/NveyGO4SqhbRcgF3kL9rBdysyet2gP4SXuL+RN0DfHlUksKWD1Gq5N6ZF6y+6YV8updsccYoAXoBXszXFHe4JrN7SiK/mjH7O3xDaNN6znTTI3AwCvMi5IrmYA2vGYi2Ze6ORcEhxzO4i6XGtocVcsoZUMjZdy/cpj+xcXRPRyGOZ+h2A2pOV0WmHyK6Uwjm2MA/lJe+gKvwDzIIYnuU2kEHF7fVaY/u4qfsg67+6cXzInSRm9wuI2spdAg058vX9gcgOX4qn9VA42O8nL6P0K5y4Bc1ko8abtW5qCXUksO0nPaAHMtSoVndTwW7bbDn+mPWMEWt1zcDCD0c7vgMzMSWb2fXDPOXuVgnlHMSffbl8z1wEsCJrnqnkkDwSOC9+kZ0PhY4240M1ZMPO0Q4CzNYAXulycneBonuq5WyOLdzz5GvJ3eYQG2c/E5bMTBM3zcpLIVsPYfJj/frdsm/aJscxWMWp2zSLCy/Ru5cc7awnf4XpqlU2PT2UY5j64vsCGXoeu/+wFZ/NU2L2W14Owy8rrp1zBWsDvlL23h+t6dx2zF6TNUwFSadgbmBtm5600o8NH4tvZC8bmuf6YWK0ZuRwSnry700uMTK/TvGRrvYPQTnOWZVdjdAbchaYGydZ4gUaDG1iMT7h82BP1hqHXst00e8nVvo/tOFdTlQxwsobH2w74WiTH2wLcbste8rXvYzuk81o9ppu9pGvdQ9C4VkMhfWAuO/HxDh3O7Nxq8s7Lr7d/rymHgl9vLfD1BsnVvg/uUsmfHCRb+z7AK6mQQZI2HqQIzOWE/rF0uKb4l8hwkCzNAK6z1hPDRVBNu58oDn/YNgcYC772eItFOwZWxuHy3bk2YXKYpTcMyw3QtdWVG5LDsq2wybatHJI5kNfr2spBkLfASzI864FC7SxN0c5OsTdN/whnbxF2xQcEju2KfcFdcSj28B0+Hq8ZIDq34+X40L8b//sHxJebyC+d4G+BOtB/HghyRQgeiOMk5ocfYc0IrPHp9J9g1j6L2arQrCF8oiFDAypvyEgOlkH9hozU2DIIndJxs4btWiadKOhbIEuh+/gALijEN9sJBio+44/kf6K3hu8y7Tk5BmvYLhh+z1GyOB6oQJcZvVRaBzpQT3zDIJtpAhWdhrhbkEdg2/Xq0Fw2WviiZG8GwJ1E3zRTcIe+bbL+qUvfWsD6p5hk/VOOkr4ZgHmxi8Y5SgrHK7YSS7rCAjlPSQcNM7j9FoPnVnoULiSAl0MLqAKikrl9H9FlqntzlKSNN5ZF8DtQE1+csdZcjRcnyd2+D/FSnS5Jcrfv4zvuhdIsjjtmqF8zhM4Q9UtQxOINf86SJG7c9vDz+Ibnj28snxQkjR+BzUnytu9Du1w5XE6StvF2wwjVsnTkbUN+vnGT+rGm/tpANmcYS5Kp0bjg1T2NQiRuKPKhEvmROwoaBvEZX2+S7Oz70I4boDRvbccAVZN8a/v+p5KJ7dQ7tJ0mQcsegrqsJYN3AME9du+92edg94ZCToKpRZ4VzBePx/GgJb0d7uD/1bNiOTVzGA93TGtUyE7JtG8RXoluy3SKxIJ6IZmrvJkDd1zj1VCJjsaLT/CBxJvIExzwBc6CpsVeXNCBt4FMYql8FNxjcYEPYp0d0Jw5LAteFnmKjXXxYryqtJfJwzTZxuoJ0pyDNYRP3qxRAMtv1uDSsnuzpuKccBXAJLTRGrSrVeZkQdMi2fTc7Ohy3KV29HS4FP5HZd0s6Foka4lbDJO0oWNS0PkvKwuaaeGFXc+BZW9LrJpoQ+0xS85mAuF1ophZ0rVez57HVjjgxP6v3vCZ5hzDWk6WLI0W7m2efboAbXGvQzu7JNLgpr1IsmYA43HBbDwwGF/IC9aN5AV9wsBgkWzNALjLzL9FkrfeaXiy+SFhwc+/vEM2p85K2EN5zsFKOLDynA3f3yLJmwGEF2mWLpK89dYUWBiJU0N61vr0BheZ6TrZIombBXTPjbwa6bwz88Yqz+X2x15fMh7MdS7Li7m5COL28OeIg3cy80oPEh8/De8+pKJ5dj8UJS7FHKzj09j49lI/ijEaHAgNLoKmJRoKvC4lsGcPlhID/sfZLZHjzy1mLg9e3MCiPw513iKoWqLRqp/vlhS7wHc768Udr80Zb82pL5TmZEcWwg4G3boZxHbW3l3xHfO9u/yGe1v3Rh6IhDJOFVQt0fzP9X1AkOF9KPGjD6/xz9ebQ3atzqcqaFriJZHbXVN4El0buEsxzzBido1ZozmIlyFrVZC1RBYUt45TfB9wjxmnvA+LiAxVcrTvI/uWo3YcaNVRu65IVsjgG8nbK/na9yGeUwmnymdThOEYbrcVLkYMDf9AAxhL6sajKZVFUyoMEP7lx3fdBVuVrI2HJzLpe8LRzOXPHwUyjG2TrI13GWY44cwEB+dnnAtbzyvdJGv7PsgnZV7NxMtl3gAbzAOZt3lSi3H9CxJgSd6+D/CceJVqFc9fCrziejCrkSOuV4u1hFlSON4gmS4+A8x4Pyy8PkbMDLyrXP4dE5R3r5igHBN3WCF9E/ztYVEXATYMrjDbdHqiob3jqRix8HWqZSXA3V7ZRjxQDXu1WrKI7jIEuQkal3mf4UY8/6SVsx2/Dh8/tqJAmjtRkyx26R9bqVjs4gsUu7RiEOdFROAmOFzmO4wG2NLifz/piVirHq41ixgvc+T1Nsnt8OWLDF2FziS2fK5AUqmiMZEHTg0e9EdGdoI0Q/1/2Zw9gNeQgssmeFzmCwzPdEqMxYdvpABGfuC4FfV27EtlRc2ugBvKt5IkuoK+5Z4K7MAoSc6Xh+2TBS9PrCWdVKb2hCOHFT5Z+FwlX+OSbyYV3ig7pI/LOiMN6Z2fMRQbDn7JIlEbbiRZwisJG/el/3ydKDcAYavH157fwNbGFIderqK+lKtgD67HK2Jlk6Tt+xAP/5RpGgZ6v2WhwaTQ/z0rnkwKFzaKSarWkyXJSghlyW2KXrbQpaCySbpG9UjShsyocH79DshUIqwKZXImjKmgAyrsSSrIQSiobIKmPRJYuym3kmEB15nuo9cphtoxOrOCi/Du9u89R/bsos57OyVkDNslLroWJ6hZ4fbpys7lArCfLeQdunan0hQO7pNTTQHjl8UJXlZ4n0sCby9NZ5cRyWbqW6v5FeNPrf6dLWwBT6ANFqE9OSVofsr4lHBd+WqnhJyQ9makvU6wtEIbSK7nGnHGRdrrZ5xrXO8GfHHJHMqTVvDjFac48h5oZJvGSlJcNgfzKU6seYk7lFhPh3//AM5lgK4gbIUfTVBGiWe1kCylnrtqEeLFDL/FSfbWk3o3hdQ7ZxBeLGxRvCRxRPy97zGhwpfsMQeukL6t09vWL56XnK7bTiI+ZdZO4rb6SY1y6BZTT4losLboM7uQSXnGxYH/t3jJ7AygO87rVF8uJ3Y+vaChxYifboj46Upux5tJWBE1AXfWb90aUo+XrM4Etot4JYuXbK7n9CXPAqoSUwzV4+XIKrc6L0cO0DzdL0cOGxkcKnlyJYX7PrbL3LgqXjK474O7oNjjBYl7dD/sHt8AeYt4Jxz7Nsnj24JvnX2tpuWLFwSu8k1GgoYd9h37OPLr9jabWeeWjc5mxlEFSCWeQbC1Sl2nbiNfLK6KW/yeBjzy+nI+7GQCts+IVQnYEpw1jBfo2irBW0N1jsqgGXZ1GdguTWMZWLx7V4KgaZUbegtzpENz0WerHcYCg51UG/E6HKTaqCE9OAJvNAfvQiuLIJha7XW+yPJe9jyEfPQ8fLpWR1UmSX/aIHTV/2nbMHTlsgxdlZDNobzSNyxIW6Xbis2T3iImQs5Yao5fC1JFBfm5oORA4Q1dr1lqhEh4lHKC5GrfB3ep/ukSJFX7PsDrcYvHDcdfkPm2rZKFJnH2PVN7P9phpHkvVDvjHsTsRrHHzXyU9I2vgiocxGPmyTDlbOYiLTslSg5HlxXX8SHLr5dltqds2V6ZH4be4MbfYFxj5u42qLI1psdjjiVKCmcA4Fk9RpoxmBcZ3Yu5VU1GJaO8HiEgX6LkcgZwHl8MabbxncXQLa+m3Qz5u94uRwkAV1I5vrtwd1r8xNsXB+6wnHskjkU0Lvp6ju4czTcK0vboOhtpGti2KU0ZK+WvYjEI8Jy2DJVtktZlQLFkvzBjw9H3Og5LlAWBa91QC640MS1Ut5HZd+o9XVUcizPk3/SajiKHSurjErTHlSgIXOMKu7/D+aR1IBzez3z/bTHVnW1+zuJaGSDA7Z+0SImAi9g+LoP8YtsTf2VlHL0UUtMRq5hdljG0ge/cMHcoPfRvmBfHpAdi803OHrpz3t/0fHbgz+/tR2jC8JAEZWtE8dXnskYm3alvrjVVMgnC1ohopm/sTP7o0X3rl4vUWGOH4pehXcoC6e5x6FojkdYjwBztwTy82wyKR6G324wNdpujD4NgaY0qkddpASkwXm2bQdImfbcaatH5bje5b+t+ty3gvi0m2LclSd2+DvLwV3uiZra8so8PTIsMJMydJGv7OrbLnNkuSXI1WlWvzF25XL7HiIe+Y63Lt78yJi7fHJBVSMbWO/kqi7doiHDOPn48VqFpiONmM7SnHyQrIsu1kX3moxf5F1wuQwYWMQZzrwtP5IY3xwfNJjSzpG4mUJ4knim+aM7erk30SvUs54A/d1sAnPc87vY/GMrjZN6Y8rg4UHG2vFc9B4MQz3ovVN8yfTDcBieGem9GdkQJDqAE52gQ6HMHYhXodhrssZ3goMR+I+0EFS0QOQmAidR+myvIQgPninI4V3z+/i5nzOr7u4N8OWeBKe/7TlDSR+uS24zDWG+QKF/5kQOJsr8hio5QOgcQFwExL4UJpAcRZ4kUPinyjGRgOxK7Wl7//fdiEibBgFzN4brKuZCSm8C21wMjq/rYUztm6JtK4jS/ZB0Wd6vr1dK4xM4sXBOYEuBHqaQlgCeJv6/paET87QtpzZEv+EIaCIoTAHNtPTG7Dmnu869PY5P9Opr67952E3zV/aNurD2ZFEUVSdy447ewuQF3m3GbY/ldIVFYJF8zgeyCqaEi+ZoJoFeLbxZJ2qhv/Xr1vMp3mARktymk+NzJENUsQTcarWhvhlz9OzADBy/LU4tkbwbAnbPvHF93anedv/9c+M9QcC+SvvEzAe3icZBAG+XAQaG3rZQtWSGKJHPfR3m4TkMFbKdP41bKuYe2f+qiseyQa9iGWCSd+z6647kAhWrWiQXMkcwedTq/YJLd0H1uwGpJnBu+1fhgWDCrgro9DjJIbozlccCN60fzxpa77KugbI471SOcb2PXhJw/dj+8l1YM3SmlH6/8dksXZPx03YafriBvjsjpV8mBpQHwbdg+erIJB91xVuzhV+yAGLNfsYw/YlXwNcft1OniN3gWiKLTXhZ8Z/YQWEtZ1GQO3FMVGieOuWWQIw9aNBzbVgSiR1ZB1RzvKHFkaiDesx1X+4BgZj9sUYtFfNeyklRB0hzX1BtLXSCNSIc0Ynbp4f+BL7jZQ3et7/eRgP1FmF+Eray2E7Kau+ssZ5Zu5w6IKA1QdLEJQ9rBBRHHpAZyVbNJ8kY91tfyWVTV0TlZh6yT71LM7IiSTXI5EyifKi1RgNvpLJEri+52vtFSRHJ4t0kaZwLeJVw7TbI4Hg6IJN9CVIg05bzmyX2QAl6+D4LoRX8fVEmcOwOLa5LFcdu6Zz9wWHYWDlnc+8Py41l5PLnbj8rXjZzc9Qlv7jbJ4AyAu9rZpiZY3OOMk2zTwETsG9s0ljgT26pJbNeJF7ZmEuATB5vGtxeugADcX2CkQEJZQeJbH4GKX3y5/1+5eBtZYEwvQZx7zK1bhMiOuUUYH+omuJvnYYBC+uMIwAPBzRMKO7wMGoW9V7XjXpgfciDzQ4XxoW7eHLjn2s7Gz0iDD6rfdVaJEao2aYSqmyBsvre+kG5fur6oU9r5FtMc6hbtYbxgjrBugsR5Hg1o7KFAHbg8Ozo/nccNkQuV/HBw3Y3JDw6Vnbplk+AuxuPqJnmcDZiHrRCaYaJjhcCamAMrBEu3sK9YUjleal/ZJAxMowy8xCtjK1mcAWxXKVGuDyufHXDn7Dg1HzE/xhDUW85YyG9cAYwli+NbTs8uBYBO2QZKjhY/xVCdZHLfB3j8gTjxPoDEczCfeSLxuA01HieJHK/o2gjJIBX2Y4ej33Zas0PfdKc1+zGA//wBwSzQAlydpHA20F1l/1adpG58uVkgZ0E1nu31hpKprbSa95ZbVCWsXXtqYkMZWV5UJ3mbAWRPxblV5mr+8HrolTvIcztC2Ii44yRh48vNDF3VtIr2GV/7xBEcBb6f8pNUJ/maBXTHHwYNqeiZ10t9wbweHD67cPamOsHYHtek5a8a1nrCr1oc+lE7qa3bPY5VH0vMX3Bpauh64BhadsjI4NOcb3fW9SbNI6H6hetdbmoE5QSr4+oFZws8N+QuDikFqUwduig/MQFra+r13iK48443vTQ86CcHJqmTycwHi+gOPhBDM7Bm+3aXx9gETJZvAXmxF8wt0LIzh92HicVbYjgUHT7jfTD0G5cMgjvtQOHwbxzIv91fuUrE30hwzgZxHt5baKbgzt6ivRCPdZWokhdUJb1gcIGv3OLFo7SOxup6eCjrHf4Sy9a+6qs5cE/FY1W+s04+1tVXArIbm9I84chesrjvQzyrnUDlo+SN69Jc0u0nyOgtaWAteTDjX4z5+q2AhZ2paPmwMvUNU/DYGUhOM7Cf+iD7FlmpJ5Yi1iBZHF8MZdawATJP/atRjrbsrPMCB0nieCQrsvJvfB7i8WWczxTJDe8ttFuLTLAl3CJIBsfbocqdrz0rLRmLzr/tMI7q7e04rIN8Iw7EiEJ0noJQSxrHu6MqkGXmf3C1TYJ6FS0iCCIXiRJ8S2CQzTzCu33v4qZhG3DI9jBer522BkHnIg+7tIuDpcbb2iBOXkcfDwz45tWJgZwKJAZyKzIxEASji1S2dB7wTeTOnqtDO7llt/WhmQR3nWn48ej+AkyzGG5jbUe4lfswjztGtnM5tiNGCGg5rAApwOmMwTnHk7p/cTmw3JQ66U53jd4YsOd+wjRTGP8F27Q/X428AA0udNcoOFvkalmGsqhIpIa8zRjC1ggIxWgO2EmPgYan0cfAy7LvvkM9YNn3tSJRYixp2vcxXi2AFSVL6ym9HjuUQdNp8dMv75NbeWdlnH5Qnsk4qJhFSc6+ju7446sZEjqvb3IS2dExQZKxr+M53PiiKvblvtPfLlld7UtkezXsna1RUjF+5Sbf560nb20asu+t7PhPkojxtURmGzX8KWsv/5TNbMyw1bdVkyRlX4d2sSvnNUl2xhc/4RJw8QM1h7sTeR9GeOjsAl24C4S763a2Eca4a5Is7esAj5/Q1NidOic0fcCm2W6oIkaWwkRoJU/jkYp6cXD6CtcQ4dnO8v1lh4ovtvP46l/exAzTG84MSfCzx4+cCLjiWTHSdJgHEq7/xo4nCZKW+I4nMR4MjTrTjsCuCHSxCPScu02q6iJuLnNFTsM9WTLnQF6OADhXiziPnwjQPMqcGlfIaB5cCEisvr7i6j0JLpfIWu0GL5mIAd74ur9s4QhA3sxBu8LRsZoFiUu8NC4wwxM2qY8cxJp9cUEhl3U8pwGuhgzKZdkbBHUNL2QOBqFd4yUQhC31lj4OGxwwA9+e5QTfOoQNrSd4N1HyUtTp/ZTFXMnmpwLOkrxxLT0ywReN0m6GyX+Ok3fesND9lHU3zWuWvI1q6s6TMhK0N005ULrMiJslU/s6tKtVDWTJ0b6O8GpJtixpGllcpBuXwGvbWJQ8lohf1lpaJFHjknq8eDyyQH7ePvj2Dtke4zttj0WSs69jOUcS0+zXNNuf/iFzsv6JuKMokqfRHcXV/Yg2aHA/Hida31p2alpzLJKxfR/kFVvpi6BvD8FMlp5ihRmMDeFZcG226+mJNfolZuyTNDsckOMY0ewQIngdSjKI7itz2dD2J3ZavSGbHbq+3riRp7hiNLtkgwBP6xfQfMz0OfbyNe4aHhI+xhXfYsHeMtn/3N7iTVUWN+W44zKOh1LtgfuOnAoHWplT6VvTvUN+sTkAWXC3zNvMMqk7RJUyTpkmVjj7WqugbZlWP10tJUg14P3Nh6HhN09pZiviqjMH8XCBpObp7TVIhgbzQ79FsngyP1zwrnmt3hy6K81nVbC4zLdDytuOA9fxZuOreBU68OqxrUwzI6u3KrmbAXDHxzKV+59Dm1+YyrIjU5kr5GWQ3I0s3G4jA3Gi4mIzDt26WrdetkriZgLdWXErjq06bnVwj6k2spXHHHGVjK1bWYY/awjvTgP+yO/akParap7u98EVuggi2asqGRtPsHj27qKPette91HPDsBbuvlaJVUzgO4STp0muZoBYE/NYuOjLp5aORjHqMchoMehSaJG127OXcIm31ysQR7QGN5VN6KZGlTZ966GwwDGWFuTVI2W7F1rprF0BGumB24Fvc9EopkeuIvEBYi+9owkJZNr8Xh2pUnK9n2YF/uOBW17WB/kZQXUIgHgaWmKU0eZVN9vLx0Pb3H/MlNlZ69cIW9xsojxrL1mx1Si3WtybAFXwFRQtsIXFf5uInnW/pYPqwvfX05k7EBmK/bAXcu10wRrKzwK1C4eDdSkefOTFrOhk7mqI3j9IpLEjuAx515r5nA9VwipESI7jZABCjMOlLLmyRW861/YA3wTfIwBvAIfbpvga4VnggrshOnVhK+mh63e1G6bt4jxuGVaMYZ1LNOzxrC2BYuQvvTkjjTneNXvmev6IT39PcONcNskPeNbtQCWMhoVbMfXrN7xgzbEzjrwBjgWdoCwJ+fCGoy6bZPczADA/2fN/m2TrKzXsSdLXdhzkGaFUmZZIIcdkNJA1jVAFo1/rG2SnvG6vQjXEfiZmsN92psLXeB5GHajB1kg2zejVyyQjZsskG2bpGgGUB72OqmqTTteJ+de8Dr9vLqEAftIpjFJ1Qzgu0S1VnOSo/FsYGC3lvA3bYa9dJVte3OSpn0d2tV+3JwkaWRxea93woGMBFsHbrBN26xZdfE2J1kb7zXMLKiChhwfRua0aSgP9WTwTjiYIfqdcJ6U0FeYIZygbw+H+kgx8mcbn6x7IpsT1K3SLcX1LcYjYfAW+21KgeQqld7NZXvgnrKbamSHzooNxt8DHZ1Z/fGKa3OCwlUqoztmf8INW37dEXlS1RlKV/FuLfDs9dvSiWXPB2nZa65ag3Ypx0hzgrdVLvk61mKIlpxvzsBDa3gKMZzQ7g8OEZPwP9hIkL2gcJXIkul2mRGfX1iz+df7td7oF3lpz/aGHHzzzhy2izScNi/IW+X6b2WuXihMz4fz7ke19A6oOi29dRWd//wBMY0lHMd8sAbsKtdVmpccjadTEkBLm7Q+3cZpuUfrdlDXHLSzxByNC5KrOdXN2bZ5ydEswHuuaE/z6vaK9vxLRXss1+rZNyyZGg2qXOkE6JFIJ8pQNHCWMcdu22nzkrSZQHmxg43NS+rGu/jaxeODgea9mj8qmcEDrOlv6HSP+PZCr2yKBN2LR2YcJGmjYRUtM04f7xcYSWKqa+j7y7dcydbCbwRfSdwM4DutXkvzFvO2Q6k9dBdwGaWHBspDkBTOAMiLkLggSNwjAyueX6Kpk+fXvf78/hOhwRaiPZzXsaSGZA/dZfwlQVC6xtduDo5bsaigiwOU7n3uB80ToSTMXQNETI3g3ADmYg/mE/q65meO6+sYHzzQ1xOJD0Z0l4RqD9y1gixB8LjGQ1iRhbDAOjmnQHLcVqJRglUlZgeWEir2kOc3buaAXWYvHwV7a71yQ6JWvitUvM5UFr09dIeVnXFhJ4JX5+BeUGNOdfLcRsnbeEaoQvs/W77VOGPgXcOoHiVR+z6wq1l9o2Rr34d4aBYbeXzdpkE49t7e33++hzih6SFKzkbbI6+7C+xMx6c3TnGsL+NDjZKpGQB3QUIcJWfjq+QAgy/NtZRtgsFkwQM3LUrixuNDnsFMpjQ/g2AMi+uq/vSOuh4bvBV9hb0xv8mFPBZJ0jeeHVKeJS1DuZaPOU6++l4kSeb4luj3dXiS0prTVL+KhzJJJvd9aFf8gPec7v+19y05kuzKjitKwPWXxm8db9j730JHfhpxk6Q8LRSKcF1VD08BUQXwCOZGMxr5NQIZ9p997wSNhjyWnq0z/43sEdWf//oiPKIKrd9SXA3a4bN5S1XoXM0DrCcX8061wkF4RKUEwIrB+vd0klfz/HlreeTztq9NfUt5RXitb3foXsg0V3etj6x4uU083LIisq8hGFoIbCUYGmfCmACuALBMFHOHSFjg2LbiZwx/5xy9GaDVR28uTEK2LYfsrHdrKBD62VpJcRHbzMiyvntM5g/EenVhS19J53oS44TnuQALS9egAyyQEnfjK75/DoWXP2nZLQftHpct2S8H7D45eC0jOdMXmsp/mhlE/MtV8iUDhqWXxRkZ2hL4blIZkKQtge2cbswiNNPtmCdnna4LQRDOOo6cdTKSNR3ZFkW+DVOK1i6cko1s6LWSGh9zT0bdxFP+3OYjxMjatEFfU9aoJPT9/8krBC9ytqvh3Y5XIHW7GuCN8sXaPcPmB1yd35aVeyc3wEOfuW3NHgqythWw3WW9VpC56R1xoBtYafid0h/ovkSJOvJN0ypfURi0vkHMG4TarCBx07vL+hEMNiUuXPF0VzesL8Dd7ma/eClPs3QWRLVyOnn4t8T/BZib03crRcW0kXl9meGxM80RddjYLEV8wF0LgiNz43CrvwhyXg3kbaSSBfia08crnnzN1N7dPy4cmdzwWoYNnY43kt3sSccblN2s46FZqavBO3xfYUC2c18BsPaPK35+D1VXOL8UYGlOT9KLclSnguDrGawvXV0ubK5zd51eBuI92t0KRM3JWa87yLVILYf9UNzN65qGdcxQq18Q5j163hoWhHYfR6iKZK13vWIK0h0w05k9xzFZ+eqvmmsoNe3PctwhjF7YurMiY+tGCBVqyVhXNjZueI/06ZE9BUmf+puKryhyaH1vTRrCjJxtDZifCom3LNlM6/h+PnxT6/gvIoL4InFbA98ng4st/YMOLo4VvQdOAhdKZvcB5zLZD1Skb73kJuH6zXPf4/wS9j3+A9Z1vPrckT/fyWQyiDtYd/BovSKVWwHiTbT/d5etH2z12sIJg1Q21WnxrJF4d/KYBWjpfIgw90AWqrPPKxdEGMnc9QiPK6JMl1ZaElXYYb2rioohiJOgI1Cn1pDC6cVQUBcAojTMiI3fzai6AZW7R4gMcI38+N3VTEczC7r6oA2/av1rtqL2xQLWuBqsGwl9W1oN3ElCyWHyFjBOs0/evClPswF583Lh5hxV3p/YgN8QnwolX3zAQkV42HI2mh1na+LvWzr481aWA3kvsWQD9uZ7yzcRLM83xafLt/duicbnadSm9VmGF11aFk1aWw7kHW4Cvn+/GLDPDXfGZzvua1xjm+2E42sQhMXh9oeIL1A3rxecTWwxhCX1tAHaNo3aDWG/JMJPJcKaxmedbREti04mlE584shG7gYx8rc1IN4rA+cGM/K53n2Wo4NuYcHl0hnnmH0SOwSqScjTd88ISsjjaItxAxa53PXAzrpoGXaQo0D5voFc5bO3eEQCGdmczoFknz6tXj9lzO9thOdulvsDd7FZJkJ3+2eQ0C2A83Mtm6VU6JbN/KX7+T1qgPGy8IYusrkF0J0WhGPZLMtnTMcC/amEOBWIoqNAPqf3yvn7auiPO6LwuCX4tII8ligtd0a+WLdGKRDGNSDE9+uLVSDewRn8hisyustx3eP+7YYsMjm5pP+8HwJ7STlynzKqfGoTZ6kEnUVcfmQP51QfHEhSeQMYedz1AE/sHLQHl61z0MgSqAQoMrbrAd1K+nBDGKmbzoUtNJ9UBwLx9CjLWG2fuxwav5UvNDw7uRw6BLoV40Nu6CJnuxzdSYxt/KPmAsJ8wtiKGJ8VRhkZm1SY3KoEiyiV1LqcwfzKXfKioWM3gIG03dOOfz3jqi436bZ7oAxv2+oCSwvaHDV/OFb/UqubyzoTnXVWm+G4C0uWAXkT+foNW7cctuNrY9NRt94b//ij23bHoXoxiPT8cIGuBbE6NlfdOCCpnll2LY1Zp+4KcPu1t3gBrisC3bAcunsdH98gjstB/FTltYjOdOVlV4KT4utUU1Z4nemBugW5Nf70p2ZyTAeczs9gF9sNeX1eDuOtnjAwt9CNKOT+gSrEWjecy+iAbygjfVsB5c3maB6pnDalbd9BTX9JeMbO6Z/phtdv2O5Dhx+E5V7oVooPj69YlOJjyoXhHhrVgCxuAWR3cVy/oYs0Tlp6fh66kDEiTyfHLD1nfeRGjGL0gJJMwbsjythYHeUTqaMC0jl9wlm/5+p/2U8edQbZmJYyZHjOWoRWPMLcFaHFyhOfXAlmpHQLwPzfH5N1wxW53AK4bvJxQwYnlkPfDI7SAoTN0eMOaFt6991gBeYW9UqofXie7QjJ+uP2RtunMNwwruthPKdv+P1F08IS3Tgk/KJphAlewrath+0e0WPhuGP5g602+s2Uxa0SslxI137MVlsLRbceukNVYci5pMhZzqdSBHDuPeKcee77OVxAlIG1Rb27iGqeI4y56ght29pV+QZxWBHijSZmEcha1MsLtjVS1gQDAabTGPG6afI3kNNqIO9zLBTzatg+pVe3dGgdvTpgeyJW//kL8JyQGVxEBqf9f73oI4RqcmTs+zLbKE0obLZRg3wiIleTd22fT5Xu2vip/oo5H89m2UuEGpGxLYDw+Hs1KRz0g/UJe4UTq7MYuVcIkVqFhJRtAXCH57qW5Hjd5zoydxgsBwlJml6pqcQQUVzfvw4ecszovNdvFb/xvaYgvl4Yv3DDF+nZGvju5Jt8AxkJ2hogD33WhrLd3CE5hEu4vYy9tVq1eTskZGraPjmRQid9k+PfN6/nyW6zW7GhdWUn5SLTnOEk6EKJzJwQmSVkaNeDu8tFcUKCdj20uy2BEtI0uRn+3F+yfIT2l+ntjcRQtpBeYnIfcWJd5EUf4Q7RSCBvWwLevZhbQua2BMbD9MJkHtfJ46bv24l0RKGb+fOWkbr1/NVZX8aOOpNSYaell1qmkVpEjS1a3zzOc4vmKrVoGRjdnTHjqRuJJEUyd5hgcTacXmrxmOyllzZKD+mnl4Ys0kM+HLcR2a+G7bRDFkuvpleaGKXXFahnTtJrniAGLpf0pWYhu/UonAjalGHvI7P0sV2xtkl1B7OM7hvWLEPIfHNcDuA5RNnygjVPtpLkn5//aZOagcil3j0hiiTVPWF7/EP3D9y7ZSB06ZmNm/v1jFWv9sqHvGw7nMuKGO/GmzMQu6SP3n7yx37XYxpNuDyw0hjv2EbONnum4IkatpNMskN1bJ+CPkIXKF2S+6LPk0K28WS9ehwQoT1pqzFSHTriKHy4fWWUOgZwFDwUjgKULonB+/eHjq6OBboXWNCOPODOQRb7RZ3cZEVhGOUcK1QLkrkFAN7D0qgglVsA2WGibOkYTGeEfY6c5BmhuGMpSODkGeEnR+YYPeLI9dxMY7ZUktmbBVmtqU6OBhD9jMLUBLhe1AMkb9eDu90EoiB7ux7jSZvkcYbsvm4lTCS5fU00YZN8qx6IMhI47TjpyT1ZRTGU0ySGFw+DqWgMa36JI3c1v8mZjgMKMjh5U/jZ/XLaMX/k2pRRxIaqiIIUbgGYrb0ENWnBoEr7MpoW0MZGdtUaWEKVIEXetgCkezS+FTjbfS2Hnzee//JZ1uOF99+w+q1A3LI+fksfnt8vT3UuyNNb+GyzAnXLerxePjzfY9EGw4UwA9sNcqRvwAJ1yzrezSkXcB74Hn5GU7aNErjG9cDdsBeraT2YNwrZrEDbcs+iT2wruC8rk25hp8l4LKI/KeNJyI/7Mp6D+bHLxI9rWRHop8JMDfW4k2WK2PZPBpQtjBhS1roiuvvMKSvQtyzWbt/THUdVmC8yRpaa8+Y7I0IT7XKG053ep66I/Xzk3WZDJrcCyNvsNhsyuBXQHZ7qHONDnTkDnYakrZuWx+pfHjvkU0L8bmvfYVEUGih3FxfF5J/ckL8tgPFe4smGJG4BhIdrguXZdmpCoTlv604mXVBHWkF0ZQ25m77SqiJFT5lLDpwIzBz6WshbZ+rr2wM2OykJmx022WnI3LRzZxThY+xiFE71Dv9k9lhDwqbPW9juTMbBuocrw5PHmyNsLVvGvaEXCpDFtDfw3KwhVbsc1y1mvQ0Y2l3KB+0ti3u5vfUDF7EzL90sk4X3GCR/kelfuMrzik8vAkvGYzne+V7POwTNGjpfsOjxAzbGG25dLuDZvaXgeS71BOk4+2z9c9ZaX+PttcDdxs3BHUDGilhEfPVbWGBlv9XmTBgn3RI/5FXEt8SjpQDIV5FGcNa97y/N2LtdHJY9rHJHWg/kcRMHQ03omDggO+g7OKiVg+MMUnfk9ZCdF/CqS4It4HW0HgDjKnpCWz/8u75eQ4x2qJuVS0hsZrtxbFm8WNovfKVzrIXvc3ZEphrbUYg1invuWhK5g8cxMeM8xh1IwPQo8eeW8o+7v6//0+8TjS7v1PBl8/oLXR1mdXyHJPxh5RJnJMHPulu1JGNqSkYW/73L1ZqEwf9BL9ghNbsc412Wj84hMdPDWk79iCL1ww/UhmeUeCML8w4zs9MyheyXGgSRRVqmheVOmfmzPuzNF5XLk16HFG0BdGcVXkv7oCuvC+bSW7JoHhyXXmBpd1E/eGlha6a8tL4K+dNTxh2OV53Ly+G6TUqCc2U5cLeIDnQOiFqVxyYiuVUmJOTrpOUjKOugJQS5d3NShO45iu8akLUqBuXfJi28PCeydj65eUVZWNzmwvljNXj3CwByHuha1ZcRt/LbsEqI8ptOq8S/xte8Xw7bLdQfzgNdq1qo39S1KsdfuhlDhh1UCh54WtWjXVs2Y3g8sGrmkdRqnmPOIznT1kKeXGKltYV77/Bm5dt155GeLYDsPvzMIz+T8ttPv0eyLRXZSvFhFrGp44LzSM+6yltWMJISpD6uvH3ZHUmn2NruSE4E41Hql5JAFmnZ9ciOi0MtvitaHFonae0C0jA5vXX+IxiSFtObJUtD1Kt2Ejw8NQapdG+nnegLHN/ruQAE7H6/N7Av+/oWvjeCdd18HxeAfzWpuj3ch2exHX26pgwQnlKJmpQKHZmoq3SbcyIVPbzamwn1UgAi1rRUNH43Wn+FYM9JYd1mfBDieuBu4hbkQloP2+FdmX9CZxOpLvQXZlGVBbFND0DIWnfuxVckNPfKp1+0txw9GeDVY6/gE1eFzi69UKjl570fIltWQ3bSGclDZIzPSE742FHUHWSh5XkAPtakEFec6Mh1mfePV4QnGBlVWktJ6LS53lFJ6Le5WbZioiQAJ2titPh998DSJeZkx4QpwiyNvuWbZllGdgX6Yhf5eegHAMdjNYD38bdyETna5eC+YJGuhwumRfrgZCEiP5ODW+eUQoH4WZ4yqNksR8ZFJGjXQzx+bWbRJ2hyFqkqnGzLglJ/0Gm/i0jProf2KSM2C7q9wRih2/diUzU3C3SRoPWymcWZCVvlTuFnO0pGI1K162HeZfoYkatdD+2GntouIm/rRUYImIm3tb88G1/xhkcuIzo6PCzDfRGe1D6r1heJm9bu80GaesXlPPfkH7Msd/eg4HWwnWWaO+yZS7k9fc/cyME9N3AI5d/k7esfHXd1rX8tMN9sEbDI+CH5FUEeHp8ZUO1Mz8yTs6ocAnzh0VkKK0K7S5eWIqCrd8Re3VTy2PeX6PEJecMeV5UprYjtJLebh+YP7HZzMn9Q1oKZO7OUV0R3twFaKoCyXBRbr6h+zX7f8GGjN2yZrXfecHvgDbsq3vAHT3lSBXT1PrN8j9H/cr/xUwK9po15hp9wo5V815PBiVGl+Mi19WDeoje7x6StA+wcuyHTx04SOI/hPX3HocDhPc5heI/LSODktY8QoErzzBBHPnTTI8VXmvFkJG9rALwZRc7I49ZA+amdkalKdGQm8YGlkRPeZIm/cxnJnD5gi+rgklV9v06BXi/9X5rKZaRy3RsrizH0xRViKKtOh/e4A8eV3XKcHY8rQ6BxZUZa1w0aZz8MkcT6n1CPavy2hBl53fUwb1IpkNJdD+xzx5iWTYY+xrw1Vsn6ifvM9iMFsIuVJMAZuVzvuo3bCP7G5XL2iXvJPm7pTvied7AMuNsE+biCPO56cLfKoXIFeZwMRfmcVVpSJupAON34mIeer0XB3nu/IT3ygA91su3EyXZBBrcAvs9dtliesD5tacV62vKZREWNw+2LieACd7t79eL9BXE3ZVd22je85djNdK6phSa+YePQ15rkxH1D5suhkpaDd46G3TKC0CL2gpyi7wd3CE4RiVOUvBzGe4QkFCBrTq86MxnISk4RZ5iQ7KJ/KEDXnDTZs04l4/kG4yWEYumPWlsQ3acO5A3Ydg7keeB7ciOfVBhF4Od7d4tdCOBtbmIrMDbXPTfmK3k6Nw75YcY2e5Rj6RU6s5xA+J6sK5rIXnWB0ldd9avhO25U9JuvPeRUNC0WsAJBc3LFdsNT9AmE56fJ5Pu8yobiw43GTye5oNmJUA8+E6pIzvRirX23W78fKhtuDnS2s7ykR6aP7pBWvGJ+05kvCCcosbysyND0ii0JpZm4F6qnKeJvt9LR9cBmpTNaDJCN6UVEE5mr/GZrmPFkt+q8kJNdD++4KZyhCnQ0ZZWwPfGEk9hWgS2Ssm7QD3/HCNs5RrxbPV1kZdfDu9OY/O5g+AOvzma3dWFfBvVv8yJZWmzakI1dj+u0oFtLGyaHuHQu2FXpZZ7hNhrhNmRk12O8h91xA2p2D/fAmB++VhExP0MKsmnvd+Fr1xZXxHnYC8r0eet4QXn2PO17QckqLEQMDViaF6uIL8W/g2tMqfg/5gwcN8ylaXlBnHcxHmhlQXDnmJOMpzlnCnPutsI+8NQsB5qaNaBxXt8OOjE1Y4coF0ZK8QsdHizFQn/0UjR/9I7MlCNnAhoInRdz9O9TWPJQF6ew5XSQ/vLBr0k3oie/Pj0w+o2RH3GI+Ii/FqCLYbuN3tQfQOl8d2HBQVbUrc3KVtjkK+cP4HJeLi3c7eVaHH3zgFzvhQaTywS++wOZnd5bNJXuzLuh9MZpz+IOD/5ALnc5spMkexbhtJ72fCn0TZq9nIMYTATCGPlcd43B7jqEcXw8fWU6y1hKduoPpHHXwztnb2yaWOrF8ecfG3fHLXD/+7nmQJSRz8mFxo1oCBUUEw33ZqOd5TOa/IFEThv1ORL+JxEkNCejaT+XEn8gi7se5X2e8F2L/g3uPdXtVyEuH44XGzzyCcdbT+OHFvbJSXiTo3cb+hvlpgTqTDWcWw/dzfRR3gGdC/oIoKg4eMb4l9Pvew2VhyKg5SCNBhIn8wguEoxwWA/hrS40vQNGF6Rc/ahqO8dentfJKEcOWpJ0dsC1UW8SrCizJ0M579JyAO8yTnN5OWjHHTMse+WOZYbj6/i+bcZPE/IbXNb2eAcMLuhLgKSM5Fj8W/6ysX/LJHitSYSrKyI8viayFAa9JbKviIq6IRSPF4hbkFsMd3w42mKICON6Hp33Cl+zoS1yJ2k3U3U4Cdp1SnUS2FXH32U8PxDrA4ysNvZ8ATvltHiPtHjvkbrpIXslMXBSn7XwuJD9VTEtFphtN8Z96xfbx80jc7se4ucujA3Q6gNjnDx042BFS/Y5pkBgkbDpiCEVQSYmZmNiv+l+UBaH6k6YMaULnazoo4gXco7bXo+UbQ2MtzCL8x7pWs8SyvN6iCyh4pQjollaSgsjtszNukLKJMZmqkYgbeuFDIklMvW99e0xhX+YSOq7wtYLO6drIg0t4UqgIl27HtT9hCUeGNs94viXfueg1N0kaMUv05d3R0CuWxzachDvYp7h7zugH2z1NL2RZbKSPrQwA9vhMwyT2qFzhuE4HrZ/hnF7z8JN3XP8rg/A26IUV9/6MhGeR33ZSHjeJN627Cg9+OUA3sLNzAdgbVFPIiMFuimX+jnATnP4NuCsHb6LR6C7Bt+x8qftxjgQ5bgcytbyy6cWlpqge95EYpLQXWMmtYl3nhfFIS2H7XN+fHMjjbuefDLSmLuyAJQt6qsAo5okTmkdxrU6lrerpTr4cLs6Hbllc3y96UNZD9lhtboB2I5YHadkfaW6GuQ0gStStQVw3edKKCBLE8ufbybBkQpstfO4MdSzI96R1UTHhg/B7ecpeDFCd5kCHv2d8v6Aq5cTRVDgSRFu/8AQMiJZWwHkLXbvEVmaXE98ek6bjtz+OjKe7Wf03zBpiMjX1oD4SZPk4R0m3cn3TZKrmJRlGpRFZGpr4LudN4yPSNvEtu3Lj0AATROdORPJjfoIJG3Xg7uD65mPSNn0qq19eIP1bLrw9Grd5gzJ2+UI70CJI5K2y1GdIyszqXo7o7Jmt9j5tJs07IgTsLf7f2MANy/imVjUvxw03n2cObyMd8G8jS+ZkY5kAe6TWxHpOSs3k++ZXltQLmmvR4u2Hi35FWF+8hDAwun0IQCXjP4hQBGyktL4IQOdS3ovn9Reng8B/F904yWiydUhjktCPCvc4qGJD2tLToY+XmhLHEtLEhC5pE+x8oc3ZOzmNmMgvJ+rnE/A6JLecmbB6ATK7gxl6wsevrkIlnSWztFFbHTSonElUAnRshyi45ISy0PtODwUxPNEVeKDmD8czOJSXQ7bLQkH0LokNp3fpnKWjMc4dEa46y4jI5nTe06n2gYaocUpquodJhEZmZtevrE7lL5gebxdmDjgCZbrII1re8Chz1Whkfzg1VBGtnY9tHtZkmQka9I/zh3CfVYI1C99uuMv19HZyklRyALYwm46GSna5cA+5fQybvQSSCB54vNSxUTdH+LZIkHTy6CDFDvqrsKfJgy95R7e0iR07uEB3JNjeC9PtjlLxGckZteju9P0JiNL05sL27l2fTwC54k2bOiYwiTjO1FNSxmfEJ9mYGj3dvcXrkrnwE7qn2vR915iDllH9qrCj4LHWBkOeU+sIG7LQTynHzOMb3Q/9mUmOGF0U4CbZTHS/eK9IsuCee+5xcsrO90Ru4GOwWHCk5W+jW/lk5V00MlKccthvI3IrABTy3Jk/pnFQu5lLM8ZiIaeauFgGYn13MsO0kieuJcVIZF0gXlwCcuh+9yn7QkDKMexY2efNq8+beJqsMTlIP4v30YUIGlZT8zbh+cDV/amfxjQjU/fS14M2Z2uA0tZDNwd1U4FuZo+aMt0sKI27F/6zEcPVqbhvPKKvSBf07aGhTxlpdopzDLXmvWiDXVDP2jra26ieUisTa9I3taAeSd72YrcrbcJYu6mNkFTRg/7HFdUZG8LoLvXoq0ig1sA4eH7FcuWuHPA4hst2/pHLCkKcD+EYUZF8qZP3I7vAfofG4t5BXgHdUNFFrcGtHvZT1ckdNqnMyh/B5EqP2NdPNijDc0onQ4jRO1/6fYQLP1vpPyvyOuux/iplbwB185K3ryPL3J4pt4v0jmx0vwSpCNn1oL09EeRePMTHn7B1verpsCOQUYytwTI40M1A6ydoZp9opZUARaShwYM7r6Og6EPFgcZBVuHLipmnwVZnu17om0akLciF2+fQbsk6hXojt2rvK48WLoJWR6atT4Ux/XhcISyXxHl8YhHS33QJKM+wDFKUgSusqKvhRXhfXKBbFl0yhLRCkx4+gvk5GnA44PHAU8DClf0/u2gNHklmGwDYfLPtWdDO2S7j3ru7pCrU+9XKFIbELmi9xqVUoSU7CyUU4D/PZuzltdDd4fxQwPWVvSiqKpFEWfb/FJLXlMXLDsLk2KyXxKaUkwGoXlodT1wtzHxbUDXil4KRWVQwtkrjxuUzNu7LUqIv1b/iyG8mSoqHMjcrod4aC80xC6KfMNkSRJ69LgcPJf8tJJDjJG3idXQt5sDnQqJuc4xEAv9wlKxyvg3HEjfVkB5q/TtcCCFkzdvR6AoNzVh91dsilbu1sKBBG4JeIdJhuX5dlhGJI31CdEIoplgF9pwIIFbAt0dfAfCgRxOb97qhz8IWqYZ7r3HAUMn8h1kEx0TnoCrDTMQWmRwC0A7527I1AzrwyGXsvi46elZjVwcbn8rwoxcbgGYN5juBIcMTq80m2rKxNrtGFlp7h8PEByyuDVgfqQzG1JZR/2MC7UPoesPFZWLfeX2wSGJWwPiDWuxAyJ3F19DLUYlpazFR364Fr/OsdpikypR/joftlWMr4NlFEQEAhmoXBXLzu/gaHZApLnPCMgve8uWvlg/Zes7dmpCnGghF1xaD+PNLjOCy+thvAWnc8DpqrZI9cpLjp0gjsenaa/yqrb0bG+Ihw2uLgfwdm1xWw7ijXyOggdyV4Uk4qslPiLBy7F655KIF3/fRlxNdA5vwHa4n8Nra4e9Ww/l4XQyy/vthJPhsujEiVYtP4P4xnngdFV60RpjeNNx1ju8Zb+82tlL8Ejlrgd4znbZ8I71chnb3+5qWS01eCPnkcZdD/B40LElJKCTdPxj/G9LOw7Vi8m75+8b8rfe1ffBZmji6vu9cuv/gmDI4JG8rQDwc7HHlp1nRxRMTicnycdRWJ04R4cZwSOLk6KIT0c0dqmlDrgN6P+e1QQPjYXtbvZ9LxmxnIvkihY8krgF8N1i/OCRuml7ZU+lQQHr2oDeeu/SG5C7ddM2qXFgNzSX/lMO8fJwlpUXngHZmvb+zaohm+N79LKe10KJZc8b8A6u3/VGPoQLFQ/hbtVhQZCHq8Pvtrdj5tepDp5VwRpZgpUwRaq2Aqbj4UKGktAJF8LxTT9ZSLFgJ3R9AUja/RYZTZX5sJC/ZTU+Du2+zgQhAElregHklKyPbT1X8LJfyZYrBKBoTY/QbarJMAPdF/iB93mapGnI0k5IGpeHQg+4rIbwDmEBIQAza3Js/pkzRrAKApHrGbCv3F8uO3oMbTmAt7tpicDSmh7vBhGWJyyNRu43p990O0O32znqjhU9CQZ73QgkrYm54/fTJdGIeLr1PChg8lx3ZfIb/Xq4jq8jxrcRPtmXEbFGEVmcIo0aY1gP3K0sPENEnqYtPKvyiGKLhykJsI/QtCFcTRy4b5/hFQcW3VhElnY9tOO+ZibjIm1sVhOOa/reZiULaxLvWAMZkaNJB8/PNRp3CbRGK/85Kjev0V53xj08dfyMAzB2vDmbNNMRmZo+EsrCwUiMyH7pyRTQL/fns2Dbecdi337ykL3Yt7vCC/eInG0JgJ+74R6flfEVy8kJd1SOGpn3PhFZmz5jsU0b3JGuY21DRyxas/d5LW8V7Tlh+RCIuCUkbtfDPBw2ZCHDnawhQLV1S8T/+wtg6pC4k0jI3a5HdtINlgXnzg3Wgbki/SS9wLkiMWGuSEi/mdzXFEMrp9lLmciGn7QNmpXfYtkNmfhGN7xF8A3PE7QUFgR5LwFqigBxLxESLwBUIuSI6eTMRbHJmKCzKA7tARlJ8aKb+BCGMCkBvHp3kYX8iRu2+rh71BPd8Fiqk6bLySG2/a2xr00IoFi5lzJAq2X/Rjd7P8dw8rmDbkPd7Rx0R3IzOjnoDsrNyInHWxZEeM5EzQK1Hql5PF/pD9UCn698FmZEuQLK2oKSNb5RaXzPJeqvl5WM14jvz7tRWeKDeMIHH7ilth64L/Gg7KiiLHvOwR3RPfl8HWgnFYfhLHQS8o1i6wBbrfsPSvfPlbf85cU1/XKF+l7L5UpnkubdAwGyOYgA2Ur5sSEjfVsD4C2EJRlZm/aZjLSTV44DAznST16sLH5QkZGwXY7u+ALZgmxng/ydsmvcIH+PG6lbYGyRrek9USQ3cHUsOIWtbeZXnZGzXQ7wRp80ZGvyYOXwIqZQiKjP1Q8vSbcY+ah16q656AZ1bMVGRRk5Wjd4jC0G2DrZ1QlVd7PsppCRqV0Psbk2jLg4ZJPkLHZNk7OSnCn9/z3I7RvYu+MkACtGkAzsBFiH87AMqHbisLDYdrOwqpqb+yJQBYbm5Nz8xn6d4TLb/0Ef3nM4vE65LcDOnJiaf2cRcpSQsJKcs5V4au9jwbaz97EvfbxcER/i8QJDc2Kwm76SAFhsxiXhAnyXdqkvcUF0Z9kaWgbn2tew0Yai52xYnXjGokqkBXEeD3scT5R3ntKbTtIenUpviiz2LcDVnJ7vBtWQidOKv1ST/6TFYSkrYrxNJmEodUV8d3ORLEDdnBymf2pIqBcWhxdpKJb7hU6HK8km71bfP1DrM4FMXofShOBT67qOKeo63t8VyZ321nHEP6Lyfjm1fpm+ejv/1nXOCU2seXCXWZHMXQ/mUBMxxOlsfLnL6BRfFsOIinzueoj36SEq0rlu8o0hIjakhwdos4/eLMYOPZ6BNOPk7k0pJMW5RUUSJ8e+7hABvBx6PnIkP9UfzrIT6hjERVoJnXjEebEScrwSqkjhFgB3Vrdg2h3LdqE6a7sQUxMj9kYwI4tbAOYtlCQV6NvdT/0XsThEtyuArW0SsdgDWyBtviv8Z39DIm3hL2inC0+HtP+dndtPQKZt7xajGu0QvHcLsx94tfD/56H+tXUr7axteIs43fB2O9p0fLt9YbpaaTrhfdqAn3ktTE/0diW4/pwFv2V/YXi8nf0FK/9PVhgqx9gX8Xr9ggDvYADTgKl57VfU6DhTbTbzMUEA9ZybtynCWD/cQAuhEztvL1ZCjSeRLa4G70Zb4wZUzYsx7/c5EBcFoZl+b5LY0hKdltdD9jXTcz1/tE7PByeQrawH7zCHsNBeXXA93wj2aYS8EUyiU0CKpuXo7iNwn0ujx/y4au/fkDo0JGvXo7xRdPHXlGgxeHeYMcQDeZrcS9xwFQfEvJeYRCM2ChiMB/K0FQCe1jkYoNadw9eg0LZ2j5UXwre+DXFG2qZ3QP57nfaHEUlrZ7ziCpPZhzZsbDJ7sgUq2ZOJunO3P0SAkbhdD/A2Z23xQOJ2PbjDXlum+tsx2/oxxTEabnmp93XiK4fsTV+uNJI/qfzRae6Sz90CjJ+80gPuXwN48X6T+MghfVsC362EqPEAGndPvwLvZGfwTn48Y+F1nofDPYS1gygCYFZTx6MtBvCTN/GWMty5iacYx5ObeJHimGjsG+8nbYuAu0PCYHTA3oLYEH8tgQQrpiVQPj3W/mctk6Pzy4E83vhavma67zU3vT+//3v24ICyBX1DmKnplUrpMOtEc470dG757btIqvJbGOq4JNT7dMAuLQnw8ELeIpPsbOQLUbiTpbyqFXywGR0QuKDVDkVdCbGTWYwPz39neupYdFC9jPhSH8iID07FshC2QN5CzyVO6KAI2/Y4tPu7JEeH3O16iLeIJY0OOZveGzdKfFWDB39crzKzLDTfdCUf71redcDd7pIteuRwC6C8k+IseuRv+iAzfXjyT2f+Vi9MC1n1ujh6JHKXI7yTyXf0SN56lnyYmqcs+coxAd4dKbJHBnc5yrtFwUaPLE5uOT+vsPgIlo6FQjj91L3i4uK8i+gLJ9WHjvxgNLCEKmGK7E2s3r6PhMhi5zWD9acANe6C/v6k9WPGfn7/p+Q3eiRtVyM7SzVp4RimEXBPMtkEwonOtqNH8nY1wMPOUCajWc2JfyZgNmeoLN35+Onet2vfyN4zuOFbdhhMfGOZMW8YTgwyfb06iUGO7+H7iUG3/xFCi+ojr+IDULaonSWdGvaypq/N0fSNLzR/I9yJqdAbTU4EGfyMBb8gpE/qUC37Ca1D9c2DgK+vQ82pkH4vt4LyvQAcLepr16ZGkDRmiO5xfCd3CkbHJ1PrdZJJWgUD9geLRwJwtKgXFF7FvrLBlnt8S/yqSEdL9dWJjgLkTt0VGCe6sIgBCFqUl4POCYLGFjppSoGYw4Nn7jH7Wkmxx8wsRA15OZC3uLMIZTlcn5SnW9ZAWp4e2EenL09vKnc7UO52DMDWoo4L4g2xDJD3E8Y3T6jTLS9XL4g5xvFEnZ5EjKPzlOMYAxC1qI+vsgq0YXGDc2+eMgy5DZg2mCfvVm0wRV24M7NloN3Eoj5GZGl6oOtVRaCWrE45GXxyr2Z5t53DYup5T/ZqQdlPHwJg5Gw6ziaIYGIVY346wZldc1c2G4gRudr1wM6JbTQ+4L/rbjfQVehxHLO1iGxNTx6P7xr7p2vZfy57/uf/rGDq3TGRNRlyDk5wItCzpGeOtglOjddSB5NET5da16jW9vlDyKLWfjhRa4GXJS1CL2SbIwWQYzbpsy0Gxh0Gvm+pjGv2pGpCEBADRUt6QlbEiQpDHGZ0YrvpRCJwtCTjQJynnCu58Hmco73wEt64uHz5EVtsy0G8xfzm/jX7wbVnW4Y8TdmW1Smm/nsoeJNbDthZ6nOTg4Nsd1PEhrcrQD8yw3wjw4iyXw7l57jwOBW282BZGwLr8xLQtaRHj04FDfLuMp1OGv7FDKaY4nIAjw8axk2QA3W9J7OGqC5TxBAnIW27Htsd6y/St+6Yl9fDPOadcL32nLTBMuTVygbAtS9raCL7o/FqIiFpuxrY8cJgEZF1KoPjm8t+aZD32RxZExOyNR1Zw/NzZdkwIMgZ1+fRbCwYhLo9S6LYCNvBCVlCbnY5oHPaBNO6UvYJiVzgenU2ZnaB+wywAYgz0jTto5XUMRW7orf8x5jsJXuf86m5frz5hYPdjAytF/t+cIklTOMxgzvsY9kdMzCz+wtG3QJH5PJgt8RJg93xkFwDvB0pdKX+9iQjV051K/e3OSyJ7z7sN8clAd5tdp6Bp2W9AKo02FUZd26ax5653R0pwzVZ3nDqGkT+/B5PsEURBnqWtXtLo8M0NR4rjwcITv7CmZTnnU+cq9TunnzmDnlMJca8GXha1nsJtR0W+ZdzDP4nWZUZ2jNtVVbmhCfEDEQt99xFUM0gd8NpCrN4Sp9nEjp1zqmohzjR6DnRQwjheQbeluWITIQHarXIjPv2DYKWYgGulqVrwOeqkksCn0z405OJ2VNdwtUiGOncUCUynT8xhnSHsCMjZIGxZe05b8vDneOWtd+lREHiJkV6ty+a0JCJi7WlbgAfer98A3jyflMQtJi73YKsbQFwn7TjHX+7nEpxYscr6sONOxC+SNqkAPLT7IL3wXQg7PJQbOvE+2vLfLd3f92oYxhswwoytCUw3enIsgBNu3cQI8uefCrRe/mgbHxOZh6SVSXC8WLVU8p6wD63oRy/vW6YndLfUdbE0Sm1UXJKAX5W9OjGKWEpf8ziddx37X6srYfyc1PecRs9tsc6GfRG4Y/lHK/a67EewJsQtgqErWjpefrwBov5gevgfY8AK7C0oueOh2jKxOzGT7kC3OuWqgJVK73pI+5/tDX3JeFKq1uY1rgkxq+JEXwkgJhiBAe5W01LAryjz2ZFEqf9jrPKChMX78dbTymW3mJWZHELIDts+2Z5sx3XN0D2xPHNqfVlEIZ6FSmclJl+WhWSrkzsKko7ayPerJI2AP2WjISK/O16iJ87yB7Pb3UZ7d/6S8xwVPZ/c58JsIBvQ/p2Pb4byfgaMjhtNuKUBTpfv79zRTymHumIpYWb6Ul+q1NGscoQoyGL68p6DRLU8Nb096F320HXjmyU7zYJZJG9aXGvU43vHN/N2bcpa9luNmRuC+D71ErIytU0WZvD1hqwtftkEs02DWnZjx/9vJAJGxduct8GetPezOFz28ZftEgY59Uw3ss8qwFZq2KanpSeNymNjjvVnE7uGIhCWC7Xem45HPjed2uIiq6pdqEuh+0+ev8GPK3KXcWnbO81V2xT43DHkxh9sgcxxhpVEGPEPdBXU7IYts8JeS1jdC1yYAHJiZBXOUizOU46gKRVadL9aftGzZhYBsXzRdvLJacWIvGeHPJ0+PWA3Wl4k46wHsCbWWelA6ha1Tsgr5bwYkD2n1MG8w5oNhleSAaVDmRtS+C7xxwnHUjXlgB33KLMQik6HmU1YefQtyn77OJ4AURRVelAtqZXa0GxYXLkrTN8RmaFgVl4sU4DI51DNw+sCpVDJEqcDqRtl4P8igvBzhfOdiEYekW4HBzA+JngjBAjebsc4o0cZJND+qbNiJoa9s44I36Z1syohpL6Eava7OseEP0iC0GMFO56iJ/Ke7cw5E7gu4v0hvuh71Xdun6aNRDASOX0IrOqRSbNznJ4N8ArJ4omhyzuemy3+8I5ZHHXY/xk0NL4KCJWJHEnM7SSmcW5z2EGAow0Tu/iq1KZ8XA9XMCS177NTA6p3AoAjyskTYZQWiLJTK6vkixZMDnvmMo5pHIrwLuVX29ySOT0JWwluc6s/dusD926CAOPu4v7YNyDhkVy3OMnveJZktRh316H3URflBq5m7jBgzj7Y0Wcn2Ic44TjO8HVxjeaUw+50Do5eSB0rberR68SVSvCf1qVDF8eb7GS88DjmrY0q+SEqmvwjDib4VH7E4JUNkY+mbYHdVQYOA0k+bAcuHs8WiBvTa85/UegLQbrH34da76+GAyNdnp+3gdJJU/8vL+ZNY4nuWnwwNya3BEZ0XXh9ID7HRcAT7gc5kdMDp2y0QhivuOBuTUxXf92gOG+lx1gFloSDe+IrBsidQiQmLt54G6tO/3ldoymv+7X/mIFNfVD40lWU5847ERVIrIoEXU9gPf4siFhWwDYSdfFU4dnD/po0PAsIGHT1oflwxtCHMupp+R7fON+veFOcoXJSkPjSpgSoMjP9LiskXGverjpeHPPsHzBDUjTLod3i3IbkKDpgGf3rY78yz/SPV4HJlXbMUW1nI2Fhih3V/He8ds9HGGMZO16jDdJtUoBmdr10A77HFqUfD1vTr4m7psdZukIJUrDb5JW7zcXA4dtI3E2L9vCWz5tcgmPLK27ghcftcgj3VDWQ3gTP7MU6nrY/vdHrfzv/wU=\", BinaryEncoding.Base64), Compression.Deflate))"
      }
    ],
    "tables": [
      {
        "name": "Sales",
        "columns": [
          {
            "name": "line_id",
            "dataType": "int64",
            "sourceColumn": "line_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_id",
            "dataType": "int64",
            "sourceColumn": "order_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_date",
            "dataType": "dateTime",
            "sourceColumn": "order_date",
            "summarizeBy": "none",
            "formatString": "yyyy-MM-dd"
          },
          {
            "name": "customer_id",
            "dataType": "int64",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "product",
            "dataType": "string",
            "sourceColumn": "product",
            "summarizeBy": "none"
          },
          {
            "name": "channel",
            "dataType": "string",
            "sourceColumn": "channel",
            "summarizeBy": "none"
          },
          {
            "name": "quantity",
            "dataType": "int64",
            "sourceColumn": "quantity",
            "summarizeBy": "none"
          },
          {
            "name": "discount_pct",
            "dataType": "int64",
            "sourceColumn": "discount_pct",
            "summarizeBy": "none"
          },
          {
            "name": "returned",
            "dataType": "int64",
            "sourceColumn": "returned",
            "summarizeBy": "none"
          },
          {
            "name": "net_revenue_cents",
            "dataType": "int64",
            "sourceColumn": "net_revenue_cents",
            "summarizeBy": "none"
          },
          {
            "name": "profit_cents",
            "dataType": "int64",
            "sourceColumn": "profit_cents",
            "summarizeBy": "none"
          },
          {
            "name": "cogs_cents",
            "dataType": "int64",
            "sourceColumn": "cogs_cents",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Sales",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                " Source = Table.FromRecords(SampleRows),",
                " Selected = Table.SelectColumns(Source, {\"line_id\",\"order_id\",\"order_date\",\"customer_id\",\"product\",\"channel\",\"quantity\",\"discount_pct\",\"returned\",\"net_revenue_cents\",\"profit_cents\",\"cogs_cents\"}),",
                " Typed = Table.TransformColumnTypes(Selected, {{\"line_id\", Int64.Type},{\"order_id\", Int64.Type},{\"order_date\", type datetime},{\"customer_id\", Int64.Type},{\"product\", type text},{\"channel\", type text},{\"quantity\", Int64.Type},{\"discount_pct\", Int64.Type},{\"returned\", Int64.Type},{\"net_revenue_cents\", Int64.Type},{\"profit_cents\", Int64.Type},{\"cogs_cents\", Int64.Type}}, \"en-US\")",
                "in",
                " Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Net Revenue",
            "expression": "DIVIDE(SUM(Sales[net_revenue_cents]), 100)",
            "formatString": "$#,0.00"
          },
          {
            "name": "Gross Profit",
            "expression": "DIVIDE(SUM(Sales[profit_cents]), 100)",
            "formatString": "$#,0.00"
          },
          {
            "name": "Gross Margin",
            "expression": "DIVIDE([Gross Profit], [Net Revenue])",
            "formatString": "0.0%"
          },
          {
            "name": "Orders",
            "expression": "DISTINCTCOUNT(Sales[order_id])",
            "formatString": "#,0"
          },
          {
            "name": "Average Order Value",
            "expression": "DIVIDE([Net Revenue], [Orders])",
            "formatString": "$#,0.00"
          },
          {
            "name": "Return Line Rate",
            "expression": "DIVIDE(SUM(Sales[returned]), COUNTROWS(Sales))",
            "formatString": "0.0%"
          },
          {
            "name": "Revenue Previous Year",
            "expression": "CALCULATE([Net Revenue], DATEADD('Date'[Date], -1, YEAR))",
            "formatString": "$#,0.00"
          },
          {
            "name": "Revenue YoY",
            "expression": "DIVIDE([Net Revenue] - [Revenue Previous Year], [Revenue Previous Year])",
            "formatString": "0.0%"
          },
          {
            "name": "Loss Making Lines",
            "expression": "COUNTROWS(FILTER(Sales, Sales[profit_cents] < 0))",
            "formatString": "#,0"
          }
        ]
      },
      {
        "name": "Product",
        "columns": [
          {
            "name": "product",
            "dataType": "string",
            "sourceColumn": "product",
            "summarizeBy": "none"
          },
          {
            "name": "category",
            "dataType": "string",
            "sourceColumn": "category",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Product",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                " Source = Table.FromRecords(SampleRows),",
                " Selected = Table.SelectColumns(Source, {\"product\",\"category\"}),",
                " Typed = Table.TransformColumnTypes(Selected, {{\"product\", type text},{\"category\", type text}}, \"en-US\")",
                "in",
                " Table.Distinct(Typed)"
              ]
            }
          }
        ]
      },
      {
        "name": "Customer",
        "columns": [
          {
            "name": "customer_id",
            "dataType": "int64",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "segment",
            "dataType": "string",
            "sourceColumn": "segment",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Customer",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                " Source = Table.FromRecords(SampleRows),",
                " Selected = Table.SelectColumns(Source, {\"customer_id\",\"region\",\"segment\"}),",
                " Typed = Table.TransformColumnTypes(Selected, {{\"customer_id\", Int64.Type},{\"region\", type text},{\"segment\", type text}}, \"en-US\")",
                "in",
                " Table.Distinct(Typed)"
              ]
            }
          }
        ]
      },
      {
        "name": "Date",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "formatString": "yyyy-MM-dd",
            "isKey": true
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                " Source = Table.FromList(List.Dates(#date(2024,1,1),731,#duration(1,0,0,0)), Splitter.SplitByNothing(), {\"Date\"}),",
                " Typed = Table.TransformColumnTypes(Source, {{\"Date\", type datetime}}),",
                " Year = Table.AddColumn(Typed, \"Year\", each Date.Year([Date]), Int64.Type),",
                " Month = Table.AddColumn(Year, \"Month\", each Date.ToText(Date.From([Date]), \"yyyy-MM\"), type text)",
                "in",
                " Month"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "bab4af01-7b81-550d-b1cb-edfc22220c1e",
        "fromTable": "Sales",
        "fromColumn": "product",
        "toTable": "Product",
        "toColumn": "product",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "a344e97a-4526-5156-965b-9aa609298b6f",
        "fromTable": "Sales",
        "fromColumn": "customer_id",
        "toTable": "Customer",
        "toColumn": "customer_id",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "83005bd7-4e68-5780-ab76-6c8098fddeae",
        "fromTable": "Sales",
        "fromColumn": "order_date",
        "toTable": "Date",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection"
      }
    ]
  }
}